model/sharing/indexer.go
model/vfs/couchdb_indexer.go
model/vfs/vfs.go
tests/integration/tests/sharing_rename_dir.rb

When a directory is shared from Cozy to Cozy, the stack uses a protocol inspired by the replication protocol of CouchDB. It means that the new documents are sent in bulk, and several changes to the same document are regrouped.
For a tree of directories, the stack has to update the fullpaths of the descendants when a directory is renamed or moved. This is often done in the sharing by recomputing the fullpath when the new revision of the given document is synchronized. But if this happens for a child before the parent has been renamed/moved on the recipient's instance, it was failing (index_bad_fullpath was reported by FSCK).
Now, when the parent directory is updated, the stack also recomputes the fullpaths of the descendants (like the normal indexer of the VFS).

Fix index_bad_fullpath on shared directories

---

model/account/accounts.go
worker/migrations/migrations.go

In some connectors, e.g. EDF, the account have a `auth.email` instead of `auth.login`. In which case, the `auth.credentials_encrypted` [only contains the password](https://github.com/cozy/cozy-stack/blob/10cca451b61365aa3d1cc39dc24336070672bc7b/web/data/accounts.go#L155-L163) ; then, the account migration worker was missing the `email` field.

Use email account if login is empty

---

model/sharing/files.go

When a directory is created inside a shared directory, it will be
synchronized in bulk. It can happen that this directory will be
synchronized after one of its children. On this case, the stack will
create via a specific method, and inside the code of this method, we
were forcing the cozyMetadata like if the folder has been created on the
recipient instance. The culprit line has been removed, which should fix
the bug.

Fix lost of cozyMetadata for some shared directories

---

assets/locales/en.po
assets/locales/fr.po
model/sharing/files.go
tests/integration/lib/folder.rb
tests/integration/tests/revoke_sharing.rb

When a sharing is revoked, the directory is kept on the recipients'
instances. If a new sharing is made for the same directory, the
recipients that accept it will have a conflict between the directories
for the old sharing and the new one. It can be confusing. To avoid that,
the directory is renammed when the sharing is revoked (with a suffix).
It will also help people understand that a sharing has been revoked.

Add a suffix to revoked sharing directories

---

docs/sharing-design.md
model/note/note.go
model/sharing/files.go
model/sharing/revisions.go
model/sharing/revisions_test.go
model/sharing/upload.go
tests/integration/tests/sharing_conflicts.rb

When a note is in a shared directory, the stack should avoid to modify
the content and rename the note in a single CouchDB revision. It doesn't
play nicely with the sharing, as the stack has to create a new revision
on the recipients' instances. And if there are several instances, the
new revisions can be different, leading to conflicts.
To fix that, the stack now makes a first CouchDB revision with the
renaming, and only after that, writes the new content to the VFS.

Improve notes handling in shared directory

---

model/sharing/setup.go

When an empty directory is shared to a recipient in read-only, and the
recipient accepts the sharing, the directory wasn't created until a file
was added to this directory by the sharer. It is now fixed.

Fix sharing an empty directory in read-only

---

model/sharing/revoke_trashed.go
model/sharing/sharing.go
model/vfs/couchdb_indexer.go
tests/integration/tests/revoke_sharing.rb
web/sharings/revoke.go

When a sharing is made for a file or folder, and this file or folder is
put to the trash, the sharing should be revoked. Before this commit, it
wasn't the case, and everything inside the shared folder was also put in
the trash, and the synchronisation of the sharing makes the content in
this folder not available for all the members of the sharing. Not good!
Now, the sharing is revoked before the synchronisation can happen, and
the other members of the sharing will keep the content available (ie not
in the trash).

Revoke a sharing when its root is trashed

---

pkg/couchdb/couchdb.go
web/data/data_test.go

CouchDB returns `bookmark:"nil"` for queries with no docs to return. For instance, see the response of this [request](https://docs.couchdb.org/en/2.2.0/api/database/find.html#post--db-_explain) 
This can be dangerous for clients that would test a bookmark existence with something like `if (bookmark)`, so we return `bookmark:""` instead

Return empty string when no bookmark

---

model/note/note.go
web/notes/notes.go
web/shortcuts/shortcuts.go

When a note or a shortcut is created via their special API, the stack
checks the permission to write on the VFS. Before this commit, only a
permission on the whole io.cozy.files doctype was authorized. Now, we
also accept a permission on the directory where the note or shortcut
will be created. It is useful when a directory is shared by link for
example.

Improve permissions checking for notes and shortcuts

---

docs/files.md
web/files/files.go
web/files/files_test.go

Chromium based browser do not allow the use of the `Date` header
when using XHR. We now introduce a new UpdatedAt param we can use
when uploading a file or a folder to set the modification date of
the file.
(see https://github.com/cozy/cozy-client/issues/690)

feat: Add UpdatedAt param to file upload

---

web/middlewares/permissions.go
web/settings/disk_usage.go

When a directory is shared by link with a write access, the anonymous
users that go on this link can check to the disk-usage to see if the
limit of quota is reached.

Be less strict on access control for disk usage

---

web/auth/auth.go
web/oidc/oidc.go
web/oidc/statestore.go

When a user tries to connect a mobile app and their instance is on a
context where the login with OIDC is required, it wasn't working because
the OAuth danse was lost during the OIDC authentication. The stack will
now preserve the redirect, which should enable to restart the OAuth
danse after the user has been authenticated.

Preserve the redirect parameter on OIDC

---

model/sharing/files.go
model/sharing/files_test.go
tests/integration/tests/sharing_moves_n_delete.rb

From the sharer side, we sort docs before replication in order to apply a bunch of rules, e.g. directories before files.
We also implemented a [rule](https://github.com/cozy/cozy-stack/commit/4f9a4cdc7134cb586d4461c2b4c05cf3c8a01b8a) on the recipient side in order to put the deleted files at the end, to efficiently deal with moves. However, the sort behavior was not the expected one, and it was also contradictory with the sort performed by the sharer. As it result, it was causing errors like [this one](https://github.com/cozy/cozy-stack/blob/master/model/sharing/files.go#L875) because the recipient was mistakenly trying to recursively rebuild the hierarchy.
Therefore, we remove this sort on the recipient side and implement it on the sharer side, with the other rules.

Fix sort for deleted files

---

cmd/check.go
cmd/fix.go
cmd/instances.go
model/sharing/revisions.go
model/sharing/shared.go
model/vfs/couchdb_indexer.go
model/vfs/errors.go
model/vfs/fsck.go
model/vfs/vfsafero/fsck.go
model/vfs/vfsswift/fsck_v1.go
model/vfs/vfsswift/fsck_v2.go
model/vfs/vfsswift/fsck_v3.go
pkg/couchdb/index.go
tests/integration/lib/instance.rb
tests/integration/lib/stack.rb
tests/integration/tests/avoid_name_conflict.rb
tests/integration/tests/loop_shared_file.rb
tests/integration/tests/multiple_sharings.rb
tests/integration/tests/revoke_sharing.rb
tests/integration/tests/sharing_conflicts.rb
tests/integration/tests/sharing_moves_n_delete.rb
tests/integration/tests/sharing_push_folder.rb
tests/integration/tests/sharing_read_only.rb
tests/integration/tests/sharing_referenced_by.rb
tests/integration/tests/sharing_remove_folder.rb
tests/integration/tests/sharing_rename_dir.rb
tests/integration/tests/sharing_sync.rb
web/instances/checks.go
web/instances/instances.go

- The `cozy-stack instances fsck` command is renamed `cozy-stack check fs`
- this command will now also check that the `trashed` attribute of files is consistent with the fullpath of its parent
- a new `cozy-stack check shared` command has been added to check io.cozy.shared documents.

Add more checks for the consistency of instances

---

model/bitwarden/cipher.go
pkg/couchdb/couchdb.go
tests/integration/konnector/manifest.konnector
tests/integration/lib/account.rb
tests/integration/lib/instance.rb
tests/integration/lib/stack.rb
tests/integration/tests/account-to-ciphers.rb
tests/integration/tests/accounts-to-ciphers.rb
web/data/accounts.go
worker/migrations/migrate-accounts-to-organisation.go
worker/migrations/migrations.go

Previously, only login and password were copied to bitwarden ciphers when vault was created. Since some konnectors rely on other fields (for example Pole Emploi relies on
"zipcode"), we have to copy other fields contained from the account "auth"
attribute.
The support for additional fields has been done in Harvest.

feat: Support additional fields when copying accounts to ciphers

---

model/sharing/indexer.go
tests/integration/lib/couch.rb
tests/integration/tests/sharing_conflicts.rb

In some cases, unexpected CouchDB conflicts were produced on shared directories, leading to unexpected behaviors. For instance, after a delete on a conflicted directory, the winning revision branch was removed, but the lost one was still there, causing the directory to re-appear from the last conflicted revision.
These conflicts were caused because we force the revision list on shared documents in the [bulk_docs](https://docs.couchdb.org/en/stable/replication/protocol.html#upload-batch-of-changed-documents) replication route, as specified in the CouchDB documentation. In particular, the `new_edits` field, when set to false, avoids to generate a new revision, but can produce conflicts when a specified revision differ from a local one with the same number, e.g. `2-aa` vs `2-bb`.
See the …

Fix couchdb conflicts on directories

---

model/sharing/replicator.go
tests/integration/tests/sharing_conflicts.rb

We used to have a lock when sending shared documents but not on their
reception. This could cause CouchDB conflicts when an instance receives
at the same time changes on the same document from different instances.
To illustrate a possible scenario of such conflict, let's assume a shared directory with the revisions list `{1-aa, 2-aa}` between the instances A, B and C.
At the same time, instance A receives changes from B and C, respectively with the revisions lists `{1-aa, 2-bb}` and `{1-aa, 2-cc, 3-cc}`.
Changes from B are applied: the revision `2-bb` conflicts with the local `2-aa`, and is solved by generating a new local update, producing the revisions list `{1-aa, 2-aa, 3-aa}`.
Simultaneously, the changes from C are applied: the last local revision is still seen as `2-aa` and the …

Add lock on sharing reception

---

tests/integration/tests/sharing_conflicts.rb

CI sometimes fails on this test, that might be because it has no enough time to end

Increase sleep duration

---

model/sharing/indexer.go
tests/integration/tests/sharing_conflicts.rb

When there is a cozy to cozy sharing and the stack updates an
io.cozy.file document with _bulk_docs, it happens that the revisions
chain received is not used with all the revisions. In that case, the
stack mixes the received revisions chain with the local revisions for
_bulk_docs. And we should use the same mixed chain to update the
io.cozy.shared.

Fix updating the io.cozy.shared

---

model/sharing/revisions.go
model/sharing/revisions_test.go
model/sharing/shared.go
model/sharing/upload.go
pkg/couchdb/couchdb.go
pkg/couchdb/couchdb_test.go
tests/integration/tests/sharing_conflicts.rb

When a shared document has updates both from local and remote instances,
the remote revisions might be saved before the local ones in the
revisions tree. If there are several updates, this could cause integrity
issues in the tree. Here is an illustrative scenario:
1. A shared doc has the revision 1-a.
2. The doc is updated twice locally, producing the revisions 2-a and 3-a.
3. The doc is also updated twice on a remote instance, producing the revisions 4-b and 5-b.
4. The revision tree has still the 1-a revision and the following chain is saved: `[3-a, 4-b, 5-b]`. It corresponds to the last local revision (3-a) and the incoming remote revisions (4-b, 5-b).
5. The 2-a revision will be later saved in the tree, in a new branch starting from 1-a.
To solve this, at the step 4, we retrieve the …

Fix shared integrity

---

model/sharing/files.go
model/sharing/revisions.go
model/sharing/revisions_test.go
model/sharing/upload.go
tests/integration/tests/sharing_conflicts.rb

When a shared file is updated often by several members of the sharing,
it will lead to conflicts. And if several conflicts happen on the same
file, the stack can try to use a new name for the old content that was
already used. It fails and it aborts the upload of the new content. With
this commit, the stack will try harder to avoid already used names for
conflicts.

Fix multiple conflicts on the same file

---

docs/auth.md

doc(auth): Urlencode scope's colon in examples

---

docs/files.md
web/files/files.go
web/files/files_test.go

The `UpdatedAt` parameter was used during a file creation but not
during a file update.
Updating the `CreatedAt` field is not allowed so we don't try to fetch
and parse this parameter.

Allow setting UpdatedAt during file update

---

docs/konnectors-workflow.md
model/account/type.go
model/account/type_test.go
web/accounts/oauth.go
worker/exec/konnector.go
worker/exec/konnector_test.go

Until now, the same account type document was used for all the instances on a same server. It is now possible to override the account type of a konnector for a given context, by creating a new document with an id prefixed by the context name and /.

Allow to override an account type per context

---

docs/sharing.md
model/instance/lifecycle/patch.go
model/sharing/reupload.go
web/sharings/replicator.go

When the disk quota for an instance has increased, we look at the
sharing and ask the other instances to reupload the files. It is a
better user experience, as someone who just paid for premium to get
space will expect that the sharing will synchronize shortly after that.

Ask reuploading files after disk quota increase

---

scripts/Dockerfile
scripts/cozy-app-dev.sh
scripts/docker-entrypoint.sh

This way, connectors can be run in the cozy-app-dev image without any special setup, but this add
75Mo to the cozy-app-dev image.
Another solution would be to create another docker image specific for this goal.

feat: allow connectors to be run in cozy-app-dev image

---

web/instances/instances.go

When creating an instance through admin API and `SwiftLayout` parameter is ommited, it uses the default value of `0` which means swift layout v1 regardless of configured default swift layout.
This PR fixes this behaviour by using the configured default swift layout if the `SwiftLayout` parameter is ommited when calling the instance creation admin API

Defaults to default swift layout if parameter is absent

---

model/instance/lifecycle/create.go
model/instance/lifecycle/lifecycle_test.go

Instance creation using swift layout v1 is known to be bugguy since the introduction of instance prefix somewhere during life of swift layout v2, leaving an instance with unexpected swift containers using prefix for file and version container but using domain for data (thumbnails) container.
We still neeed to keep swift layout v1 compatibility for old instances but don't need to create new instances in that layout that would obviously be bugguy.
This PR disables creation of instances using swift layout v1.
This PR also ensure most of the unit tests (otherwise explicitely chosen) use the default swift layout instead of the old v1 layout.

Disable instance creation using swift layout v1

---

docs/notifications.md
model/account/type.go
model/notification/center/push_message.go
worker/push/push.go
worker/push/push_test.go

The push notifications can be sent via Firebase to mobile. When we have
several apps developed by several organizations, it can be useful to use
several Firebase accounts. It is now possible. The keys are stored in
the global/io.cozy.account_types database, with a document per app (and
it can be also restricted to a context).

Allow to configure firebase per app

---

pkg/couchdb/bulk.go

When the ForeachDocs function is called on a database with more than 100
design documents, the pagination can have a page with just design docs.
The function stopped here, even if there were other documents further.
This fix will avoid stopping the ForeachDocs too soon.

Fix ForeachDocs with 100+ design docs

---

model/sharing/revisions.go

When there are multiple changes on a shared document, both on the local
instance and on other instances of the sharing, it was possible to have
a race condition that leads to a panic on the addMissingRevsToChain
function.

Fix a panic on addMissingRevsToChain

---

cmd/apps.go
docs/CONTRIBUTING.md
scripts/build.sh

Small fixes that were waiting on my computer...
- Fixes on external assets
- Fix installation message: it would report "app already up-to-date"
in case of a downgrade
```shell
$ cozy-stack apps install banks2 registry://banks/dev
banks2 has been installed (1.20.1-dev.c5cae281599037051902)
$ cozy-stack apps update banks2 registry://banks/dev
banks2 is already up-to-date at 1.20.1-dev.c5cae281599037051902
$ cozy-stack apps update banks2 registry://banks/stable
banks2 has been downgraded to 1.20.0
$ cozy-stack apps update banks2 registry://banks/dev
banks2 has been upgraded to 1.20.1-dev.c5cae281599037051902
```

Improvements

---

docs/README.md

Since https://docs.cozy.io/en/cozy-stack/ links to cozy-stack/docs/README.md, there is no way to give an overview of what the Stack is on our documentation's website. 
By adding those few lines coming from ./README.md, it fixes the issue. (though I'm not sure this is the best way to fix it)

docs: Update docs/readme

---

docs/files.md

Trashed documents not only have a new `trashed` attribute, they also
have a `restore_path` attribute with their previous parent path and
their `dir_id` is changed for the Cozy Trash special id.
Although those are rather internal attributes, they can be useful when
stubbing a response from the stack or a Cozy CouchDB record.

docs: Add dir_id and restore_path to trashed docs

---

cmd/apps.go

Refine cli message on app installation to include domain
Before:
`store has been installed (1.9.2)`
After:
`store (1.9.2) has been installed on cozy.domain.name`

Refine app install message on cli

---

docs/bitwarden.md
model/bitwarden/cipher.go
web/bitwarden/bitwarden.go
web/bitwarden/bitwarden_test.go
web/bitwarden/ciphers.go

Bitwarden now [supports](https://github.com/bitwarden/server/pull/684) a trash system, where (soft) deleted ciphers are actually updated with a `deletedDate` attribute. Then, the client filters the ciphers having this attribute to display them in a Trash.
The restore simply consists of removing this attribute.
This PR adds the soft delete and restore routes.

Support SoftDelete and Restore routes for bitwarden

---

model/bitwarden/cipher.go

This is useful to support field-based permissions on ciphers, such as trigger `@event com.bitwarden.ciphers:UPDATED:!=:deletedDate`.

Implement Fetcher for ciphers

---

client/instances.go
cmd/files.go
web/instances/instances.go

We sometimes need to know the size of the trash for an instance.
This PR adds a `--trash` flag to `cozy-stack files usage` command and a corresponding `include=trash` query param to the `disk-usage` admin API (similar to the `include=trash` query param of the `settings/disk-usage` endpoint that return the total size of files inside the trash.
This functionnality is hidden behind a flag for two main reasons:
- keep exact compatibility with existing command
- Walking through all files in the trash can be particularly time consuming and not always needed

Add trashed files size to files usage cmd

---

web/middlewares/basic_auth.go

The traced time was taking the time to compute the next handler, and not
just to check the basic authentication.

Fix trace in BasicAuth middleware

---

cmd/config.go
cmd/instances.go
cmd/swift.go

Add command aliases for user-friendliness.
Also ensure all commands are coherents and match with de-facto standard (`create`, `list`, `show`, `delete`)

Add command aliases for user-friendliness

---

worker/exec/konnector.go

I am not sure of my go syntax but here is what I want :
Accounts with USER_ACTION_NEEDED.CGU_FORM need an action from the user on the website but
it is possible that the user will do this action without knowing this is needed for the connector
and there are some cases the ameli connector where the connector sees the CGU from but not the
user because this form is displayed only when the user connects to his ameli accout, and the
ameli session can be long.
At the moment, I run all the USER_ACTION_NEEDED.CGU_FORM accounts progressively and manually.
I would be nice if the stack would do it automatically and this is the goal of this PR

feat: Still continue to to run acount with USER_ACTION_NEEDED.CGU_FORM message

---

model/vfs/fsck.go
model/vfs/vfsswift/fsck_v3.go

When checking the file system of an instance in Swift layout v3, the
stack will also warns for thumbnails where the file that have been used
to generate it is missing.

Detect thumbnails with no file

---

assets/locales/en.po
assets/locales/fr.po
assets/scripts/onboarding.js
assets/styles/stack.css
assets/templates/passphrase_onboarding.html

When the stack asks for the passphrase during the onboarding, the hint
field is now masked to avoid confusion with a a passphrase confirmation.
It can be shown by clicking on the "Leave a hint" link.

Improve the onboarding page

---

model/permission/permissions.go
web/permissions/permissions.go
web/permissions/permissions_test.go

When a permission document is created for a share by link use case, the
stack keeps in the source field the slug of the app that has created the
permission. Later, if the permission is updated or revoked, the stack
was only authorizing the same application to do that. Now, it can also
be another app that has a superset of the given permissions. For
example, if a note is shared from the notes application, it is now
possible to revoke this sharing from Drive.

Change the ownership of the share-by-link permissions

---

docs/apps.md
model/app/webapp.go
web/apps/apps_test.go

Some services can be called programmatically and the stack should allow
those services to have no triggers.

Allow services to have no triggers

---

model/sharing/member.go

When a recipient is added or removed from a sharing, the stack notifies
the other recipient of this change. With the new possibility to have
shortcut to a sharing, we can have recipients to notify with no OAuth
client. In that case, we need to abort the access token refresh to avoid
a panic.

Fix a panic when refreshing a token

---

assets/scripts/renew-password.js
assets/templates/passphrase_renew.html

When the stack asks for the passphrase for renewing the passphrase, the
hint field is now masked to avoid confusion with a a passphrase
confirmation. It can be shown by clicking on the "Leave a hint" link.

Improve the renew passphrase page

---

model/note/open.go
model/sharing/sharing.go
web/permissions/permissions.go

When a sharing has been accepted by a member, and then revoked, the
stack may have kept a permission of type share-interact for this
sharing. If the same member accepts the sharing again and creates a note
inside the new shared folder, the other members would have used the
share-interact permission on the old folder, which fails. This commit
fixes this issue by checking that the permission set is correct, and by
updating it if needed.

Fix opening a note in a shared directory

---

model/vfs/file.go

When a file is requested to be put in the trash, the stack looks if it
is not already in the trash. It was done via checking if its path
doesn't start by the trash name. But there is also a trashed attribute,
and we can check both. If only one of those is true, we have an
inconsistency and we can hope that moving the file again to the trash
will help fixing it.

Force trashing file

---

worker/migrations/migrations.go

Logging migration type along with success or error makes it easier to count successful or failed migration of one particular type without being polluted with other migration type messages.

Log migration type on success or error

---

model/account/type.go
web/accounts/oauth.go

When an account type is configured for a service on a context (and not
for the whole stack), we need to remove the context prefix when checking
the service name after the redirection on the OAuth flow.

Fix the OAuth workflow for konnectors

---

model/vfs/directory.go
model/vfs/errors.go
model/vfs/vfs.go
web/files/files.go

When a path has more than 512 levels, the walk function of the VFS
reaches a limit and fails. To avoid this issue, we don't allow to create
directories with a too depth path.

Forbid to create a too depth directory

---

model/vfs/vfsswift/impl_v3.go

When using the VFS Swift backend, the deletion of old versions can reuse
code for emptying the trash: it makes several calls to Swift, with a bit
of waiting if needed and a retry logic.

Make the deletion of old versions more robust

---

docs/sharing.md

All the attributes are described in the cozy-doctypes documentation.

docs: Add link to io.cozy.sharings docs

---

docs/permissions.md
model/sharing/member.go
pkg/consts/doctype.go
web/permissions/permissions.go

When the GET /permissions/self route is called with a sharecode, the
stack will include the information about the linked member in the
response. In particular, if the instance field is filled, it means that
this member had a link to this sharing in their Cozy instance.

Include the sharing member in GET /permissions/self

---

.github/workflows/assets.yml
.github/workflows/ci.yml
.github/workflows/cli.yml
.github/workflows/integration.yml
.github/workflows/release.yml
.github/workflows/windows.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Fix deprecated GitHub Actions commands

---

model/sharing/upload.go

When a file was in a shared directory, was trashed, and is now restored,
the stack should be able to make the file available for all the members
of the sharing. It is not the case today, and this commit is not enough
to do so. But, at least, the file isn't moved again to the trash by the
sharing for the user who restored the file.

Fix echo on restore file deleted from a shared dir

---

model/vfs/couchdb_indexer.go
model/vfs/vfsswift/impl_v3.go

When the user asks for emptying the trash, the stack puts a job for the
trash worker that will do the real work in background. In particular, it
cleans the old versions. There was a bug that made the bulk requests for
deleting old versions in CouchDB on the wrong database. Let's fix that!
And improve our logs, even if the logs couldn't have given us a clue,
because the CouchDB call on the wrong database is still a success:
deleting documents that don't exist is OK for CouchDB.

Fix deleting old versions on emptying trash

---

docs/files.md
model/sharing/files.go
model/vfs/metadata.go
pkg/consts/doctype.go
pkg/consts/file.go
web/files/files.go

The metadata map for io.cozy.files cannot have a carbonCopy or
electronicSafe key unless the app/konnector that adds it has a
permission on io.cozy.certified.carbonCopy /
io.cozy.certified.electronicSafe.
When a file with such metadata attribute is shared, this attribute will
be removed on the instances of the other members: this attribute is only
valid localy, we don't want to trust other instances as it is easy to
cheat for a self-hosted.

Check carbonCopy and electronicSafe metadata

---

model/permission/doctype.go
model/permission/match.go
model/vfs/permissions.go
web/files/files_test.go
web/files/permissions_test.go

The files permissions are handled differently from the other doctypes, and it wasn't possible to request `io.cozy.files` docs when using a `io.cozy.files.*` permission. This should fix this behaviour.

Fix files wildcard permission

---

model/permission/set.go
web/sharings/sharings_test.go

It was not possible for an app to have a wildcard permission on a doctype and use the sharing on a doctype included in this wildcard

Allow wildcard permission for sharing

---

docs/notifications.md
docs/workers.md

Adding a few lines about SMS notification. I haven't used it yet, but it will help answer some questions from partners ;). But I'm not sure that ./worker#sms is the best place to do it.
I'm wondering, currently for push notification configuration, we're setting a document in the `secrets/io-cozy-account_types` database. Can we do the same for SMS provider?

docs: Add docs about SMS notification

---

web/apps/serve.go

When the stack is launched with the --appdir flag, it reads the
permission from the manifest and updates CouchDB when the index page of
an app if served. But, if there are two requests at the same time, it
can lead to a CouchDB conflict, and 500 error for one of those.

Fix a race condition when using --appdir

---

model/notification/center/notification_center.go

Since err can be nil when m.Notifications is nil, we're not sending
any error at the end in that case. We returned a 201 OK whereas we're
not creating anything.
Later in the code, we check if m.Notifications[p.category] exists. If
not we are returning an error. Let's use this error.
I had this case when the app manifest was not well build for the notifications part (having the notifications object part of the permissions object, not a new one)

fix: Do not return err if m.Notifications is nil

---

docs/jobs.md

In order to be precise and facilitate the usage,  
let's use the real variable name / access.

docs: Jobs be accurate when saying env var

---

model/sharing/upload.go
tests/integration/tests/sharing_read_only.rb

When a single file is shared via a Cozy to Cozy mode, this file will
have a referenced_by to the sharing on the recipients instances.

Add a referenced_by on a single shared file

---

docs/important-changes.md
model/permission/match.go
model/permission/permissions.go
model/permission/permissions_test.go
model/permission/set.go
web/jobs/jobs.go
web/middlewares/permissions.go
worker/exec/konnector.go

The permission logic is splitted in many places in the stack and it some cases we didn't handled the wildcard permission logic, in particular for files.
This also removes unused code in web/jobs, where we implemented a specific logic to handle jobs permissions for
apps to manage konnectors. This does not seem useful anymore as this is handled directly through harvest.

Fix lack of support of wildcard permission in several cases

---

docs/bitwarden.md
web/bitwarden/icons.go

The pass clients show an icon for each domain that has a cipher. This
clients request the GET /bitwarden/icons/:domain/icon.png route of the
stack for this icon. This route has now a fallback parameter that allows
to return a 404 Not found error, instead of the default icon when no
favicon has been found for the domain. The clients can then use what
they want for the icon in that case.

Add a fallback parameter for the BW icons route

---

model/app/webapp.go

When the stack receive several requests to install the same application
at the same time, a race condition happens and the triggers for this app
may be created several times. The fix is to create the triggers only
after creating the CouchDB document for the application, as it will
return a conflict in that case.

Fix a race condition when installing app with services

---

model/app/webapp.go
web/apps/serve.go
worker/exec/service.go

When a stack is started with the --appdir option, it should take the .js
file for a service from the given appdir, not from where the application
is normally installed.

Fix services execution with --appdir

---

web/instances/checks.go

The cozy-stack check triggers command returns a list of duplicate
triggers. When we have 3 triggers (or more) that are seen as duplicate,
we can return (1,2) and (2,3), but skip (1,3).

Limit the number of duplicates for check triggers

---

docs/permissions.md
pkg/consts/consts.go
pkg/crypto/utils.go
web/middlewares/permissions.go
web/permissions/permissions.go
web/permissions/permissions_test.go

When creating a permission for a sharing by link, it is now possible to
create a tinycode made of 6 digits by using the `tiny=true` parameter in
the query-string when the sharing has a TTL that doesn't exceed 1 hour.

Add tinycode support

---

web/instances/checks.go

The format of the response was an array of JSON objects with a single
key called `error`. This key was renamed to `type` to be more consistent
with the other errors returned by those endpoints.

Fix check endpoints when a database is missing

---

model/note/markdown.go

Atlastkit is going to be updated on Cozy-Notes, and the new version is coming with:
- 2 new nodes, date and status
- 3 new marks, indentation, alignment and breakout
The markdown serialization of the notes has been updated to include the
content when those new nodes and marks will be used.

Add new nodes & marks to the markdown for notes

---

docs/konnectors-workflow.md
tests/integration/lib/job.rb
tests/integration/lib/trigger.rb
tests/integration/tests/trigger_webhook.rb
web/jobs/jobs.go
web/jobs/jobs_test.go

As a webhook is meant to be used from a third party service, it is
simpler to return an absolute URL for the webhook link.

Return an absolute URL for the webhook link

---

model/instance/lifecycle/destroy.go

A race condition may happen when destroying an instance that leads to a
panic.

Fix a panic on destroy instance

---

model/sharing/shared.go
web/instances/checks.go

Some old io.cozy.shared documents have a JSON with more than 10000
levels of nesting. With go 1.15+, these documents cannot be parsed as
JSON. This commit makes the check shared to return a correct response.

Fix the response for check shared on JSON errors

---

model/instance/lifecycle/create.go
model/instance/lifecycle/patch.go
web/instances/instances.go

When an instance deletion has failed, and the instance has no longer its
database for io.cozy.settings, the command to remove the deleting
flag(1) was failing:
$ cozy-stack instances modify --deleting=false <domain>
Failed to modify instance for domain <domain>
Error: not_found: Database does not exist.

Fix removing the deleting flag

---

model/sharing/member.go

When a member of a sharing is in the ready state, and if they are added
again to the sharing, they were added twice to the sharing. But two
members with the same email address confuse the sharing package (the
wrong credentials may be used), so it is better to avoid this
duplication. The owner can still revoke the member from the sharing if
they really want to add it again.

Fix adding again a "ready" contact to a sharing

---

model/note/note.go

When creating a new note, a call is now made to put the schema. It
updates the updated_at attribute of the file. And this attribute was
used for checking if the file should be renamed when its title has
changed. Now, we are using the created_at to fix notes not renamed
according to their titles.

Fix filename for new notes

---

model/note/note.go
model/note/step.go
web/notes/notes_test.go

When a note has its schema updated, the stack deletes all the steps for
it to force other clients that would be opened to reload the note. But
it can take a few seconds, so it is better to do that in a goroutine.

Purge the steps of a note in a goroutine

---

docs/data-system.md
pkg/couchdb/couchdb.go
web/data/data.go
web/data/data_test.go
web/data/replication.go

This adds the following routes:
- `GET /data/:doctype/_design_docs`: access a design doc
- `DELETE /data/:doctype/_design/:ddoc`: delete a design doc
- `POST /data/:doctype/_design/:ddoci/copy`: copy a design doc
This will be useful in order to optimize the index creation from the client side: we used to create index with no name, relying on CouchDB to generate an id. We now want to create named index, by copying existing index to avoid recomputing existing ones.

Add _design docs routes

---

cozy.example.yaml
pkg/config/config/config.go
web/middlewares/secure.go
web/middlewares/secure_test.go
web/routing.go

Note: the config per context is only available via the `csp_allowlist key`
in the config file (not via the deprecated `csp_whitelist`).

Make CSP configurable per context

---

docs/files.md
web/files/files.go
web/files/files_test.go

When uploading a file to the VFS, the file size can be sent by clients
via the Content-Length HTTP header. But the desktop client had some
issues with that: Electron removes this header when the body is a stream
or a chunked body, and the client doesn't want to load the whole file in
memory before sending it. So, we have added a fallback where the file
size can also be sent via a Size parameter in the query string.

Allow to send the file size via query string

---

web/bitwarden/bitwarden.go
web/bitwarden/bitwarden_test.go

The bitwarden clients are now expecting the kdf type and iterations on
the login response. This change was made for supporting SSO. The stack
doesn't support that, but we still need to send those fields as the
client logic for deconnection/reconnection is now based on that even
without SSO support.
See https://github.com/bitwarden/jslib/pull/127

Send Kdf and kdfIterations on bitwarden login

---

go.mod
go.sum
model/app/installer_konnector_test.go
model/app/installer_webapp_test.go
pkg/appfs/copier.go
pkg/appfs/server.go
web/apps/apps_test.go

The webapps and konnectors are now compressed with Brotli instead of
gzip. It should help to send less bits to the browsers.

Use Brotli for compressing app files

---

web/auth/auth_test.go
web/auth/register.go

When requesting the GET /auth/register/:client-id route with no
Authorization header, the stack was sending an error but doesn't stop
processing the request. Thus, the information about the client was also
sent in the response. Ouch!
It means that it was possible to get client_secret from a known
client_id, but this attack alone is not enough to get access to the
personal data of the users: an access_token or refresh_token is still
needed.

[SECU] Fix error handling for getting OAuth client

---

model/app/installer.go

Update installer start log message to make is more understandable when debugging

Make app installer start log more meaningful

---

assets/templates/error.html

Otherwise the link stays blue even in a context where the primary color changes.

feat: Use semantic color for link in error.html

---

pkg/appfs/server.go

When the browser devtools are used to disable cache, and the stack is
using afero for apps (not swift), there was a bug where brotli
compressed assets where not served correctly.

Fix serving apps with devtools

---

pkg/couchdb/couchdb.go
web/data/data.go

When asking CouchDB to create the same index twice at the same time, it
respond to one request with a 500 response. So, let's add a retry as a
work-around.

Add a work-around for a couchdb quirk on index

---

.github/workflows/ci.yml
.github/workflows/integration.yml
.github/workflows/release.yml

- Use ubuntu-latest for all the workflows
- Run only two builds for the unit tests, one with the recommended Go
and CouchDB versions, and the other with an old version of Go (to
check that we are still compatible with it) and a more exotic version
of CouchDB

Make the CI simpler

---

model/vfs/vfsswift/impl_v3.go

When creating a file with the VFS Swift, the stack sends to Swift some
custom meta in the HTTP headers. Swift can respond with a 400 Bad
Request if one of those header is not encoded as it expects (url-encoded
utf-8 NFC, I think but it is not clearly documented). Those headers are
not used currently, so let's just remove them to avoid issues.

Don't see some headers to Swift

---

assets/locales/en.po
assets/locales/fr.po
assets/mails/new_connection.mjml
assets/mails/new_connection.text
go.mod
go.sum
model/session/login_history.go
pkg/i18n/i18n.go

With the lack available IPv4 addresses, the providers are reusing their
pool of addresses and it makes harder to geolocalize them. We have more
errors, and the errors confuse a lot our users. So, we think it is
better to remove this information in the new connection mail.
~~And the dependency on the geodb file can be removed as it was only used for that.~~
_Update:_ we keep the dependency on geodb to find the timezone of the user.

Remove geolocation for new connection mail

---

pkg/appfs/server.go

When a konnector was installed before we start using brotli for
apps&konnectors assets on a stack with afero FS (not swift), the files
were saved with a .gz extension. They are now saved with a .br
extension.
When running a konnector, we list the files, decompress them and rewrite
them in the temporary directory that will be used to execute them. We
have forgotten to remove the .gz extension for konnectors that were
already installed and nodejs didn't like that as it was expecting a .js
file.

Fix running already installed konnectors (afero)

---

worker/push/push.go

When a device is registed as several OAuth client with the same
notification device token, we should send only once the notification to
firebase.

Avoid duplicate notification

---

web/data/data.go

While some index-related requests  are expressed as `POST`, we only ask for a `GET` 
permission as the application objective is to actually read data.

Require GET permission for index copy

---

docs/settings.md
model/instance/lifecycle/passphrase.go
web/apps/apps_test.go
web/settings/passphrase.go
web/settings/settings_test.go

On instances with authentication via OIDC, it is now possible to force a
password to allow the setup of Cozy Pass.

Allow to force setting password for Cozy Pass

---

web/data/data.go

Just like https://github.com/cozy/cozy-stack/pull/2939, an app might automatically delete indexes when [querying data](https://github.com/cozy/cozy-client/pull/907)

Require GET permission for index deletion

---

docs/settings.md
model/instance/lifecycle/passphrase.go
web/apps/apps_test.go
web/settings/passphrase.go

Otherwise, key was not replaced in the bitwarden settings document and then
the vault was unusable

fix: Pass encrypt key when force updating passphrase

---

pkg/couchdb/index.go
web/data/data.go
web/data/data_test.go

The stack needs a few CouchDB design docs for its own indexes and views.
The front applications will no longer be able to delete them with the
DELETE /data/:doctype/_design/:ddoc route.

Forbid the deletion of stack indexes/views

---

model/intent/intents.go

When no installed app can be used to answer an intent request, the stack
makes requests to the apps registry to look if other available
applications could do the job. Those requests were overwritting the path
without taking in account the different spaces of apps registy. This
commit fixes this issue by appending to the app registry path.

Fix the available apps for intents

---

model/note/note.go
tests/integration/lib/cozy_file.rb

The filename of a note is generated from its title. We should avoid some
characters like ? to ensure that the filename is compatible with the
windows and macOS file systems, so that the file can be synchronized
with the desktop client safely.

Improve the filenames for notes

---

assets/locales/en.po
assets/locales/fr.po

The message was abput checking the URL and the padlock before filling
the password. We remove the part about the padlock because there are
some contexts where the user is expected to give their password even if
the padlock is not here (webviews on android for example). And the
sentence was modified to emphasize it is a general tip for every time
the password must be given, not only for this time.

Update the wording for the banner

---

docs/jobs.md
model/job/broker.go
model/job/mem_broker.go
model/job/rate_limiting.go
model/job/redis_broker.go
model/job/redis_scheduler.go
model/job/scheduler.go
model/job/trigger_client.go
model/job/worker.go
pkg/limits/rate_limiting.go
web/jobs/jobs.go
web/jobs/jobs_test.go

For running konnectors on mobile client, we want to keep a trace of the executions via the triggers and jobs. So, we are adding a new type of trigger, `@client`, and a new worker type for jobs, `client`.

Add a new type of trigger and jobs worker: client

---

cozy.example.yaml

I had an hard time to understand that the first word was the slug of the app. I first though that it has to be a specified route of the Home application

docs: Update onboarded_redirection doc

---

pkg/couchdb/couchdb.go
pkg/couchdb/encoding.go

When the stack send a request to CouchDB for a view with the keys
parameter, it is sent as a POST with the keys in the body. So, we should
not put the keys in the query-string, as it defeats the purpose of using
a POST in the first place (avoiding too long URLs).

Fix view requests to CouchDB with keys

---

model/sharing/shared.go
model/sharing/sharing.go

When a user puts a shared directory to the trash, the sharing is
revoked. We have seen a case where the revocation failed, which is bad,
and it blocks the user from accepting the sharing again, which is worse.
So, let's make the revocation process more robust, by trying harder to
manage errors and adds a retry loop for removing the shared references.

Make the sharing revocation more robust

---

web/middlewares/secure.go

Google’s Federated Learning of Cohorts is a new initiative to track
internet users without their consent. This feature is already enabled by
default for a small percentage of Google Chrome users, and is intended
to be enabled for all users at the end of the experiment. We don't want
of it, so let's add an HTTP header to disable it on Cozy.
See https://plausible.io/blog/google-floc#how-to-opt-out-of-floc-as-a-web-developer-set-a-permissions-policy

Opt-out of FLoC

---

model/account/accounts.go
model/instance/lifecycle/destroy.go
web/apps/apps.go

When a konnector is uninstalled, the stack cleans the accounts. To do
that, it looks at the triggers, and when we had several triggers for the
same accounts (e.g. cron + webhook), it was trying to delete the
accounts several times, which failed. Now, the cleaning entries will
regroup the triggers with the same account to avoid this issue.

Fix cleaning on uninstall konnectors

---

model/sharing/oauth.go
model/sharing/rule_test.go
web/sharings/sharings.go
web/sharings/sharings_test.go

When a user wants to accept a sharing, they must give the URL of their
Cozy. There are a few mistakes that can happen easily on this step, and
we want to fix them for the user. For example, the URL can have been
copied-pasted from address bar of the browser, and it contains the app
slug in that case (https://john-drive.mycozy.cloud/ instead of
https://john.mycozy.cloud/). This mistake was already identified and the
stack was fixing the URL for creating the OAuth client, but the fix was
in too low-level code, and the incorrect URL was used later for the
redirection. This commit moves this code to a better place and fix the
issue on redirection.

Fix cleaning app slug in Cozy URL for sharings

---

docs/bitwarden.md
pkg/assets/dynamic/dynamic.go
web/bitwarden/bitwarden.go
web/bitwarden/bitwarden_test.go
web/bitwarden/ciphers.go

This PR adds 3 routes to handle bitwarden ciphers in bulk:
1. for soft-deletion
2. for restoration
3. for permanent deletion.

Add routes for bulk handling of bitwarden ciphers

---

model/vfs/vfsafero/impl.go
model/vfs/vfsswift/impl_v1.go
model/vfs/vfsswift/impl_v2.go
model/vfs/vfsswift/impl_v3.go

When files are synchronized via a sharing, the stack use a sharing
indexer to override some behaviors from the classical VFS, like forcing
the revisions to put in CouchDB. And in order to do that, we were using
the UseSharingIndexer method of the VFS that was bugged: the prefix
field was not copied. In most cases, this field wasn't used, but it made
some requests for checking old versions of a file to fail.
In practice, it means that a shared file can have several versions
written in a close time gap, ingoring the mininal delay between versions
from the configuration.

Fix some issues with sharing + VFS versioning

---

web/data/replication.go

This will be useful for PouchDB replication, typically to get the last sequence number, if it wants to replicate from it

Add descending parameter for changes

---

client/apps.go
cmd/apps.go
cmd/root.go
docs/admin.md
model/app/maintenance.go
pkg/consts/doctype.go
web/apps/maintenance.go
web/registry/registry.go
web/routing.go
worker/exec/konnector.go

With this PR, it will now be possible to put a konnector for only one environment (aka a stack). Before, it was only possible to do that by updating the konnector on the apps registry, which impacts all the environments.
We have 2 CLI commands to manipulate this: `cozy-stack konnectors maintenance` and `cozy-stack konnectors deactivate-maintenance`. And we have modified two routes to use this information: `GET /registry/maintenance` and `GET /registry/:app`.

Allow to put in maintenance a konnector on an environment

---

pkg/previewfs/cache.go

previewfs stores PDF preview files to avoid regenerating it each time.
Previews are stored in afero fs or in swift.
When using swift, if previewfs container doesn't exist, the stack should [create it](https://github.com/cozy/cozy-stack/blob/master/pkg/previewfs/cache.go#L86-L87).
Unfortunately, this doesn't work currently because we test for error `swift.ContainerNotFound` but `ObjectCreate()` errors are mapped against `objectErrorMap`  (see [here](https://github.com/ncw/swift/blob/master/swift.go#L1496)) and 404 status code is then interpreted as `ObjectNotFound`
So previewfs container is never created.
This PR fixes that behaviour by comparing error to `ObjectNotFound` instead of `ContainerNotFound`

Fix swift previewfs

---

pkg/previewfs/cache.go

When the swift container for previewfs is missing, the error happens on
the write operation, not on ObjectCreate. So, the stack was checking too
soon if saving a file to previewfs was failing because the container was
missing.

Fix creation of previewfs swift container

---

web/notes/notes.go
web/office/office.go

When a directory is shared with a link in read+write mode, and an office
document is opened from this link, the stack must use the edit mode of
OnlyOffice. It was forced to view (read-only) before this commit for all
documents opened from a sharing link.

Fix opening an office document from a link

---

web/apps/apps.go

When a client asks for the icon of an app that is not installed via the
GET /apps/:slug/icon route, we were sending a 500 Internal Server Error.
This is fixed by sending the expected 404 Not Found.

Send a 404 for icon of a not installed app

---

model/move/request.go
model/oauth/access_code.go
model/oauth/client.go
model/sharing/oauth.go
tests/testutils/test_utils.go
web/bitwarden/bitwarden.go
web/instances/client.go

Some OAuth clients were used by sharings but their pending flag was not
removed, and after 1h, their clean-client trigger deletes them. Now, we
avoid setting the pending flag in first place when we know that a token
will be generated just after the client creation, which avoids this
issue.

Fix the deletion of unused OAuth clients

---

pkg/couchdb/couchdb.go

When a database was manually deleted in CouchDB, we will recreate the
indexes when the database is recreated.

Recreate indexes when creating database

---

model/vfs/directory.go
tests/integration/lib/stack.rb
tests/integration/tests/selective_sync.rb

The format of the changes feed is a bit weird. The results are an array
of object which can have `deleted`, `id`, and `changes` with `rev` inside. It
can also have a `doc` object, but the `doc` object have `_deleted`, `_id`, and
`_rev` (prefixed with an underscore). We have added the missing underscore
for `_id` and `_rev` inside `doc`.

Fix changes feed with selective synchronization

---

web/auth/auth.go

A user can be logged-in on a not onboarded instance when both the
password and the OIDC can be used to log in (login via OIDC but no
password has been chosen). In this case, the home should display the
need_onboarding page.

Fix the home when logged-in but not onboarded

---

model/app/webapp.go

When an application is installed, the CouchDB Document is created before
the triggers for its services. But, we should also update the document
after to keep track of the trigger_id.

Fix missing trigger_id for services of new apps

---

model/vfs/couchdb_indexer.go

If we have a VFS inconsistency on a file, we may get an error when
trying to trash its parent, and the other files inside this directory
won't have their trashed attribute updated. I don't really see how it
can triggered, but it sounds safer to do that.

Fix trashing a directory with many files

---

model/oauth/client.go
web/auth/register.go

In order to improve security, we don't want to allow OAuth clients to
link with store and settings. They are apps with special privileges, and
we don't want untrusted code to use those permissions.

Restrict OAuth clients

---

cmd/instances.go

The example given to create an instance did not include the home and store apps. 
The default redirection is `home.cozy.localhost:8080` so it particularly makes
sense to include it.

Add home and store in instance creation example

---

model/session/login_history.go
model/session/session.go
web/auth/oauth.go
web/bitwarden/bitwarden.go
web/instances/client.go

#3105 Added audit traces for sessions. 
This PR:
- group them in a new dedicated `loginaudit` nspace
- add log messages for successful session deletion and expiration

Group session audit messages in a dedicated nspace

---

docs/sharing.md
model/sharing/member.go
model/sharing/sharing.go
tests/integration/tests/bitwarden_cli.rb
web/settings/passphrase.go
web/sharings/sharings.go

When an instance is in a context with delegated authentication, its owner may have no password when they accept the sharing. In that case, the password will be created a bit later in cozy pass web. And when it's done, the stack is now sending the public key to the sharing owner instance to make it work.

Make passwords sharing possible with delegated auth

---

client/apps.go
model/app/apps.go
model/app/apps_test.go
model/app/installer.go
model/app/installer_webapp_test.go
model/app/konnector.go
model/app/webapp.go
model/instance/instance_test.go
model/instance/lifecycle/destroy.go
model/intent/intents.go
model/intent/intents_test.go
model/move/importer.go
model/notification/center/notification_center.go
web/apps/apps.go
web/apps/apps_test.go
web/apps/serve.go
web/auth/auth_test.go
web/auth/oauth.go
web/instances/fixers.go
web/instances/instances.go
web/intents/intents_test.go
web/sharings/sharings_test.go
worker/exec/konnector.go
worker/exec/service.go
worker/migrations/migrate-accounts-to-organisation.go

The apps registry allow developers to add custom fields to the manifest of applications. But, it worked only if the fields were defined in the stack: the stack was doing unserialize to a Go struct + reserialize to JSON, and unmapped fields were lost in the process. This PR fixes this issue but unserializing twice the JSON: one time to a Go struct, and one time to a `map`. The Go struct is used for simple manipulation in Go code. The `map` is used for serialization to JSON (and is updated with the changes from the Go struct).
Fix #3103

Remove explicit mapping for app manifests

---

docs/sharing-design.md
model/sharing/files.go
model/sharing/oauth.go
model/sharing/replicator.go
model/sharing/shared.go
tests/integration/lib/sharing.rb
tests/integration/tests/bitwarden_cli.rb
tests/integration/tests/sharing_referenced_by.rb
tests/integration/tests/sharing_sync.rb
web/sharings/sharings_test.go

1. Alice has shared a bitwarden organization + ciphers to Bob
2. Bob has accepted this sharing
3. later, Alice has revoked Bob from the sharing
4. later later, Alice shares again this organization with Bob
5. and Bob accepts
With this scenario, the ciphers in the organization weren't synchronized
on Bob's Cozy. It is due to how the CouchDB replication works. For
example, if a cipher was in revision 3-aaa when Alice has shared it to
Bob the first time, a document was created on Bob's instance with this
revision. Later, when the sharing was revoked, this document was
deleted, and CouchDB will do that by creating a revision 4-bbb. On the
second sharing, the same document is sent with revision 3-aaa. CouchDB
will accept the document with this revision, but the revision 4-bbb is
still seen as …

Fix resharing ciphers with the same member

---

model/sharing/replicator.go
tests/integration/lib/bitwarden/organization.rb
tests/integration/lib/rule.rb
tests/integration/tests/bitwarden_cli.rb

When a sharing rule has the revoke action, and a document that matches
this rule is removed from the sharing, the stack must revoke the
sharing. It is now done by the share-replicate worker.

Fix revoke action for a sharing rule

---

web/bitwarden/contact.go

When a user has shared several bitwarden organizations with another
member, the sharings can be in different states for this member:
pending, ready, revoked, etc. For revoking a bitwarden contact, we
should revoke only the sharing with the ready state.
For revoked state, it is already revoked, so no need to do something
more. For pending, we want to let the member the possibility to accept
the sharing and use a new key (so, new fingerprint).

Fix refusing a bitwarden contact

---

model/sharing/rule.go
model/sharing/rule_test.go
model/sharing/shared.go
tests/integration/lib/bitwarden/cipher.rb
tests/integration/tests/bitwarden_cli.rb

When a cipher is in a shared organization, and is moved to another
organization, the local stack sees an update, but the sharing
replication protocol must delete the cipher for the recipients. It is
done by marking the io.cozy.shared as removed in the share-track worker.
This clue is later interpreted by the worker-replicate that can send the
cipher document as deleted in the replication.

Fix removing a cipher from a shared organization

---

docs/data-system.md
web/data/data.go
web/data/data_test.go

This might be useful to quickly destroy all database documents,
typically for running tests or performances measures.

Add a route to delete database

---

web/apps/apps.go

When a konnector is uninstalled, the stack looks at the accounts used by
this konnector, deletes them if the konnector has a on_delete property
in its manifest, and deletes the associated triggers. When there are
several triggers for the same account, only the last one was deleted
because of a bug where the assigned value was lost. This commit fixes
this issue (and I'm surprized that the linter didn't noticed that).

Fix trigger deletion on konnector uninstall

---

model/instance/lifecycle/destroy.go

When an account still exists but its konnector is missing, the instance
deletion fails (because we can't look at the on_delete field when the
konnector is not installed). We are now trying to reinstall the
konnector in that case, which should help to limit the number of
problematic cases.

Fix instance deletion with a stale account

---

docs/admin.md
model/instance/lifecycle/create.go
model/instance/lifecycle/patch.go
web/instances/instances.go

It allows to avoid calling the cloudery when the email or public name is
changed and the change is coming from the cloudery.

Add a FromCloudery flag for PATCH /instances/:domain

---

model/vfs/directory.go
model/vfs/file.go
web/files/files.go
web/files/files_test.go
web/files/paginated.go

I was not very pleased by #3149, as it makes changes on a lot of files, and looks like it can easily introduce a regression. Here, I'm making another proposition, with changes more focused in `web/files`.

Allow to filter fields for mango queries on files

---

web/routing.go

- remove piwik.cozycloud.cc (no longer used)
- add errors.cozycloud.cc (will replace sentry.cozycloud.cc in the coming months)
- add api.pwnedpasswords.com (used by cozy-pass-web)

Update the CSP list

---

web/bitwarden/organization.go

When several sharings are made between Alice and Bob, Bob can have
accepted one but not the others. In that case, if Alice confirms
the Bob's identity for the sharing of a bitwarden organization,
cozy-pass-web will also send a confirmation for the other sharings
of bitwarden organizations. For those sharings, Bob can still be
in the invited status, and this commit allow the confirmation to
work in that case.

Allow to confirm an invited member

---

model/vfs/vfsswift/impl_v3.go

When using vfsswift, if a file is uploaded to a directory and while the
transfer, the directory is put in the trash, the file wasn't created
with the trashed attribute.

Fix a case of trashed-not-in-trash with vfsswift

---

web/middlewares/permissions.go
web/permissions/permissions.go
web/permissions/permissions_test.go
web/settings/clients.go

When a Bearer token is invalid (expired for example), the stack will now
send a WWW-Authenticate header in the response.
See https://datatracker.ietf.org/doc/html/rfc6750#section-3

Add a WWW-Authenticate header for invalid token

---

cozy.example.yaml
docs/workers.md
model/job/mem_scheduler.go
model/job/redis_scheduler.go
model/job/scheduler.go
model/note/note.go
pkg/config/config/config.go
pkg/couchdb/index.go
web/files/files.go
worker/trash/trash.go

A new worker has been added to delete files and directories that have been trashed after a configurable delay. It is called via a `@cron` trigger that is created by the stack when a file or directory is put in the trash and the configurable delay has been configured for this instance context.

Add a way to automatically clean old trashed files and directories

---

docs/workers.md

This is useful when creating a job, to know which arguments should be
defined, for konnector and service workers.

Add doc about worker execution

---

model/app/installer.go
web/apps/apps.go

When installing or updating an app with Server-Sent Events, the client
can reach a timeout as nothing was sent for 1 minute or more if the code
wasn't in the cache. The stack is now sending a blank line every 10
seconds to avoid it.

Send blank lines on SSE every 10 seconds

---

scripts/build.sh

Improve `build.sh` script to allow passing generated binary target when building a release
Allow for `scripts/build.sh release /path/to/binary/target`
This will be usefull when user building binary does not have write permission on repo clone or if the user simply wants to build the binary directly in his final target path.

Allow to specify release build target

---

cmd/instances.go

When creating a cozy instance, cozy-stack cli provide the registration token.
This PR adds the complete registration URL to the output to ease manual registration.

Show registration URL on cozy creation

---

web/statik/handler.go

We want to mutualize the HTTP cache between the apps, and each web app
has its own HTTP origin.

Remove the Vary: Origin HTTP header for assets

---

model/sharing/open_file.go

When a sharing member has been invited with several email addresses, and
has accepted and revoked the sharing from one email addresse, and later
accepted the sharing from another email address, their instance will be
listed twice in the sharing (with the status revoked and ready). If this
member creates an office document, and someone else in the sharing tries
to open it, it may fail as the sharing status may have been seen as
revoked (it depends of the order of sharing members). We are now
ignoring the not-ready members to avoid this issue.

Fix opening shared office documents

---

model/sharing/member.go
model/sharing/open_file.go
model/sharing/sharing.go

When Alice shares a directory with Bob, and only the instance URL of Bob
is known (not his email address), a note inside this directory could
not be opened by Bob.

Fix opening shared note

---

cmd/serve.go

Previous used digest was from CozyPass app
Now the Flagship app has its own new certificate

Fix certificate digest for Android flagship certification

---

docs/apps.md

This new attribute has been added in order to know how to open native apps from React Native
See related PR:
- https://github.com/cozy/cozy-pass-web/pull/78
- https://github.com/cozy/cozy-react-native/pull/65
- https://github.com/cozy/cozy-home/pull/1680
- https://github.com/cozy/cozy-ui/pull/2015
- https://github.com/cozy/cozy-apps-registry/pull/282

Add documentation about the new manifest's mobile attribute

---

model/app/installer.go
model/permission/set.go
model/permission/set_test.go

The stack can auto-update konnectors if only a permission of carbon copy
or electronic safe is added, without asking permission from the user.

Allow auto-update for carbon copy permission added

---

worker/exec/konnector.go

When a konnector is executed, the stack ensure it has a folder where it
can be put its files if needed. The path for this folder is taken from
the account, but if it is missing, a fallback will use the konnector and
account data. It was using the slug of the konnector, and it will now be
using the konnector name instead.

Fix the folder path for recreating a konnector folder

---

model/sharing/member.go
model/sharing/sharing.go

If a recipient revokes a sharing, and an error occur while removing the
references, the sharing was marked as active with a revoked owner, which
is a state that can cause panics in the stack. We can avoid this issue
by removing the active flag sooner on the sharing.

Fix revoke sharing by a recipient

---

pkg/jsonapi/jsonapi.go

The JSON-API responses are accessed from several origins (the apps)
and, as such, are bound to CORS by the browsers. A CORS preflight
(OPTIONS) is made, but the main request (GET/POST/etc.) must also
have a response with the Access-Control-Allow-Origin header set.
And the server must tell the browser to not cache this response for a
request from one origin, and reuse this cached response for a request
from another origin (or the browser will throw a CORS error). This is
done with the Vary: Origin HTTP header. In theory, it was done via the
CORS middleware, but a mistake in the Content-Encoding negociation was
reseting it.
In practice, most browsers already split their cache per origin for
privacy reasons. And the bug was only visible in the chromium family
when using the back button of …

Fix HTTP caching of JSON-API responses

---

worker/exec/konnector.go

- Log `account_id` on konnector ignore
- Stop logging `job_id` as this message clearly means we are not going to start a job and it is always empty

Improve konnector ignore logging

---

web/apps/apps.go

The stack sends some comments in Server-Side Events response to avoid
letting the connection timeouts. But they were buffered, which defeats
the purpose. We are now flushing them to fix this issue.

Flush SSE response

---

model/office/callback.go

When a file is opened in OnlyOffice, and the callback endpoint creates a
conflict, the next callback for saving the same file should avoid
creating more conflict files and should instead save the new changes to
the conflict file.

Fix conflict handling for OO files

---

web/middlewares/user_agent.go
web/middlewares/user_agent_test.go

We are using unicode property escape for regexp in JS, so we need
browsers that support them. We have increase the required versions of
chrome, chromium, edge, and firefox to the minimal version that has this
support.

Increase minimal required versions of browsers

---

web/auth/oauth.go
web/middlewares/permissions.go

`Flagship.Contexts` uses `default` key to store default configuration
`instance.ContextName` returns empty string if no context is set for
the cozy instance
So when instance has no context we should force `default` key instead
of empty string when accessing `Flagship.Contexts`

Fix skipping flagship validation via config when using default context

---

web/settings/capabilities.go

We were returning the same error message for all
the possible errors.
Now we return the specific error.
We find out this issue when requesting this route
with an expired OAuth Token. And since the only
message we had was "Forbidden", the refresh process
was not launched.
Thought, we had the right message in the WWW-Authenticate
header.

fix: Return the real error for /capabilities/settings

---

docs/toc.yml

To easily find konnectors documentation on docs.cozy.io website, use correct `/konnectors` endpoitn prefix for konnectors documentation.

Prefix konnectors doc in toc with correct endpoint prefix

---

docs/data-system.md

Let's make it explicit that _all_docs is not the way to 
go to fetch the full list of documents since it can be 
subject to performance issue on large dataset.
I know that some use cases are legitimate to make 
a request on _all_docs. With this edit, I try to warn 
that you can do that only if you know that the dataset 
is not pretty large.

doc: Attempt to warn about the use of _all_docs

---

web/middlewares/secure.go
web/routing.go

This reverts commit 2f03e7e12b21813185fa1395948d0ac1d2ee0b29.
Piwik.cozycloud.cc should no longer be used, but it was not yet the case
when it has been removed from the CSP. so we have added it again to give
time for clients to finish the migration. But, let's try again to remove
it!

Revert "Add again piwik.cozycloud.cc in CSP (temporary)"

---

model/app/konnector.go
model/app/webapp.go

When a webapp or konnector is installed/updated/removed, and we have
several websockets listening to changes for io.cozy.webapps or
io.cozy.konnectors, the stack try to serialize to JSON the same manifest
several times concurrently. Golang doesn't like that a map is read and
written concurrently and can crash. The fix is to clone the map to have
one map per serialization.

Fix JSON serialization of app manifests

---

web/accounts/oauth.go

The BI reconnect flow is similar to the OAuth flow for konnectors: it is
meant to be triggered via a browser opening a tab, not via a fetch/xhr
request. As such, there is no token for checking permissions, but we can
rely on the session to ensure the security.

Fix the BI reconnect flow

---

web/apps/apps.go

When someone is using only the flagship app, we still need a way to keep
the webapps up-to-date. When the flagship app opens a webapp, it makes 3
calls to the stack:
- GET /apps/:slug/open
- GET /apps/:slug
- GET /apps/:slug/download
It seems that updating the app (if a new version is available without
needing a consent from the user) on the second call, GET /apps/:slug,
is the best choice as this call in made in background.

Update the app when calling /apps/:slug

---

model/instance/lifecycle/create.go
model/instance/lifecycle/reset.go
tests/integration/tests/accounts-to-ciphers.rb

The stack should create the CouchDB databases for a new instance before
registering a fake password for OIDC instance, as registering the
password also try to create a settings document for bitwarden.

Fix instance creation with OIDC

---

docs/couchdb-quirks.md
pkg/couchdb/couchdb.go
pkg/jsonapi/data.go
pkg/jsonapi/jsonapi.go
web/data/data.go
web/files/files.go
web/files/paginated.go

With CouchDB 3+, when an index can be used for a _find request, but
CouchDB still need to look to many documents that will not appear in
the response, a warning is emitted. This warning is now forwarded by the
stack to the client. The warning for no index at all is still
transformed to an error by the stack.

Forward warning for unoptimal index

---

web/routing.go

Loading images from mapbox was authorized in the CSP, but this is not
used, and I don't like having exceptions in the CSP. So, let's remove
it.

Remove the exception for mapbox in the CSP

---

web/routing.go
web/statik/handler.go

API endpoints like /files/download must have a strict Content Security
Policy to avoid using them as an HTML page or JS script. Their origin
is the main domain of a Cozy, and as such, they can read responses to
xhr/fetch to /auth/ endpoints.

Fix security issues with CSP

---

client/files.go
cmd/fix.go
model/vfs/file.go
model/vfs/vfs.go

The PATCH method for io.cozy.files allowed to update the md5sum. It was
introduced for fixing missing md5sums. It looks like this endpoint has
been misused by some clients and can create FS errors (content
mismatch). So, let's remove this possibility and the fix command that is
no longer used.

Forbid patching md5sum by clients

---

model/sharing/files.go

When the folder where the sharings are received has been trashed, the
stack should not create the no longer shared directory inside it, but
should create it outside of the trash.

Avoid creating the no longer shared dir in trash

---

web/accounts/oauth.go

For Google and BI webviews, an OAuth danse is made, and if the user
clicks to cancel it, they are redirected to the stack. We want to go
back to the app where they started the OAuth danse, not to an hard-coded
slug (store), because the store app may be not available and it makes
harder to have a coherent User Experience.

Fix redirect when cancelling OAuth for a konnector

---

model/vfs/vfsswift/fsck_v3.go

When using the VFS Swift, the images inside notes where seen as
thumbnail_with_no_file when the cozy-stack check fs was executed. It was
due to a bug in handling `-` in their name when removing the -format
suffix.

Fix check fs command for note images

---

model/sharing/files.go

When the stack changes the name of a directory to add a suffix like (2),
it also needs to update the fullpath of this directory to avoid VFS
inconsistencies. It wasn't done for some rare operations in the sharing
package.

Fix fullpath for directories on some sharings ops

---

docs/konnectors-workflow.md
tests/integration/konnector/index.js
tests/integration/tests/trigger_webhook.rb
worker/exec/common.go
worker/exec/konnector.go
worker/exec/service.go

The payload from webhooks was read from the COZY_PAYLOAD env variable by
the konnector or service. But, env variables have a size limit (defined
by the linux kernel), which makes impossible to use large payload. Now,
when the stack sees a big payload, it will write it to a temporary file
and will just put @ + the filename of this file in COZY_PAYLOAD.

Allow to use big payload for webhook triggers

---

model/session/login_history.go

It doesn't make sense for the user to receive a mail when they are using
their Cozy for the first time. It was already the case for most users,
but we are fixing that for users with OIDC flow.

Don't send a notification for the first time

---

model/app/konnector.go

When a trigger is created for a konnectors via the stack endpoint POST /jobs/:slug/trigger, the stack tries to mimick the behavior of harvest. In particular, it needs to to fill if the folder_to_save field of the trigger if the konnector manipulates files. Harvest looks at the manifest of the konnector for the fields.advanced_fields.folderPath (and the stack was doing it too) and folders (which wasn't done by the stack before this commit).

Fix trigger creation for konnectors (folder_to_save)

---

pkg/couchdb/proxy.go

The /data API allows to make requests to CouchDB, and the stack only proxify the request and check the permission. In thoses cases, it is better to drop the Host header.

Drop the Host header when proxy request to CouchDB

---

model/notification/huawei/client.go
worker/push/push.go

When sending a push notification to APNS/FCM/Huawei, the error response can be interpreted to know if the mobile app has been uninstalled. If it happens, the stack will remove its associated OAuth client. The error codes are different per platform, but the logic is the same.

Remove unregistred clients after error on push

---

model/vfs/version.go
model/vfs/version_test.go
model/vfs/vfsafero/impl.go
model/vfs/vfsswift/impl_v3.go

When there are 2 concurrent uploads for the same file, we may have a race condition on the candidate version. The candidate will twice be the same version, and we need to avoid keeping it for one upload and cleaning it for the other, as it creates a FS inconsistencies: the version will exist in CouchDB but not in Swift.

Fix race condition on concurrent uploads

---

model/sharing/files.go

When a user has a "Shared with me" directory without the expected id, the stack should still use this directory for new sharing (instead of failing).

Fix accepting sharing with shared with me dir

---

model/app/installer_webapp_test.go
model/app/webapp.go

When a webapp is updated, and its manifest contains services, it can happen that a new trigger is created but the old one is not removed. It was the case, for example, when the type of the trigger is changed (@every -> @monthly).

Fix orphan triggers on app updates

---

assets/locales/en.po
assets/locales/fr.po
assets/styles/cirrus.css

We have many remote-doctypes for the DACC (unfortunately), but only one had the correct locales and icon

Add icon and locales for all DACC remote doctypes

---

model/vfs/vfsswift/impl_v3.go

When files with thumbnails are shared, and someone move them outside of the shared  folder, a copy of those files is put in the trash for the other members of the sharing. This operation is called dissociating files, but it didn't removed the thumbnails of the old files because of an error "nil Context". This is now fixed by setting the context on the thumbsV2 object.

Fix cleaning thumbnails while dissociating files

---

model/vfs/vfsafero/impl.go
model/vfs/vfsswift/impl_v3.go

When a new version of a file is uploaded, but the content is the same, the stack can avoid creating a new version. Some konnectors are known for importing files without checking if the file has really changed, and it creates lots of versions with the same content.

Avoid creating useless versions for files

---

docs/bitwarden.md
web/bitwarden/bitwarden.go
web/bitwarden/bitwarden_test.go

This route can now tell if the login via OIDC is mandatory and when the vault is empty. When both conditions are true, the onboarding process for the mobile apps and browser extensions is a bit different.

Improve the bitwarden prelogin route

---

docs/remote.md

Try to make clearer about the fact that `token` is stored in  the secret database, but need to use `secret_token`  for the remote doctype declaration.

docs: Try to make clearer the secret in remote doctype

---

docs/konnectors-workflow.md
model/account/type.go
web/accounts/oauth.go
web/accounts/statestore.go

This webview let's users manage their bank connections. We need a
route to compute its URL and  allow Cozy frontend apps (e.g. Harvest)
to open the appropriate webview for the user.

feat: Add a route to access the BI manage webview

---

model/sharing/shared.go
tests/integration/tests/sharing_conflicts.rb
tests/integration/tests/sharing_sync.rb

When a single file is shared, if this file is moved to a new directory, the share-track worker was failing because of the isNoLongerShared function. We were trying to load the file as a directory, which triggered a "file not found" error.

Fix the isNoLongerShared function

---

model/vfs/couchdb_indexer.go

Removing a shortcut for a sharing should never revoke the sharing, so let's add a protection against that. We have seen a case in production where this protection would have been useful.

Add a protection when revoking a sharing

---

go.mod
go.sum
pkg/couchdb/bulk.go
pkg/couchdb/stream/all_docs.go
pkg/couchdb/stream/all_docs_test.go
web/data/data.go
web/data/data_test.go

When requesting all_docs for a lot of io.cozy.files with Fields, the response can be quite slow (a few seconds). Part of that is CouchDB and transfering the bytes, and we can't do anything about that, but there is also another part that is deserializing JSON, keeping only the required fields, and reserializing to JSON. And it looks like this part is taking way much longer that we would have expected.
In this commit, we are trying to make things faster by replacing the full JSON parser by just a tokenizer (and doing some low-level stuff). I have added unit tests, but the code is tricky, so I'm less confident than usual on the risk of a regression. And we need to deploy on servers to really see the performance boost (or lack of).

Make the all_docs endpoint with Fields faster

---

worker/exec/cmd_unix.go
worker/exec/konnector_test.go

The current working directory for a konnector should be the directory where its script is running (and not keeping the cwd of the stack). It would make easier to find the payload.json from a konnector when needed.

Fix cwd for konnectors

---

docs/cli/cozy-stack_instances_add.md

1. respect the order `<domain>` and then `[flags]` in the exemples.
2. rename the created instances with a less ambiguous name than "cozy" wich make difficult to understand what is what.
note : if somewhere in the documentation there are explanations about the notion of "domain" and "slug", a link to this documentation could be added in this page.

small documentation modifications

---

docs/auth.md
docs/flagship.md
tests/testutils/test_utils.go
web/apps/apps_test.go
web/auth/auth.go
web/auth/auth_test.go
web/auth/oauth.go

The flagship app should be able to retrieve tokens for client-side
konnectors so it can run them with their own token instead of the
flagship token.
Using specific konnector tokens means separate permission sets and an
accurate client name for konnector requests to cozy-stack.

feat: Add client-side konnector tokens build route

---

docs/konnectors.md
web/apps/apps.go
web/apps/apps_test.go

While we could already download the latest version of a konnector from
the flagship app, we could not download a specific version.
This feature existed for apps already so we just add the route for
konnectors.
This requires the `GET io.cozy.konnectors` permission.

feat: Add route to download a konnector version

---

web/files/files_test.go
web/files/paginated.go

When using the POST /files/_find endpoint, a JSONAPI response is returned. It must include the referenced_by relationships. It was the case for files, but not for directories.

Fix referenced_by in POST /files/_find

---

model/sharing/upload.go

When uploading a file for a sharing, it may happen that the io.cozy.shared document is corrupted (bad chain of revisions), and the upload fails with an Internal Server Error. In that case, it is useless to retry, as it will fail again, but it is better to skip this file to allow uploading the next files sooner.

Do not retry upload on Internal Server Error

---

model/sharing/shared.go

When updating an io.cozy.shared from an event with no previous revision, we should check if the current revision exists in the io.cozy.shared document to avoid putting it twice.

Mitigate bugs when updating an io.cozy.shared

---

worker/exec/konnector.go

When preparing workdir for konnector run, avoid downloading useless files to lower pressure on underlying storage backend during high konnector execution rate.
Also avoid looking for older konnector storage `app.tar` because these are non-existent in the vast majority of cases. Simply assume there is no `app.tar`, start copying all files, and extract `app.tar` on-the-fly if we encounter one. Side effect is we now copy other files that reside alongside `app.tar` which should not be a problem because the only case where this can happen is in a specially crafted konnector with an `app.tar` file alongside other files and AFAIK there is currently no such konnector.

Avoid unnecessary storage backend access when preparing konnector run

---

docs/README.md
docs/connection-check.md
docs/toc.yml
web/conncheck/conncheck.go
web/routing.go

This PR adds a public unauthenticated connectivity check route `/connection_check` that respond with HTTP 204 No Content for the flagship application to check for connectivity

Add connectivity check route

---

model/app/webapp.go

Using fields other than "name" in the locales of the manifest was lost by the stack when deserializing/serializing JSON.

Fix locales for webapps

---

model/sharing/sharing.go

When a sharing is created for a directory, the stack should add a reference to the new sharing on the directory. It was done when a recipient accepts the sharing, but it could be too late if the directory was trashed before that: the sharing should have been revoked.

Add reference to the sharing directory

---

model/sharing/revisions.go
model/sharing/revisions_test.go

When an io.cozy.file is created and modified just after, it may happen that the share-track job for the update is processed before the job for the creation. When this happens, the revs tree for the io.cozy.shared wasn't correct: the revision 2 was coming before the revision 1. This commit adds a check to put the revisions in the good order for this case.

Fix share-track jobs when they are not in expected order

---

go.mod
go.sum
model/app/apps.go
model/app/fetcher_git.go
model/app/installer_konnector_test.go
model/app/installer_test.go
model/app/installer_webapp_test.go
model/app/webapp.go
model/instance/instance.go
model/move/archiver.go
model/vfs/vfsafero/fsck.go
model/vfs/vfsafero/impl.go
model/vfs/vfsafero/thumbs.go
pkg/appfs/copier.go
pkg/appfs/server.go
pkg/assets/dynamic/fs.go
pkg/previewfs/cache.go
worker/exec/common.go
worker/exec/konnector.go
worker/exec/konnector_test.go
worker/exec/service.go
worker/mails/exec.go

Our fork was used via a `replace` directive in the `go.mod` file but
this prevents the use of `go install` which replaces `go get` in Go
1.18.
We simply replace the import of `spf13/afero` with our own in `go.mod`
and all the files importing it.

chore: Directly import our fork of spf13/afero

---

model/permission/permissions.go
model/sharing/open_file.go
model/sharing/sharing.go
web/apps/serve.go

When a user goes to the preview URL for a Cozy to Cozy sharing, and if their Cozy URL is known (ie they have accepted a sharing), then we should allow this user to interact with the sharing. For a note, it means that they will be allowed to edit it. For a folder, they can upload new files.
Note: we also need to update the webapps to use the interact token.

Use interact token for preview URL of sharing

---

assets/templates/passphrase_reset.html
docs/auth.md
web/auth/passphrase.go

When the passphrase reset page is opened from a mobile native
application into the phone's browser, we don't want users to click on
the provided back button as it would not redirect them to the native
application but the login page inside the browser and this would be
confusing.
We add a `hideBackButton` query-string parameter that native
applications can set to `true` so we know not to display the back
button on the passphrase reset page.

feat: Allow hiding back button on passphrase reset

---

docs/registry.md

It was not clear when reading the line that konnectors are also concerned by this route. I understand that from the point of view of the registry apps and konnectors are the same, but this is not the case when querying from the stack (io.cozy.apps vs io.cozy.konnectors)

docs: Add konnectors to the /registry/maintenance route

---

pkg/config/config/swift.go

Fix swift auth URL hardcoded path and allow to specify an http auth url as additional parameter even with a `swift+https` scheme

Fix swift authURL hardcoded path

---

model/vfs/couchdb_indexer.go
pkg/couchdb/bulk.go
pkg/keymgmt/nacl.go
web/bitwarden/ciphers.go

Those actions are done following the suggestions from the `gocritic` linter
The errors was:
```
pkg/keymgmt/nacl.go:97:7: unslice: could simplify keyBytes[:] to keyBytes (gocritic)
pkg/keymgmt/nacl.go:85:21: unslice: could simplify keys[:] to keys (gocritic)
web/bitwarden/ciphers.go:140:17: unslice: could simplify k[:] to k (gocritic)
model/vfs/couchdb_indexer.go:331:15: unslice: could simplify docs[:] to docs (gocritic)
pkg/couchdb/bulk.go:266:15: unslice: could simplify docs[:] to docs (gocritic)
pkg/couchdb/bulk.go:267:10: unslice: could simplify olddocs[:] to olddocs (gocritic)
```

Remove some useless `[:]` annotation

---

model/account/credentials_test.go
model/app/installer_konnector_test.go
model/app/installer_webapp_test.go
model/instance/lifecycle/lifecycle_test.go
model/job/mem_scheduler_test.go
model/job/redis_scheduler_test.go
model/job/trigger_event_test.go
model/oauth/client_test.go
model/remote/remote_test.go
model/vfs/permissions_test.go
model/vfs/vfs_test.go
pkg/config/config/config_test.go
pkg/crypto/mac_test.go
pkg/crypto/utils_test.go
web/accounts/oauth_test.go
web/auth/auth_test.go
web/data/references_test.go
web/files/files_test.go
web/files/notsynchronized_test.go
web/files/referencedby_test.go
web/jobs/jobs_test.go
web/notes/notes_test.go
web/office/office_test.go
web/permissions/permissions_test.go
web/realtime/realtime_test.go
web/routing_test.go
worker/exec/konnector_test.go
worker/push/push_test.go

The following pattern:
```go
if !assert.NoError(t, err) {
return
}
```
does the following steps:
- check if there is an error
- log the error with the assert package
- exit the test immediately
All those steps can be done with a single line:
```go
require.NoError(t, err)
```

Replace some multiline assert() use by a require call

---

model/account/accounts.go
model/job/broker.go
model/job/scheduler.go
model/sharing/shared.go
model/vfs/metadata.go
web/files/files.go
web/jobs/jobs.go
worker/sms/sms.go

Those fix have be done following the suggestions from the gocritic linter
This commit fix the followings errors:
```
model/job/broker.go:198:2: singleCaseSwitch: should rewrite switch statement to if statement (gocritic)
model/job/scheduler.go:228:2: singleCaseSwitch: should rewrite switch statement to if statement (gocritic)
model/vfs/metadata.go:176:2: singleCaseSwitch: should rewrite switch statement to if statement (gocritic)
```

Fix the gocritic `singleCaseSwitch` suggestions

---

cmd/config.go

Those fixes are following the suggestions from the gocritic linter
The fixed errors was:
```
cmd/config.go:45:15: badCall: suspicious Join on 1 argument (gocritic)
filename = filepath.Join(utils.AbsPath(args[0]))
^
cmd/config.go:125:15: badCall: suspicious Join on 1 argument (gocritic)
filename := filepath.Join(utils.AbsPath(args[0]))
```

Fix the gocritic `badCall` suggestions

---

worker/archive/unzip_test.go
worker/exec/konnector_test.go
worker/mails/mail_test.go
worker/push/push_test.go

Refactor the `worker/` test init
This refactoring consist to use the subtest pattern (https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks)
in order to remove the use of the `TestMain` function. This bring several
advantages:
- It scope the data inside the tests, making them easier to read
- It allow to setup several instance per package
- It allow to cleanup the test correctly by applying the defer and using t.cleanup (exitAfterDefer issue https://github.com/cozy/cozy-stack/issues/3622)
- It allow to use the logger from the tests and printing only the log in error
- It allow to use `t.Tempdir()` which is automatically cleaned
- It allow to use `t.Name()` for the instance naming
- It allow to setup the `--short` flag
- It allow to remove a lot of global variables and possible …

Refacto tests worker

---

docs/apps.md
docs/client-app-dev.md
web/apps/serve.go
web/middlewares/assets.go

This helper can be used by front applications in their html template to insert an HTML tag for loading the fonts.css file, and thus the Lato and Lato bold font. The fonts.css can also be overloaded by context via dynamic assets, and be used to load other web fonts.

Add {{.CozyFonts}} helper

---

pkg/config/config/config_test.go

`t.Setenv()` ensure that the env will be restored at the end of the test

Replace the use of `os.Setenv` by `t.Setenv` when possible

---

pkg/assets/dynamic/dynamic_test.go
pkg/config/config/config_test.go
pkg/hooks/hooks_test.go
web/apps/apps_test.go
worker/exec/konnector_test.go

t.TempDir will automatically remove the folder at the end of the test.

Use `t.TempDir()` instead of `os.TempDir()` in tests

---

.golangci.yaml

This lint was not deactivated due to the use of the `TestMain` functions. Now we can enable it again and be sure that the tests are correctly cleanup.

Enable the exitAfterDefer lint

---

web/permissions/permissions.go

When returning permissions from an interact sharecode, we'll return
the associated sharing member in the `included` part of the response
like we already do with preview sharecodes.

fix: Return member with interact permissions

---

web/apps/apps.go

It appears it was forgotten in an earlier commit

feat: map CozyFonts() to the apiOpenParams object

---

model/sharing/sharing.go

To check if a sharing member's instance can be found in CouchDB, we
first need to parse the member's URL instance to retrieve its domain.
However, when the Cozy is reachable using a specific port, that port
is part of the instance's domain (i.e. in the form of
`<domain>:<port>`).
We assumed that a missing port in an `http` URL would give port value
of `80` once parsed (and `443` for a `https` URL) but that's not the
case.
Therefore, in these situations, the instance's domain used for the
CouchDB request would have the form `<domain>:` and the instance would
never be found.

fix: Handle missing port in sharing instance check

---

model/sharing/sharing.go

To check that a sharing member's files and folders are consistent with
those of the owner, we need to get the owner's XOR key from the
member's credentials list.
However, it turns out that members can have an empty list of
credentials which generates a go panic when we try to access the first
one containing the owner's XOR key.
We add a new check before trying to get the key to avoid these panics
and notify us of the issue.

fix: Check sharing member credentials before docs

---

model/sharing/sharing.go

There's no point in checking an inactive sharing member's files and
folders' consistency with those of the sharing owner as the
synchronization is not active anymore.
Besides, no skipping them would mean returning
`invalid_number_of_credentials` errors while this is a perfectly
normal situation.

fix: Skip sharing checks for inactive members

---

model/account/accounts.go
model/bi/webhook.go
web/data/accounts.go
worker/exec/konnector.go
worker/exec/konnector_test.go

When running a konnector for the first time, we compute the path of
the folder that will be used to save the files fetched by the
konnector if necessary and create it if it's missing.
We should also save that path as the associated Account's default folder
path so it's reused later.

fix: Save konnector folder path into account

---

model/app/fetcher_registry.go
model/app/installer.go

When an app is installed on version x.y.z from the stable canal of the apps registry, and the stack is asked to update it to the version x.y.z-dev.shasum from the dev canal of the apps registry, the downgrade was failing because the manifest sent to the apps registry was for the x.y.z version, without the shasum. The stack is now forcing the version for this case.

Fix downgrading app

---

docs/apps.md
web/apps/apps.go

- accept logs sent for an uninstalled application
- use the jobs namespace
- accept a job_id parameter in the query string
- accept a version parameter in the query string.

Improve logs sent by the flagship app

---

model/vfs/vfsswift/thumbs_v2_v3.go

We had some old thumbnails that were incorrectly saved in Swift. When encountering one of them, we will delete it and retry generating a new one.

Fix for thumbnails handling

---

client/admin_client.go
client/apps.go
client/instances.go
client/tools.go
cmd/apps.go
cmd/assets.go
cmd/check.go
cmd/config.go
cmd/feature.go
cmd/files.go
cmd/fix.go
cmd/instances.go
cmd/root.go
cmd/swift.go
cmd/tools.go
docs/admin.md
model/move/doc.go
model/move/export.go
web/instances/instances.go
web/instances/move.go
worker/moves/workers.go

This new flag accepts a local directory path so that an admin can
make an export of the given instance.
When passing this flag, the cli will download all the export's
archives from the Cozy and save them with their archive name or, if
that name is missing from the download response, as
`<instance domain> - part<00n>.zip` in the directory pointed by the
flag.
If a file with the same name already exists, it is overwritten.
The command returns when all the archives have been downloaded.

feat: Add --path flag to admin export command

---

model/vfs/couchdb_indexer.go

Scenario of what was happening before this commit:
1. Alice shares a directory "Holidays 2023" to Bob
2. Bob accepts the sharing "Holidays 2023"
3. Bob moves this directory inside "Photos"
4. Bob moves the "Photos" directory to the trash
5. When moved to the trash, the "Holidays 2023" sharing is revoked
6. When seeing the mistake, Bob restores the "Photos" directory
7. Bob edits a note inside "Holidays 2023"
8. Bob understands that the directory is no longer shared
9. He asks Alice to share again the directory, Alice agrees
10. Bob accepts the sharing
11. The same directory is reused for the sharing
12. And conflicts happen...
The error is on step 5: the reference to the sharing was not removed from the "Holidays 2023" directory when the sharing is revoked. This commit fixes this issue.

Fix removing sharing reference on directory

---

model/contact/contacts.go
model/sharing/member.go
web/sharings/sharings.go

1. Alice sends a sharing invitation to bob@example.org
2. Bob accepts the sharing
3. On Alice's Cozy, the io.cozy.contacts for bob@example.org is updated to add the public name of Bob's Cozy if there was no fullname

Add a fullname to a sharing contacts when missing

---

.golangci.yaml

Forcing an explanation why we bypass a lint seems to be a good practice and ensure that this is an exceptional and justified behaviour.

Improve the `nolintlint` linter specs

---

model/sharing/invitation.go

When a sharing has read-write rules, but a member is read-only, the invitation mail for this member should not tell them that they will be able to edit the shared content, only to read it.

Fix invitation mail for sharing

---

model/contact/contacts.go
model/sharing/member.go
model/sharing/oauth.go
web/sharings/sharings.go

We need to fill both the fullname and the displayName, as it is what the contacts app expects.

Fix adding name to contacts on sharings

---

model/sharing/sharing.go

The cozy-stack check sharings command was returning false invalid_instance_for_member errors, because it was trying to look at instance for members that haven't accepted the sharing, and thus the instance field was blank and cannot be parsed.
We also put the domain in lower case, as the domain is case insensitive, and stored as lower case in CouchDB.

Fix false positive for invalid_instance_for_member

---

tests/integration/tests/export_import.rb

When running the export/import integration test, we are looking at an email with the export link. For that, we are querying MailHog with the instance email source+test@localhost. But, it can return us an email for konnsource+test@localhost from another integration tests. The first email address is included in the second address, and MailHog matches on that. The fix consists of having a more specific email address for the instances of the export/import test.

Fix the export/import integration test

---

cozy.example.yaml
docs/settings.md
model/instance/instance.go
web/settings/instance.go

The redirection after a login can be configured via the "default_redirection" setting of the instance. The format is composed of the app slug and the route, separated by a slash.

Allow to configure the default redirection

---

model/sharing/sharing.go

Some instances were having a no_database error on the check sharings command, because the sharing root of an active sharing is missing. It would be better to categorize this error as
missing_matching_docs_for_member.

Improve check sharings command for no_database

---

docs/admin.md
model/sharing/sharing.go

Members of a sharing who don't have received the invitation e-mail and
are thus not ready to share are excluded of the tree consistency
checks but it would be nice to be notified via a dedicated check as
this is not a normal situation.

feat: Add mail_not_sent sharings check

---

model/app/webapp.go
web/instances/fixers.go

This command was recreating missing triggers for app services, but the triggers were recreated without the service name in the message. So, we need to fix the script, and to add a way to also fix the triggers that miss the name.

Fix the cozy-stack fix service-triggers command

---

cmd/root.go

Triple CLI clients timeout to avoid timeout with long running commands like exports on instances with a huge number of files.

Increase cli clients timeout

---

model/contact/contacts.go
model/sharing/oauth.go

The contacts application may fill the displayName of a contact with their email address. We need to ignore this case when filling the fullname for a sharing contact with just the email address known.

Fix adding the fullname to a sharing contact

---

pkg/realtime/mem_realtime.go

When a realtime websocket is closed, the Subscriber calls close on the realtime hub. It iterates on the sucscribed keys, and removes them. But the list of keys was modified during the loop, which can make some topics to be kept, and their goroutines won't be stopped.

Fix goroutine leak in realtime

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/impl_inmemory.go
pkg/cache/impl_redis.go

The `/pkg/cache/cache.go.Cache` struct seems to contains two separate
behavior based on the presence (or not) of a redis client.
If the redis client is present we are using the redis client, if not
we are using an in-memory implementation.
The goal of the next commits is to separate those two logic in two
separate implementations in order to increase the readability.

Cache refacto

---

model/sharing/indexer.go
model/sharing/replicator.go
model/sharing/replicator_test.go
model/sharing/revisions.go
model/sharing/revisions_test.go
model/sharing/sharing.go
pkg/couchdb/bulk.go
pkg/couchdb/revision/rev.go
pkg/couchdb/revision/rev_test.go
web/sharings/replicator_test.go

Adding some logs for bulk operations can be helpful for debugging sharing issues.

Improve sharing logs

---

pkg/assets/dynamic/fs.go
pkg/assets/dynamic/impl_os.go
pkg/assets/dynamic/impl_swift.go

By moving each `assetFS` implementation into their own file, it became a lot easier to see what implementations is available by looking the file tree.
Now the `fs.go` file contains only the interface and initialization function.

Move the implems inside `/pkd/assets/dynamic` into their own files.

---

pkg/limits/impl_inmemory.go
pkg/limits/impl_redis.go
pkg/limits/rate_limiting.go
pkg/limits/rate_limiting_test.go

This will permit to quickly see what implementation is available and facilitate the navigation inside an implementation

Move the rate limiters implementations in their own files

---

pkg/limits/rate_limiting_test.go

This ensure use that both the implementation have the exact same behavior. It will also make easier the new tests and the new implems.

Use the same tests for all the `/pkg/limits` implems

---

.github/workflows/ci.yml

This cache option follow the official github documentation: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go#caching-dependencies

Add some cache to the CI job

---

model/sharing/replicator_test.go

This param seems to have been added by an incorrect `sed` command
Fix issues from #3796

Remove an unwanted param in a test assert

---

.github/workflows/ci.yml
.github/workflows/go-lint.yml
.github/workflows/go-tests.yml
.github/workflows/js-lint.yml

This lint job will run the golangci-lint tool on all the go files
This job have been done following the following documentation: https://github.com/golangci/golangci-lint-action

Add a lint job for go files

---

worker/exec/konnector_test.go

Fix a datarace in `/worker/exec` tests

---

model/intent/intents_test.go
model/move/export_test.go
model/oauth/client_test.go
web/apps/apps_test.go
web/middlewares/user_agent_test.go
web/remote/remote_test.go
web/sharings/replicator_test.go
web/sharings/sharings_test.go

The tests seems to encounter some issues where two tests are using the same global variable creating randoms side effects. 
This review propose to avoid this kind of issue by moving as much variable inside the tests scope. This is also a requirement for running tests in parallel. This is not possible yet but it could be a great improvement in the future.
Bonus side effect: It allow us to detect unused variables and remove them.

Remove the global `instance.Instance` variable inside the tests

---

worker/push/push.go

If an application is sending a push notification, and the user doesn't have the mobile app for it, but has the flagship app, the stack will fallback to send the push notification to the flagship app. But the firebase configuration can be different for the mobile app and the flagship app. This commit fixes the firebase configuration used when fallbacking to the flagship app.

Fix sending push notification to flagship app

---

.github/workflows/go-tests.yml

This will make the job title more explicit

Rename the `CI` job to `Go tests`

---

pkg/avatar/initials_convert_test.go

It seems that there is some output change between the images generated by the CI and in local. I guess this is due to the different versions of convert.
We don't want to force a specific version for everyone so we will only check that the two files a PNGs and they have the same size.
Fix some issues from #3796

Do not compare PNGs pixel by pixel

---

model/account/credentials.go
model/account/credentials_test.go
model/stack/main.go
pkg/config/config/config.go
pkg/keyring/service.go
pkg/keyring/stub.go

Previously the vault logic was living inside the `/pkg/config` package in a global alongs with other config stuff.
This PR goal is to make a clear separation between the vault logic, where some important secrets are handled and the config logic. It also remove the global variable and move to the same initialization logic than the cache or lock package: It create an object and put it into the `Config` object.

Move the vault logic into a new package

---

model/sharing/indexer.go
model/sharing/oauth.go
model/sharing/sharing.go
model/sharing/upload.go
model/vfs/couchdb_indexer.go
model/vfs/vfs.go
pkg/couchdb/index.go
web/files/files.go

When the stack sends a request for creating a sharing, it includes the number of files in the sharing. Counting the number of files may have been slow because we were walking the VFS to count the files. We have optimized it by reusing a CouchDB view.

Optimize counting the number of files in a sharing

---

cmd/config.go
model/account/credentials.go
pkg/keyring/nacl_key.go
pkg/keyring/service.go
pkg/keyring/stub.go

This package was only use in `keyring` so it doesn't make much sense to separate them.

Merge the `/pkg/keymgmt` package inside `/pkg/keyring`

---

docs/jobs.md
model/job/scheduler.go
model/job/trigger_cron.go

In order to be able to run a trigger hourly.
It was already possible to do it from the manifest but not from the API.

feat: Add Hourly trigger

---

model/sharing/files_test.go
model/sharing/indexer.go
model/sharing/oauth.go
model/sharing/sharing.go
model/sharing/upload.go
model/vfs/couchdb_indexer.go
model/vfs/vfs.go
pkg/couchdb/index.go
web/files/files.go

In commit ce5f1b0219e189203954dddaef805f008bd4c217, we tried to optimize the counting of files by using a CouchDB view. We changed the reduce property, and I thought CouchDB wouldn't recalculate the whole view. But it does, and it is too heavy for our servers. So, let's use the view as it is today, even if it needs more code and is a bit less optimized.

Do not change the CouchDB views

---

model/instance/lifecycle/get.go
model/instance/lifecycle/helpers.go
pkg/couchdb/bulk.go
pkg/couchdb/couchdb.go
pkg/couchdb/views.go

When a Cozy was created before the set of indexes or views for an instance was last changed, it has a different IndexViewsVersion. This number can be used by the stack when a Cozy is used to check if the views and indexes must be updated.
Before this commit, the update process was the same as the creation process. We iterate on all views and indexes, trying to create them, and if it fails, look if the view/index exists and has the right definition, and if necessary update it.
With this commit, the update tries to opmitize this process, by first looking what views and indexes exists, and only try to create/update it when missing or not the right definition. It should help to lower the load on the CouchDB cluster when we release a stack with an increased IndexViewsVersion.

Improve views and indexes update

---

docs/admin.md
web/oidc/oidc.go
web/oidc/oidc_test.go

The delegate userinfo endpoint for OIDC was using an Authorization header for the access_token. But, as it was on the admin endpoint, there was also an Authorization header for basic auth of admin. And the two headers were conflicting: they were not manager correctly by cloudery and stack. We can fix the issue by passing the access_token in the POST body (as JSON).

Fix delegate userinfo endpoint

---

assets/locales/fr.po

Correcting a typo in cozy flagship app registration message.
I don't know well the testing/merging process.
You take the baby ?

fix: Typo in flagship app registration message

---

model/stack/main.go
pkg/config/config/config.go

The keyring is initialized in the pkg/config/config package. It was initialized a second time in the model/stack package, but with the stub implementation. It was a mistake!
Cf https://github.com/cozy/cozy-stack/pull/3821

Fix keyring initialization

---

Makefile
cozy.example.yaml
scripts/konnector-dev-run.sh

This runner uses NodeJS with the appropriate DNS resolution argument
depending on its version, making sure every request will use an IPv4
DNS resolution as `cozy-stack` does not listen to IPv6 addresses yet.
This runner also forwards all outputs to a dedicated log file in
`~/.cozy/services.log` for easy access.

dev: Add dev konnector runner

---

pkg/realtime/mem_realtime.go
pkg/realtime/subscriber.go

When a client asks for UNSUBSCRIBE on a doctype, and just after that for SUBSCRIBE on the same doctype, there was a race condition where a part of the UNSUBSCRIBE process were done after the process for the SUBSCRIBE. It is due to the lock for the mem hub being acquired in goroutines. We are now getting the lock sooner to avoid this issue.
In practice, this bug was seen when emptying the trash in Drive web and files were still on the screen as Drive was not receiving the realtime notifications for them.

Fix a race condition on realtime

---

model/account/accounts.go

When we delete an account related to a client side konnector or when we uninstall a client side konnector, we want the stack to delete orphaned triggers.
So we have to not ignore `client` trigger.

fix: Delete triggers for `client` trigger

---

pkg/config/config/config.go

As precised in https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html the config files should be hosted inside the folder `$XDG_CONFIG_HOME`.
In order to allow a retro-compatibility with the previous path we use this file only when it's available.

Add support for XDG Base Directory specification for the config file

---

model/account/accounts.go
model/job/scheduler.go
web/apps/apps.go

This is a followup of https://github.com/cozy/cozy-stack/pull/3862.
When deleting an account, uninstalling a konnector or destroying an
instance, we try to clean orphaned konnector accounts and triggers.
However, when checking triggers types, we forgot to take into account
the type associated with client side konnectors thus leaving their
triggers untouched.
We'll now use a new `trigger.IsKonnectorTrigger()` method to make this
check and make sure all orphaned konnector triggers are removed.

fix: Check both konnector types when cleaning data

---

pkg/logger/logger.go
pkg/logger/logger_test.go

This refactoring brings three main advantage:
- It remove the global lock inside `/pkg/logger` and replace it by a `sync.Map`. This shoud reduce the number of request hanged, waiting to have access to the logger
- It reduce the number of access to the new `loggers` variable by accessing it only when we log in debug with the domain field setup and not each time we had a domain field.
- It make the `AddDomain` function behave like a classic new field. This will allow us to link this method to `Entry`.

Refactor the way `/pkg/logger handle` the debug mode

---

model/sharing/shared.go

When a directory is moved from a shared folder to another shared folder, the stack creates two jobs for updating the io.cozy.shared document related to this directory (one for each sharing). There is a lock to prevent the two jobs from working concurrently, but if the job for the latter sharing was processed before the other job, the removed flag wasn't set for the former sharing. It was due to an incorrect optimization.

Fix a race condition when updating io.cozy.shared

---

model/sharing/invitation.go
model/sharing/member.go
web/sharings/sharings.go

If Alice creates a sharing with Bob in read/write mode, and with the open_sharing set tot true, Bob can add recipients to this sharing. If Bob has a contact with a Cozy URL but no email, adding this contact to the sharing was failing. Bob's Cozy was trying to send the invitation, but it can't create the shortcut as it requires the Xor key for this new recipient (only available on Alice's Cozy), and it can't send an email as the email address is not known. We have fixed this issue by making the owner's Cozy creating the shortcut in that case.

Fix adding a contact by Cozy URL to a sharing with delegation

---

pkg/avatar/initials_convert.go
pkg/avatar/initials_convert_test.go
pkg/avatar/service.go

ImageMagick leaves a file on the filesystem after each run. They need to be cleaned periodically in order to avoid taking unnecessary space.

Clean the files left by ImageMagick every hour

---

web/middlewares/permissions.go

When validating permission claims from a Cozy Pass client, we want to
log token security stamp differences.
However, if we had a CouchDB error while fetching the expected
security stamp from the settings, trying to log it will panic as it
means dereferencing a nil pointer.
In this case, we'll log a more generic error encapsulating the
original error message.

fix: Log expected security stamp only when fetched

---

scripts/konnector-dev-run.sh
scripts/konnector-node17-run.sh
scripts/konnector-nsjail-node17-run.sh

This flag was used to force the use of ipv4 for node 17+. As we just have enable the ipv6 listening this flag is no more useful

Remove the flag `--dns-resolution-order-ipv4first`

---

pkg/assets/dynamic/dynamic.go
pkg/assets/dynamic/impl_afero.go
pkg/assets/dynamic/impl_afero_test.go

https://github.com/cozy/cozy-stack/pull/3785/commits/e1fe8a537387228750e4213144c1557a74a2466f#diff-e35f56a6ed6c1d2da87f0ee14ed6e74b729656eb08a795d95b913e5726341727R75 has introduced a regression. The code was trying to read the assets without nbeing bound to the afero object, which doesn't work.

Fix listing assets

---

web/data/data.go

We want to allow reading the bitwarden settings document with the permissions given by the bitwarden OAuth client, and the permission on the com.bitwarden.organizations doctype seems legit for that use case.

Add a special case of permission for the bitwarden settings

---

model/sharing/sharing.go

When a single file is shared, and the sharing is revoked, the stack should not transform the file to a directory (with a "sharing revoked" suffix in its name).

Fix revoked sharing for a single file

---

pkg/registry/registry.go
web/apps/maintenance.go
web/registry/registry.go

When an app is present in several apps registry spaces for the same context, it may happen that a maintenance is present in a space with a lower priority and should not be sent to the client. The stack now correcty handles this case by fetching all the slugs from higher priority registries.
It requires https://github.com/cozy/cozy-apps-registry/pull/401

Fix the maintenance list from the apps registry

---

web/auth/deprecated_app_list.go
web/auth/deprecated_app_list_test.go

This ClientOS field is already parsed so no need to use the user_agent package again. There is also some issues withe some unexpected upercase inside the OSs names. This commit normalize the name by using the lowercase everywhere

fix: Handle correctly the ClientOS field

---

pkg/logger/debugger_redis.go
pkg/logger/debugger_redis_test.go

It happens that we want to execute some cozy-stack CLI commands without having the credentials for redis. In that case, it was failing when initializing the logger, when trying to load the instances in debug mode. We can ignore this error, as it not a big deal if stack doesn't load them.

Fix the 'bootstrap failed' error on some CLI commands

---

model/app/installer.go
model/permission/permissions.go
web/apps/apps.go

This forces the konnectors/apps refresh from their source after each reload for apps or each run for konnectors.
This should improve the dev experience by allowing them to install a local application using the following command:
`cozy-stack konnectors install foo file://my/project/folder/build`

feat: Allow to dev in local with the `install` cmd

---

pkg/config/config/config.go
pkg/logger/logger.go

The `logger` package does need to setup `logger.debugger` in order to
know wich instances are in debug mode. One of the `debugger`
implementation (`RedisDebugger`) does need a redis client. The issue
is that once started the redis client log some lines but we don't have
setup the logger yet. This lead to have the first log lines from the
`debugger` redis client on stdout instead of syslog.
In order to fix this this commit setup the redis global logger juste
after setting up the global logger and before setting up the debugger.

fix: Avoid to log the first redis lines on stderr

---

pkg/lock/lock.go
pkg/lock/lock_test.go
pkg/lock/simple_mem.go
pkg/lock/simple_redis.go

Due to the hardcoded timeout, some tests was waiting 20s for an expiration. By setting it inside the struct we can modified it and wait only a few miliseconds

refactor: Make the lock tests much quicker

---

web/settings/instance.go

We want to implement a feature in the Pass clients (bases on bitwarden) that requires to read the instance settings. The bitwarden protocol has a based on OAuth2 with a fixed set of permission coded in the stack. Changing this set of permissions would work for new clients, but for existing clients, a migration would be required and quite complex. So, we have prefered to modify how the permissions are checked for reading the instance settings.

Allow the Pass clients to read the instance settings

---

model/app/fetcher_file.go
model/app/fetcher_git.go
model/app/fetcher_http.go
model/app/fetcher_registry.go
model/app/installer.go
model/job/mem_broker.go
model/job/redis_broker.go
model/job/worker.go
model/note/note.go
model/sharing/member.go
model/sharing/setup.go
pkg/couchdb/couchdb.go
pkg/lock/simple_redis.go
pkg/logger/level.go
pkg/logger/level_test.go
pkg/logger/logger.go
web/apps/apps.go
web/jobs/jobs.go
web/statik/handler.go
worker/exec/common.go
worker/exec/konnector.go
worker/exec/service.go
worker/push/push.go
worker/sms/sms.go
worker/thumbnail/thumbnail.go
worker/updates/updates.go

This interface aims to bring two main advantages:
- This open the possibility to have several different implementation
for a logger and switch between them when needed. For example we will
be able to create:
- A logger for the tests based on `testing.T.Logf` which will attach
the logs to a given test and improve the errors readability.
- A NoOp logger logging nothing when we don't want to polute the tests
with useless logger. We can a
- A mock logger when we need to test whate have been send to the
logger.
- It allow to standardise and greatly reduce the number of available methods
for the loggers. We don't have access to unwanted methods from the lib.

Create the `Logger` abstraction around the use of logrus

---

pkg/couchdb/errors.go

This will allows us to wrap the couchdb errors with some context information without losing the original error behaviour.

Refactor: Use `errors.As` for the couchdb errors

---

model/stack/main.go
web/server.go

When syslog is configured, the logs emitted by the http.Server from the stdlib should be sent to syslog, not written on stderr. We can do that by configuring an ErrorLog for the http.Server.

Send logs from http.Server to syslog

---

web/registry/registry.go

The JSON in the response wasn't in the expected format. The apps in maintenance from the registry were put in a couchdb.JSONDoc, but it was then casted to []interface{}, and the JSONDoc.MarshalJSON wasn't called when serializing to JSON.
The issue has been introduced by #3945

Fix the GET /registry/maintenance response

---

web/auth/flagship.go
web/oidc/oidc.go

When a user clicks on submit with an empty 2FA code, the stack sends again a new code. We should avoid and just tell the user to use the first sent code.

Don't send 2FA code by email on empty submit

---

model/move/importer.go
worker/moves/workers.go

When importing documents in CouchDB for a move, it may happen that CouchDB is overloaded for a database and we have to wait minutes before another request to this database can succeed. In this commit, we increasse the number of retries to help workaround this issue.

Retry for more times on CouchDB error for a move

---

docs/admin.md

`/instances/count` admin endpoint has been added in #2675 with associated `instances count` cli command but has not been documented.
This PR adds documentation for the `/instances/count` admin endpoint

Document instances/count admin endpoint

---

docs/settings.md
model/instance/instance.go
model/instance/lifecycle/create.go
model/instance/lifecycle/passphrase.go
web/realtime/realtime.go

When the password is defined for an instance, an app can be notified with the realtime websocket by listening on a synthetic document. This document have the io.cozy.settings doctype, and
io.cozy.settings.passphrase for the id.

Add realtime event for password_defined

---

model/instance/lifecycle/destroy.go
model/instance/manager.go

Invalid cloudery config type castings were causing panics.
Clouderies config used to be maps of `string` to `interface{}`,
requiring type casting to access their attributes.
However, a dedicated `ClouderyConfig` struct was created and thus
every use of a cloudery config should not do type casting anymore and
use the struct members directly.

fix: Update clouderies config usage

---

web/auth/auth.go
web/auth/oauth.go
web/auth/register.go
web/settings/clients.go

There is a follow-up of e3b2bbb. We are adding the lock around OAuth client writes to the endpoints that updates its synchronization date, that updates the client information, or delete a client.

Add the lock for OAuth clients to more places

---

model/settings/service.go
model/settings/service_test.go

The Cozy client has difficulty handling field deletion via realTime. When merging, it will use the previously present field if field is not find. This allows it to update documents with requests that only select a few fields in a document. If the field is present with a value (null or empty), it will update it and the interface will react.

fix: Pending email with cozy-client

---

cmd/serve.go
pkg/avatar/initials_convert.go
pkg/avatar/initials_convert_test.go
pkg/avatar/service.go
pkg/config/config/config.go

Each cozy-stack command was creating a temporary directory for image magick that was not removed later. We are now using a temporary directory for each initials image creation, and we clean it when image magick has finished running.

Clean the pkg/avatar package

---

web/auth/passphrase.go

If an instance has not been onboarded, the stack will show an error screen if the user tries to reset their password. It may happen when trying to connect the Pass extension, typing the instance URL, and then then the "password forgotten" button.

Block password reset for not onboarded instance

---

web/bitwarden/bitwarden.go

On Cozy Pass mobile when the login requires 2FA and when the user enters a wrong password, then the API should return a dedicated error message
With previous implementation, the same error would be returned on first login attempt and on second one containing a 2FA token. This would result on the app completing the login process but displaying an empty vault. This behaviour is wrong but is from Bitwarden's implementation. However with correct server implementation the correct behaviour happens

fix: Set correct bitwarden error (JSON) when wrong 2FA code

---

model/vfs/vfsswift/fsck_v1.go
model/vfs/vfsswift/fsck_v2.go
model/vfs/vfsswift/fsck_v3.go
pkg/appfs/server.go
pkg/assets/dynamic/impl_swift.go
web/swift/swift.go

- Use the ObjectNamesAll method instead of walk+names
- Use explicit pagination parameter (limit)

Optimize some calls to Swift server

---

model/bitwarden/oauth.go
tests/integration/tests/accounts-to-ciphers.rb

There was an offset in parsed DeviceType number as `Edge extension` is not `4` but `5` (`4` is `Opera extension`). So everything above `4` and under `15` was impacted by this offset
This means we wrongly attributed `desktop` to `Edge extension` (`5`) clients and `web` to `Linux` (`8`) desktop clients
This is based on JSLib enum targeted by current cozy-pass-web version
Related file:
https://github.com/bitwarden/jslib/blob/c8eca37183c5fa67d0b0988402aea49d0f0f505c/src/enums/deviceType.ts#L7-L10

fix: Correctly parse Bitwarden DeviceType

---

model/sharing/revisions.go
model/sharing/revisions_test.go

It is a follow-up of #3582. When an io.cozy.file is created and modified just after, it may happen that the share-track job for the update is processed before the job for the creation. When this happens, the revs tree for the io.cozy.shared wasn't correct: the revision 2 was coming before the revision 1. The previous commit was fixing some cases, but there is one more case that we should handle.

Fix share-track jobs when out of order (bis)

---

pkg/lock/lock.go
pkg/lock/lock_test.go
pkg/lock/simple_mem.go
pkg/lock/simple_redis.go

The lock tests were flaky on the CI, but it wasn't the fault of the test. There were some issues in the code:
- there was a race condition when a long lock in redis was trying to extend, allowing another writer to potentially gain the lock
- the long operation lock could not be reused (its internal mutex wasn't unlocked at the end).
And the order of functions for the redis implementation was changed to have the same structure as the in-memory implementation.

Fix some lock issues

---

web/files/references.go

When a request for listing all files referenced by a document, the stack uses the VFS lock. It was using the lock in write mode, and it has been changed to read mode to allow concurrent requests for this endpoint to be parallelized.

Use a read lock for listing references

---

web/auth/register.go
web/middlewares/instance.go
web/middlewares/permissions.go
web/settings/passphrase.go

We found out that some middlewares like `CheckInstanceBlocked` would
modify the response headers if the request's authentication token was
invalid (e.g. because it's expired).
This is because we use the `GetPermission` middleware to get a
permission doc and check its type to do some specific actions when the
request is done via the CLI and the `GetPermission` middleware will
eventually change the response headers via a call to `ExtractClaims`
when the token is invalid.
We're modifying `ExtractClaims` to move the side effect outside the
function and introducing a new `GetCLIPermission` middleware which
will try to get a CLI permission from the context without side effects
or erroring out.
We can then use it to check if the request is done via the CLI.

fix: Don't modify headers to get CLI permission

---

assets/locales/de.po
assets/locales/en.po
assets/locales/es.po
assets/locales/fr.po
assets/locales/ja.po
assets/locales/nl_NL.po
model/notification/center/notification_center.go

We set `mobile` as the preferred channel for the (almost) reached
quota notification that was sent only by e-mail.
The notification will redirect the user to the storage view of the
Settings application when opened.
E-mail is still added as a fallback transport when no mobile
devices are reachable.

feat: Prefer mobile push for quota notification

---

model/note/note.go

When updating a Note, we would take the new Document's metadata and
store it in stead of the old file's Metadata since the Note's title,
version, schema and content are stored there.
However, other apps can store data in a file's Metadata, such as a
qualification, and we don't want to lose this.
From now on, we'll merge the 2 Metadata objects, overriding any
existing Note metadata value but preserving metadata from other apps.

fix: Preserve other metadata when updating note

---

docs/files.md
model/sharing/sharing.go
model/vfs/errors.go
model/vfs/vfs.go
model/vfs/vfs_test.go
web/files/files.go
web/files/files_test.go
web/notes/notes.go
web/sharings/sharings.go
web/shortcuts/shortcuts.go

When uploading a file we can receive a `413` error response in return
in 2 cases:
1. uploading the file would exceed the quota of the Cozy
2. the file size is larger than the server's filesystem's maximum file size
We want clients to be able to make the difference between the 2
situations as they otherwise need to make an extra request to the
server to fetch the disk quota or hardcode the server's filesystem's
maximum file size.
Thus we introduce a new `ErrMaxFileSize` error which will still be
returned with a `413` HTTP status but with a different body.

feat: Add error for files larger than FileMaxSize

---

docs/flagship.md
model/notification/center/notification_center.go
worker/push/push.go

Don't include the app's slug in the disk quota push notification
title.

fix: No app slug in disk quota push notification

---

model/sharing/upload.go

It should not happen, but if the stack try to upload a deleted file, it should detect it and skip this file instead of looping on this file with an error.

Don't try to upload deleted files

---

assets/locales/de.po
assets/locales/en.po
assets/locales/es.po
assets/locales/fr.po
assets/locales/ja.po
assets/locales/nl_NL.po
model/notification/center/notification_center.go

Based on a misunderstanding, we were sending a push notification when
reaching 90% of the disk quota (i.e. the `capsize`) with a message
intended for a fully reached quota.
However, there are 2 things to note:
1. there are no notifications when reaching 100% of the disk quota (so the term "exceeded" in the existing notification refers to the capsize or 90% of the disk quota)
2. because the disk quota can never be reached from below since `cozy-stack` will refuse the upload if it would mean reaching the quota
Therefore, we can completely remove strings related to an hypothetical
reached disk quota notification and always use those of the reached
capsize.

fix: Use right strings in disk quota notification

---

scripts/integration-test.sh

The stack now listen on both IPv4 and IPv6, so this hack should no longer be required.

Remove hack for GitHub Actions

---

model/sharing/files.go

It happens that the stack needs the main directory for a sharing. For example, when it receives a new file that is inside the shared directory. The stack was using a referenced_by to find it, but we have found in production that the referenced_by can have been put on the wrong directories. We will now use the ID when we have it, and only use the referenced_by if not.

Improve the way we get the sharing dir

---

worker/exec/konnector.go

When running a konnector, the worker will copy the konnector's source
code to a temporary directory and execute the scripts from this
workdir.
After the run, the worker will call a cleanup function that's supposed
to delete the workdir.
Both the workdir and cleanup functions are defined and returned by the
worker's `PrepareWorkDir` method.
However, in the konnector worker's case, when preparing for an
`OnDeleteAccount` script execution, we change the workdir to the
script's path thinking the cleanup function would be left untouched.
But it happens that this function uses the workdir variable that we
modify so we end up removing only the `OnDeleteAccount` script instead
of the whole directory.
This is a simplified version of what was happening:
```go
var workdir string
cleanDir := func() …
```

fix: Cleanup after OnDeleteAccount konnector run

---

.github/workflows/js-lint.yml

The third-party `eslint` action we were using has changed its API
making it very hard for us to check files from folders outside the
`scripts` folder.
Since it's pretty easy to run `eslint`, we'll stop using the action
altogether.

fix: Run eslint without third-party action

---

model/sharing/upload.go

When a sharing is revoked during its initial synchronization, it may happen that the stack panics.

Fix a panic

---

model/sharing/replicator.go
pkg/couchdb/bulk.go

When there were more than 1000 documents in a call to BulkUpdateDocs, only the first 1000 were updated, because of a pagination bug.

Fix BulkUpdateDocs function

---

model/bi/api.go

When a webhook from Powens is received, the stack calls Powens API, with an URL constructed from a baseURL and an endpoint path. If the baseURL had a path (like https://domain/biapi.pro/2.0), it was missing in the final URL.

Fix URLs when calling Powens API

---

model/sharing/files.go
model/sharing/upload.go

When a conflict happens for two directories with the same path, one directory is renamed. Its path wasn't updated with the new name in this case.

Fix a path inconsistency

---

docs/settings.md
model/instance/tos.go
model/oauth/client.go
model/oauth/client_test.go
tests/testutils/test_utils.go
web/apps/apps.go
web/apps/apps_test.go
web/apps/serve.go
web/middlewares/instance.go
web/middlewares/warnings.go
web/routing.go
web/settings/clients.go
web/settings/settings.go
web/settings/settings_test.go

If the user manages to connect more OAuth clients than is allowed
(e.g. by trying to connect a Flagship app while the limit was already
reached), we want to redirect them to the Settings app to manage their
clients or increase their limit if they can.
If the request is asking for a JSON response, we'll return the list of
warnings (including a new warning for the reached OAuth clients limit)
instead of redirecting.

feat: Block users with exceeded clients limit

---

docs/settings.md
pkg/consts/consts.go
web/settings/clients_usage.go
web/settings/clients_usage_test.go
web/settings/settings.go

This will be useful to know how many OAuth clients a user has already
connected to their Cozy and how many they're allowed to create,
especially for the flagship app to decide whether it should complete
its onboarding flow or present the user with a modal requesting to
either remove some clients or increase the limit if they're able to.

feat: Add route to fetch OAuth clients usage

---

model/instance/instance.go
model/notification/center/notification_center.go
model/oauth/client.go
tests/testutils/test_utils.go
web/auth/oauth.go
web/settings/clients.go

`enable_premium_links` is not a feature flag but actually a Context
attribute which we can get from the config.
Without this attribute, we would never show links to the manager's
offers page when the limit of connected OAuth clients is exceeded.

fix: Fetch premium links status from config

---

model/vfs/vfsswift/thumbs_v2_v3.go
worker/thumbnail/thumbnail.go

It happens that the stack creates several jobs that will process a tiny thumbnail for the same image with imagemagick. We can avoid the useless calls to imagemagick with a lock + looking at Swift if the thumbnail exists.

Avoid useless calls to imagemagick

---

web/settings/clients.go
web/settings/settings_test.go

We should return an Unauthorized error when someone tries to access
the clients limit exceeded route of a Cozy without a valid session
(i.e. without being logged in).

fix: Clients limit exceeded route requires login

---

model/app/installer.go
model/app/installer_konnector_test.go
model/app/installer_webapp_test.go

Send more explicit error to client when type mismatch on installing a webapp or konnector

More explicit error on app install type mismatch

---

docs/docker.md
docs/office.md
model/office/callback.go
model/office/errors.go
model/office/file_by_key.go
model/office/open.go
model/office/store.go
web/files/files.go
web/files/files_test.go
web/office/office.go
web/office/office_test.go

When a new version of an office document is uploaded to a Cozy, the
stack will now open this new version, even if the previous version of
the document was already in the cache of OO. It was too confusing for
the user that has uploaded a new version to not see their changes if
they open the document in OO. If there was other users editing the
document in OO, they will be alerted of the conflict by cozy-drive and
can refresh their tab to see the new version. And if there were changes,
they are not lost, but will be saved in a conflict document.

Fix onlyoffice behavior

---

model/sharing/files_test.go
model/sharing/indexer.go

When a member of a sharing modifies a directory within this sharing
then the `io.cozy.files` doc on the other members' Cozy will lose
their `not_synchronized_on` attribute.
This means the directory will get synchronized with their Desktop
client again while they haven't modified the configuration themselves.
This is because we forgot to keep the existing attribute when updating
the document in the sharing indexer.

fix: Preserve not_synchronized_on on shared dirs

---

.golangci.yaml
client/instances.go
cmd/apps.go
cmd/check.go
cmd/config.go
cmd/feature.go
cmd/files.go
cmd/fix.go
cmd/instances.go
cmd/jobs.go
cmd/root.go
cmd/settings.go
cmd/tools.go
pkg/statik/statik.go
tests/swift/swifttest.go
web/server.go

Printf is often used while developping to inspect or debug code. It happens that these statements are forgotten and commited. We can prevent that by using a linter to disable them.
We have some cases where fmt.Printf was used to print useful stuff, like in the CLI. They have been rewritten in fmt.Fprintf to avoid been flagged by the linter.

Add a linter to disable fmt.Printf in code

---

model/vfs/couchdb_indexer.go
tests/system/lib/folder.rb
tests/system/tests/filepath_operations.rb

CouchDB is using ICU algorithm for views and mango requests. It can be surprizing, and it was the source of a bug in the stack. When a directory 'EDF' is trashed, and a directory 'EDF⚡️' was nearby, the path of this directory can be incorrectly modified to be put in the trash.
The system test 'filepath_operations.rb' was restored from a6a442b9075cef99667b36b7325b0a8b25eaf5b2, and updated to test this new case.

Fix a source of VFS inconsistencies

---

model/sharing/indexer.go

If Alice and Bob shares a file within a Cozy to Cozy sharing. The file is present on both cozy instances, and the two users make a change on this file concurrently. For example, Alice adds the file to a photo album, and Bob renames it. A race condition may happen when Bob's instance sends its update to Alice's instance. The CouchDB document will then been saved in CouchDB with a conflict (two leaf revisions).
```
+----------------------------------+----------------------------------+
| Goroutine A                      | Goroutine B                      |
| Add the file to an album         | Share-replicate sends the rename |
+----------------------------------+----------------------------------+
|                                  | 1. Load the file from CouchDB    |
| 2. Load the file …
```

Fix a race condition that leads to a CouchDB conflict

---

worker/exec/konnector.go

The system test accounts_cleaning.rb has failed a couple of times on the CI. The reason is that it tries to clean two accounts for the same konnector at the same time, and both jobs need to recreate a work directory and update the permission of the konnector. There was a race condition, where it may happen that a conflict on the CouchDB document for the permissions makes one job to fail. A retry loop will fix this issue.

Fix a race condition

---

.github/workflows/release.yml

Improve the release workflow by splitting release creation from binaries and docker image build and upload and parallelizing binary building, docker image creation and packages building.

Improve the release workflow

---

debian/control
scripts/packaging/buildpackage.sh

When a package upgrade needs installing other dependency packages, `apt upgrade` do not update the package to avoid adding other packages. You have to use `apt dist-upgrade` or `apt install`.
By default, apt installs recommended dependencies. so having couchdb as a recommended dependency blocks simple package upgrade from our legacy package on debian buster.
This PR removes couchdb recommended dependency to ease debian buster migration

Fix deb package recommended dependencies

---

pkg/realtime/realtime_test.go
pkg/realtime/topic.go

When the realtime websocket receive the following messages:
1. Subscribe doctype
2. Watch doctype docid
3. Unwatch doctype docid
and a new event is published for this doctype, this event should be sent to the realtime websocket.

Fix a realtime issue with unwatch

---

go.mod
go.sum
pkg/appfs/server.go

When loading html, js, css, and images for a webapp or a konnector, the stack makes a call to the AppFS server. With many users and a Swift cluster, we can improve latency by using a cache.

Add cache for the Swift AppFS

---

.github/workflows/go-tests.yml
.golangci.yaml
docs/INSTALL.md
go.mod

The latest versions of some of our dependencies require Go 1.19 at least.

Remove support for Go 1.18

---

cmd/instances.go

When creating a new instance, the creation can be quite long, especially on a fresh install when installing multiple applications (on self-hosted stacks for example).
Currently, `cozy-stack`  does not output anything before the instance is fully created (or the creation fails), living the user uncertain if the command is running or not.
This PR adds a message confirming the instance is being creating and inviting the user to wait for completion.

Verbose instance creation

---

docs/accept-from-flagship.md
docs/apps.md

This PR documents the new manifest entries that should be used to make a cozy-app elligible for receiving files from the Flagship app as implemented in cozy/cozy-flagship-app#906
The OsReceive API is documented in cozy/cozy-flagship-app#987

chore: Document `accept_from_flagship` on app's manifest

---

debian/cozy-stack.postinst

When installing cozy-stack deb package, nginx is a recommended dependency.
On Ubuntu, recommended dependencies are installed by default with the package so nginx get installed with cozy-stack.
In postinstall script, we reload nginx if we find it installed but in case nginx is installed but not active (not started yet), reload fails and the whole postinst script fail, leaving cozy-stack package in an unconfigured state.
To prevent this situation, we now only reload nginx if it is active (running)

Only reload nginx if active

---

web/instances/contexts.go

When the default context has no configuration, it should still be listed with the `cozy-stack config ls-contexts` command. It has a list of registries.

Fix cozy-stack config ls-contexts

---

cmd/serve.go

Update mail config defaults to be preconfigured for sending emails on local MTA on port 25, without encryption nor authentication.
This should be suitable default for selfhosting and local dev environments

Update mail defaults for local sending

---

debian/control

By default, apt installs recommended dependencies so installing cozy-stack package ileads to nstalling nginx and postfix.
In our selfhosting documentation, we instruct to install nginx and configure email **after** cozy-stack installation.
This pull request move these recommended dependencies to suggested dependencies, which are disabled by default
It also removes dependency on debootstrap which was used to build a chroot environment for use with nsjail and is not needed anymore

Update deb package dependencies

---

worker/thumbnail/thumbnail.go

For the `cozy-stack fix thumbnails`, the 30 second timeout will apply per image, and the timeout for the whole job has been increased to 24h.

Improve the thumbnail timeout

---

debian/control

Fix PDF and SVG thumbnail creation for selfhosted using deb package

Fix PDF and SVG thumbnails creation in deb package

---

client/admin_client.go
cmd/instances.go
cmd/root.go

When adding a new instance and cozy-stack admin password has not been set in the environment variable, then it asks twice for admin password, one time to effectively create the instance and then another time to check if all required applications have been installed.
This pull request get rid of code duplication between `adminClient.NewInstanceClient()` and `newClientSafe()` and create a new client from adminClient on instance creation to avoid asking for the admin password more than once.

Avoid double admin password request on instances add

---

web/data/references_test.go
web/files/references.go

This reverts commit 21e94d28be2cc65cc23110328e82b115820cb2d1.
The hack is still needed, as some Cozy instances have references in the bogus format in production.

Revert "Remove an old hack for migration path on references"

---

model/bitwarden/cipher.go
model/sharing/revoke_trashed.go
web/auth/passphrase.go

When the passphrase of a Cozy is reset, the master password for Bitwarden is lost, and as such, the ciphers can no longer be decrypted. Thus, they are deleted from the Cozy. But, the stack should revoke the cipher sharings before deleting them to avoid deleting the ciphers on the Cozy instances of the other members.

Revoke cipher sharings on passphrase reset

---

pkg/config/config/config.go

`fs:url` config entry should be a valid url so cozy-stack fail if it is given an absolute path to a directory.
This PR makes `file://` the default `fs:url` scheme when it is omitted and the value is an absolute path (i.e. it start with a `/`)
This allow defining `fs:url` config item or `COZY_FS_URL` config env variable as an absolute path for better readability

Make file:// the default fs:url scheme

---

model/vfs/vfsafero/impl.go
model/vfs/vfsswift/impl_v3.go

When a new file is uploaded, and the stack tries to save the io.cozy.files in CouchDB, it may happen that an error occurs and the stack doesn't know if the document has been saved or not in CouchDB (timeout, network issue, CouchDB unavailable). In that case, it is safer to try to delete the document in CouchDB.
It is not perfect. For example, if CouchDB has accepted the document just before becoming unavailable, the deletion will fail (CouchDB unavailable), and it will still have an inconsistency. But, at least, it should reduce the number of cases.

Fix a source of VFS inconsistency

---

pkg/couchdb/status.go

Couchdb URL is stored in configuration struct as an URL with Path set to `/`, so it is a slash-terminated url.
When requesting status endpoint, we request CouchDB `/_up` endpoint to get CouchDB status but we add `/_up` to the configured CouchDB URL, resulting in a path starting with a double-slash.
This currently works because CouchDB http server is permissive but it is sub-optimal.
This pull request fixes that behavior by avoiding double-slash when requesting CouchDB status

Avoid double slash in couchdb status requests

---

docs/important-changes.md
pkg/crypto/pbkdf2.go
tests/system/lib/bitwarden/organization.rb
tests/system/lib/instance.rb
tests/system/lib/oauth/client.rb
web/auth/auth.go
web/auth/passphrase.go
web/middlewares/user_agent.go
web/settings/settings_test.go

The OWASP recommends at least 310,000 iterations for PBKDF2. Cf https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
We also remove the exception for lower iterations when the instance was created from Edge, as this browser now supports PBKDF2 via the subtle crypto API (the polyfill is no longer needed in production).

Increase the number of iterations for PBKDF2

---

model/oauth/client_test.go
tests/testutils/test_utils.go
web/apps/apps_test.go
web/settings/clients.go
web/settings/clients_usage_test.go
web/settings/settings_test.go

Our paywalls include a link to our premium offers so users can buy one
to unlock access to the restricted feature.
However, Apple and Google require that all purchases made from mobile
apps listed on their store be made via their In-App-Purchase feature.
This feature will only be available on future versions of our flagship
app and not on other, branded, versions so we need to check if it is
available to decide if the offers link can be displayed.

feat: No offers button on flagship app without IAP

---

pkg/i18n/i18n.go
pkg/i18n/i18n_test.go

Some localization strings include new line characters (i.e. `\n`) to
control the flow of text while avoiding the multiplication of strings
to manage (i.e. one per line).
However, these characters were not transformed into `<br />` tags by
the HTML translator thus effectively losing the expected text flow in
the resulting HTML.

feat: Transform newlines in HTML translations

---

model/sharing/member.go
model/sharing/upload.go
model/vfs/vfs.go
model/vfs/vfsafero/impl.go
model/vfs/vfsswift/impl_v3.go
tests/system/tests/sharing_moves_n_delete.rb
web/sharings/replicator.go

When two instances are on the same stack and there is a sharing between for files, the stack can optimize the share-upload worker. Before this change, the content of the file was fetched from the VFS of the source instance, then uploaded to the destination instance, which copies it to its VFS. Now, the stack just makes a copy from one VFS to the other. It's a lot lighter on I/O, and should help making the share-upload worker faster.

Optimize sharing for instances on the same stack

---

client/instances.go
model/instance/lifecycle/create.go
tests/testutils/test_utils.go
web/instances/instances.go
web/instances/instances_test.go

This would allow the cloudery to pass the instance's feature sets
directly during the creation instead of making a second request to
pass them to cozy-stack.

feat: Allow creating instances with feature sets

---

model/sharing/files.go
model/sharing/sharing.go

The regression was introduced by
https://github.com/cozy/cozy-stack/commit/0a22f21920f7f37691fd70104e9fb232489f83e9
When a single file is shared, the call to notify the end of the initial replication tries to create a sharing directory, which creates a CouchDB conflict. The fix is just checking that case to avoid creating the directory.

Fix a regression when sharing a single file

---

model/sharing/upload.go

When the share-upload worker looks for the next file to upload, it fetches the io.cozy.shared changes feed, and then gets the io.cozy.files data with a call to bulk get. In theory, the file should be present, but a race condition or an inconsistency may happen where the file has been deleted. It is better to skip this file: there is no way the stack can upload it as it has been deleted, and if we don't do that, the share-upload worker may be stuck on this file.

Improve share-upload worker stability

---

model/sharing/sharing.go

It should not report an error when a member has no instance in a sharing (except for the owner). It is expected, as the stack doesn't send the instance from the owner to the other members for privacy reasons.

Fix the cozy-stack check sharing command

---

docs/settings.md
model/cloudery/init.go
model/cloudery/service.go
model/cloudery/service_mock.go
model/cloudery/service_noop.go
model/settings/init.go
model/settings/service.go
model/settings/service_mock.go
model/settings/service_test.go
pkg/consts/consts.go
web/settings/external_ties.go
web/settings/external_ties_test.go
web/settings/settings.go

An instance can be linked to third-party services that cannot be
cancelled/unsubscribed from programmatically and require customer
actions.
We call this an external tie as these connections prevent a gracious
instance deletion and users should be made aware of these when trying
to delete their instance.
The first external tie than can exist is a blocking premium
subscription bought via the App Store or Play Store.

feat: Add external ties route

---

model/instance/instance.go
model/oauth/client.go
web/instances/instances.go

The last-activity is guessed from the web sessions and the OAuth clients. But OAuth clients can be revoked/deleted, which can lose the information. For example, if a Cozy instance has only been used with the flagship app, and the flagship app is revoked, the last-activity would be really wrong. We fix that by keeping a date on the instance for the last activity for deleted OAuth clients.

Fix last-activity when OAuth clients are deleted

---

model/sharing/setup.go

When a sharing is setup and the first replication fails, the upload trigger wasn't created.

Fix upload trigger creation

---

model/oauth/android_play_integrity.go
model/oauth/android_safety_net.go

Google was using a standard base64 for the certificate digest in the Safety Net API, buit it's now the URL-safe variant for Play Integrity.

Fix digest comparison for Play Integrity API

---

model/sharing/shared.go
model/sharing/upload.go
tests/system/lib/couch.rb
tests/system/tests/multiple_sharings.rb

It happens that the job for creating an io.cozy.shared has been lost (stack restart for example), and we need to do something to avoid having the sharing stuck. The most efficient way to do that is to check that the file is actually in the sharing directory, and if it is the case, to create the missing io.cozy.shared.

Fix sharing stuck because of a missing shared ref

---

cmd/files.go

When using `cozy-stack files exec ls` on directories, we list the content of the directory
However, when passing a file path as argument to ls, nothing is displayed.
This pull request fixes that behavior by showing the requested file when using `files exec ls` on a single file

Fix cozy-stack files exec ls on files

---

cmd/serve.go
cozy.example.yaml
docs/jobs.md
docs/workers.md
model/instance/lifecycle/magic_link.go
model/instance/lifecycle/passphrase.go
model/instance/lifecycle/two_factor_auth.go
model/session/login_history.go
model/settings/service.go
model/settings/service_test.go
model/stack/main.go
pkg/config/config/config.go
pkg/config/config/config_test.go
pkg/config/config/testdata/full_config.yaml
pkg/emailer/errors.go
pkg/emailer/init.go
pkg/emailer/service.go
pkg/emailer/service_mock.go
pkg/emailer/service_test.go
pkg/mail/mail.go
web/jobs/jobs.go
web/jobs/jobs_test.go
web/routing.go
worker/mails/mail.go
worker/mails/mail_test.go

Preserve mail server used for transactional emails from spam detection by
allowing webapps to send marketing emails via a dedicated mail server.

feat: Allow app services to send marketing emails

---

model/office/callback.go

1. An office document is shared
2. One user edits the document in OnlyOffice
3. Another user renames the file and change/remove the extension
4. The first user has finished editing the document
Here, OnlyOffice sends a callback to the stack to save the document. The stack was responding with a 500 code as the file wasn't seen as an office document. We should check that only when opening a document, not for saving it.

Fix OO save for a file without extension

---

model/feature/flag.go
model/feature/flag_test.go
worker/exec/konnector.go
worker/exec/konnector_test.go

The `harvest.skip-maintenance-for` flag can be set to a list of
konnector slugs to unlock these in Harvest and allow requesting an
execution even if it's maintenance mode has been activated either in
the registry or cozy-stack.
However, the flag was not honored in the konnector worker thus
preventing its execution.
We'll now check if the konnector to be executed is part of the list
(if set) and skip the maintenance mode when appropriate.

feat: Konnector worker honors skip-maintenance-for

---

model/note/import.go
model/note/note.go
model/office/callback.go
model/office/config.go
model/office/file_by_key.go
model/office/store.go
model/sharing/files.go
model/sharing/open_note.go
model/sharing/open_office.go
model/sharing/sharing.go
web/notes/notes.go
web/office/office.go

The `io.cozy.notes.images` documents associated with a Cozy Note are
not shared with the note itself.
Therefore, when the sharing is revoked and the note opened by the
sharing recipient on their own Cozy (i.e. shared notes are opened on
their creator's Cozy while the sharing is active), included images are
shown as missing because we can't find their associated
`io.cozy.notes.images` documents.
However, the image binaries themselves are stored wihtin the note's
binary (which is an archive in this case) and thus can be imported on
the recipient's Cozy as `io.cozy.notes.images` documents and the note
content can be updated to reference these documents.
After that, the images will be displayed as expected when opening the
note.

fix: Import notes' images from revoked sharings 

---

web/files/files.go

It happens that .odt files are uploaded as application/octet-stream (the default content-type used by browsers when they don't know better), and when it is the case, those files cannot be opened in the web Open-Office. We can do better by using the file extension.

Improve mime-type detection for uploaded files

---

model/bitwarden/oauth.go
pkg/consts/consts.go
web/bitwarden/bitwarden.go
web/bitwarden/bitwarden_test.go

It requires a new version of cozy-pass web, with some permissions added to the manifest (like com.bitwarden.folders).

Make the bitwarden OAuth clients linked to cozy-pass web

---

model/app/konnector.go
tests/testutils/test_utils.go
web/apps/apps.go
web/apps/apps_test.go

When sending logs from client side konnector, let's set the worker_id to client. Like that, it's easier to monitor those konnectors.
Cozy-Stack already add this information when updating the job status.

feat: Log worker_id client

---

model/vfs/cozy_metadata.go
pkg/consts/doctype.go
pkg/metadata/metadata.go
worker/exec/konnector.go
worker/exec/konnector_test.go

When the stack executes a konnector that imports files, it checks that a directory exists for those files. And if the directory doesn't exist, it creates it. We have added a referencedBy on the directory for the sourceAccountIdentifier to be able to deal with several accounts for the same konnector, as each account should have its own directory.

Add a reference to sourceAccountIdentifier

---

model/sharing/error.go
model/sharing/group.go
model/sharing/member.go
web/sharings/sharings.go

If we try to add a group to a sharing, and this group contains a contact that aleady is on the sharing with different rights (read-only vs read-write), we should abort.

Check if a group can be added to a sharing

---

model/instance/init.go
model/instance/lifecycle/create.go
model/instance/lifecycle/destroy.go
model/instance/lifecycle/get.go
model/instance/lifecycle/helpers.go
model/instance/service.go
model/instance/service_mock.go
model/stack/main.go
web/auth/auth_test.go
web/instances/instances.go
worker/migrations/migrate-accounts-to-organisation.go
worker/migrations/migrations.go
worker/moves/workers.go

It looks like the interactions between the eventual consistency of CouchDB and the Redis cache for instances can trigger 409 conflict errors for several minutes.

Remove cache for instances

---

model/cloudery/init.go
model/cloudery/service.go
model/cloudery/service_mock.go
model/cloudery/service_noop.go
model/settings/service.go
model/settings/service_test.go
web/settings/external_ties_test.go

When a blocking subscription exists (e.g. an In-App-Purchase
subscription), we want to know which vendor was used to buy it so we
can display this information in the UI (instead of listing all
possible vendors which can irritate some of them like Apple).
Since we start returning more information about the blocking
subscription we'll return it as an object in the
`blocking_subscription` field of the external ties JSON response.
We could then remove the `has_blocking_subscription` field once
apps using this route rely solely on the new field.

feat: Add subscription vendor to external ties

---

model/move/cursor.go
pkg/couchdb/bulk.go

It was working, but relying on a bug of CouchDB, which may be fixed in later versions. Let's use a safer version with `startkey` and `endkey`.

Avoid using startkey_docid in _all_docs

---

model/sharing/member.go

When a group is added in read-only to a sharing, it is no longer possible to add an individual who is a member of this group in read-write for this sharing.

Fix sharing with different modes

---

pkg/safehttp/client.go

Safehttp package is used to prevent Server-Side Requests Forgery. It prevents making HTTP requests to private IP addresses for things controlled by the user, like Bitwarden icons. This commit adds some more rules for link-local unicast and multicast.
Fix #4380

Forbid IP like 169.254.169.254 in safehttp

---

web/apps/serve.go

When an instance has more connected OAuth clients than their current
plan and options allows them to, we redirect them to a paywall from
any web app except the Settings app (because it allows disconnecting
clients).
However, if the user is not logged in, the paywall will return an
unauthorized error.
Therefore, we'll make sure the redirection to the paywall only occurs
when the user is logged in (we don't duplicate the logic to redirect
them to the login page in the paywall middleware).

fix: Redirect to clients paywall only if logged in

---

.github/workflows/release.yml
scripts/packaging/docker_package.sh

Ubuntu 24.04 Noble Numbat has been released on April 25, 2024.
This PR adds releases packages for Ubuntu 24.04 Noble Numbat.

Build packages for Ubuntu 24.04 Noble Numbat

---

.github/workflows/release.yml

This pull request add an actions workflow step to trigger selfhosting debian repo update after all packages for a new release have been published

Publish release packages to selfhost debian repo

---

docs/nextcloud.md
model/nextcloud/nextcloud.go
pkg/webdav/webdav.go
web/remote/nextcloud.go

The HTTP request to NextCloud was made with Transfer-Encoding: chunked, because of the way the Content-Length was set. But it looks like NextCloud doesn't support that, and files were created empty. We can avoid that by setting request.ContentLength.

Fix uploading files to NextCloud via WebDAV

---

assets/locales/de.po
assets/locales/en.po
assets/locales/es.po
assets/locales/fr.po
assets/locales/ja.po
assets/locales/nl_NL.po
docs/files.md

The product has decided to change the name of the folder. I'm going to force it on the cozy-drive side, but I'm thinking that to keep consistency into Desktop, we'd better change the translation here.

[VO-848] feat: Rename Shared drives into Drives

---

assets/mails/new_connection.text

We did remove the OS from the new connexion email in https://github.com/cozy/cozy-stack/commit/9eae458822bd016c833480b377e58a0509353959 but forgot to remove it from the text version of the message.

Remove OS in new connection emails

---

cozy.example.yaml

When running the stack after copying the default configuration file, the stack won't start because of errors due to fake paths defined for firebase and encryption.
Let's comment them to ease incoming developers' life.

Make the stack runnable from default config

---

scripts/konnector-nsjail-node-run.sh

Some node modules as indirect dependencies rely on HOME variable to be set.
If HOME env variable is not set, the konnector fail with the following message:
```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
```
Defining this variable make the konnector happy

Define HOME variable inside konnector jail

---

model/contact/contacts.go

- add the displayName
- add the index.byFamilyNameGivenNameEmailCozyUrl
In theory, there is a service from the contacts webapp that adds them, launched via an `@vevent` trigger on the io.cozy.contacts. But, the stack creates the myself contact before installing the contacts webapp at instance creation. Thus, the service is not launched. The easy fix is to just add the missing field when creating the myself contact.

Fix the myself contact at instance creation

---

model/instance/instance_test.go
model/instance/manager.go
model/oauth/client_test.go
pkg/config/config/config.go
pkg/config/config/config_test.go
pkg/config/config/testdata/full_config.yaml
tests/testutils/test_utils.go
web/apps/apps_test.go
web/auth/confirm.go
web/settings/context.go
web/settings/settings_test.go

We used to store the manager url in the context config in the
`manager_url` attribute.
We're now storing it as part of the `clouderies` config so we can
remove the old attribute and its use.
However, some clients still make use of the old context attribute so
we're adding it back in the context API response for backwards
compatibility.

fix: Remove duplicated manager url config

---

pkg/couchdb/couchdb.go

Golang can reuse HTTP connections with keep alive, but the response body must have been fully read and closed. In the couchdb package, we were reading the body for sucessful response with a json.Decoder. It only reads a JSON value, and most responses from CouchDB have an additional \n after that JSON value. This last byte was not read from the response body, and it prevents Golang from reusing the connection. So, we are doing a new HTTP connection (with DNS resolution and TLS handshake) for each request to CouchDB.

Fix HTTP keep-alive for CouchDB connections

---

cozy.example.yaml

The example config should not contain elements such as URLs from our
production environment as people might simply copy the file without
changing some parts and end up making unnecessary requests to our
servers.

tech: Cleanup example config from prod elements

---

model/sharing/invitation.go
tests/system/nextcloud/before-starting/create-account.sh
tests/system/tests/webdav_nextcloud.rb

The flagship app doesn't support links to an external Cozy in a push notification currently. So, let's send the user to the list of their sharings for the moment.

Fix redirectLink for sharings push notification

---

web/instances/instances.go

When calling the admin route
/instances/:domain/sharings/:id/unxor/:doc-id for a sharing where the XorID is missing in the credential, we should return an error instead of a panic.

Fix a panic with invalid sharing

---

.github/workflows/assets.yml
.github/workflows/cli.yml
.github/workflows/go-lint.yml
.github/workflows/go-tests.yml
.github/workflows/release.yml
.github/workflows/system-tests.yml
.golangci.yaml
Makefile
docs/docker.md
pkg/i18n/i18n.go
scripts/packaging/installrequirements.sh

- Use go 1.24 for CI where 1.23 was used
- Update golangci-lint (and removes a deprecated linter, tenv)
- Remove packaging for Ubuntu 20.04 (no longer supported by GitHub Actions)

Update to Go 1.24

---

model/vfs/vfsafero/avatar.go
web/settings/settings_test.go

Fix avatar creation when no thumbnails have been created before. The avatar is persisted in the same directory than thumbnails for Afero VFS, and this directory needs to be created.

Create root directory before saving avatar

---

model/permission/permissions.go

We don't see any reason why share links could not be created with CLI
tokens and this is necessary for the Twake Drive migration.
We might want to allow updating share link permissions with CLI tokens
as well but since it's not required for the moment we'll discuss it
later.

feat: Allow creating share links with CLI tokens

---

docs/sharing.md
web/sharings/sharings.go

A `shared_docs` param is added to the GET `/sharings/doctype` route, in order for the client to tell whether or not the `shared_docs` relationships is required in the response, as this can be costful in case of sharings with a lot of documents.

Add shared_docs param

---

client/instances.go
cmd/instances.go
docs/cli/cozy-stack_instances_add.md
docs/cli/cozy-stack_instances_modify.md
model/instance/instance.go
model/instance/lifecycle/create.go
model/instance/lifecycle/patch.go
pkg/couchdb/index.go
web/instances/instances.go
web/middlewares/instance.go
web/routing.go

For the migration from Cozy to Twake Workplace, we need a way to redirect from the old domains to the new ones. So, an old domain field was added to the Cozy instances, and the stack will do the redirections from the old domains to the new ones. It works for the API endpoint, but also for the apps pages (eg old.mycozy.cloud -> new.twake.app).
The old domain of a Cozy instance can be set with the `cozy-stack instances modify` command, or directly by modifying the `old_domain` field of the CouchDB document of the instance in the global database.

Add an old domain field to Cozy instances

---

model/settings/common/common.go

after creating the common settings we should not continue to perform the update query

🐛 fix(common-settings update): return after creating the common-settings

---

docs/delegated-auth.md
web/oidc/oidc.go

In order to have the same behavior as the previous route `/connect/token` we need to check that the passphrase is OK.

fix: We need to check PassPhrase
