doc/architecture.md, doc/files.md
@aenario it's work in progress but don't hesitate to tell me what you think of it
=> Documentation about the files service

main.go
Initialize Cobra as per the `README.md`, which handles a potential error in the `RootCmd`.  
Src: https://github.com/spf13/cobra#getting-started
=> Handle error when running the root command

.gitignore, docs/files.md, web/files/files.go, web/files/upload_test.go, web/jsonapi/jsonapi.go, web/middlewares/instance.go, web/middlewares/instance_test.go, web/router.go, web/status/status_test.go
@aenario it's not finished (far from it) but I will wait your work on couchdb to continue it. Don't worry I have many other things to do, so no pressure on you. I've just thought that you may want to read my code
=> [WIP] Uploading a file

web/files/files.go, web/files/files_test.go
See: #26 
Missed @nono comments.
=> [WIP] Create directory (bis)

couchdb/errors.go, couchdb/errors_test.go
=> Fix status conversion in Couchdb Error (bis)

couchdb/couchdb.go, couchdb/couchdb_test.go, web/data/data.go, web/data/data_test.go
=> Add couchdb & HTTP API for update & delete

web/files/file.go, web/files/files.go, web/files/files_test.go
This PR add the API to download a file by id and path:
- `GET /files/:file-id`
- `GET /files/download?path=`
I started by implementing a simple `io.Copy` streaming (8d234b0ed1c8772dc4fc2a7f5d47d8d9662d372d) and finally decided to use `http.ServeContent`. It allowed me to add support `Range`, `If-Modified-Since` and `If-None-Match` headers.
I'm just checking you're all OK with that before updating the documentation to reflect these possibilities.
=> [VFS] Download files

vfs/directory.go, vfs/file.go, web/files/files.go, web/files/files_test.go, web/jsonapi/data.go, web/jsonapi/errors.go, web/jsonapi/jsonapi.go, web/jsonapi/jsonapi_test.go
It should be enough for the files API (serialization only, unmarshalling in a future PR).
=> JSON-API serialization

apps/apps.go, couchdb/mango/query.go, web/apps/apps.go, web/files/files_test.go, web/jsonapi/jsonapi.go
Introduces the `GET /apps/` endpoint.
Added `jsonapi.DataList` to marshal list of `jsonapi.Object`.
=> [APPS] Add listing of applications

.gitignore, cmd/instance.go, cmd/root.go, config/config.go, config/config_test.go, couchdb/couchdb.go, cozy.dist.yaml, docs/config.md
This PR adds [`github.com/Sirupsen/logrus`](http://github.com/Sirupsen/logrus).
A `--log-level` option can be used to change the logger level. No more option for now.
=> Add simple logging with logrus

cmd/instance.go, instance/instance.go
I wanted to list the instances on my PC and hacked this
=> Add a command to list instances

cmd/instance.go, couchdb/couchdb.go, instance/instance.go, instance/instance_test.go, web/data/data_test.go, web/files/files_test.go
This PR add a command to remove an instance and all its content.
It also fixes a issue that allowed to create multiple instances with the same domain.
=> Add instances remove

couchdb/couchdb.go, couchdb/couchdb_test.go
The `POST _all_docs` does not provide what I was thinking. I added a test on `GetAllDocs`.
=> Fex GetAllDocs using GET method

apps/apps.go, couchdb/errors.go, instance/instance.go, vfs/directory.go, vfs/file.go, vfs/rand_suffix.go, vfs/vfs.go, vfs/vfs_test.go, web/apps/apps.go, web/apps/apps_test.go, web/files/files.go, web/files/files_test.go
This PR adds the possibility to move file and directories to the trash. It simply move them on a special trash directory for now. I have not added anything more for now to handle file recovery.
It still requires more tests, but it is ready for review.
=> [VFS] Allow to move file or dir to trash

.travis.yml, vfs/directory.go, vfs/errors.go, vfs/file.go, web/files/files.go, web/files/files_test.go
This PR also remove the possibility to modify the root and trash folders.
=> Return error when trying to delete a file in trash

docs/onboarding.md
We finally went with `/register` for password creation.
=> Fix onboarding doc

.travis.yml, README.md, build.sh, coverage.sh
Note: go test with coverage works only on one package at a time. So we have to iterate on te packages and launch go test, end then concatenate the coverages.
=> Code coverage with codecov.io

scripts/Dockerfile, scripts/cozy-app-dev.sh
Add a `-f` option to the dev script in order to specify the `--fs-url` option of cozy-stack.
=> Add possibility to specify fs-url in dev script

web/files/files.go
`PATCH /files/metadata` was broken because of the way echo works.
I splitted the code in two handlers for `PATCH /files/metadata` and `PATCH /files/:file-id` which I think is cleaner.
=> Split handlers PATCH handlers by path and by ID

scripts/build.sh
Also update the usage message to add `deploy` and `clean` commands.
=> build.sh: delete binaries after deploy and quote vars

docs/client-app-dev.md, scripts/Dockerfile
Now that the image is published, I updated the doc to make it run propoerly (with the -t flag). I also installed bash in the Dockerfile.
=> Update doc on docker dev

docs/auth.md, web/auth/auth.go, web/auth/auth_test.go, web/auth/client.go
It includes the commits from #187
=> Oauth delete client

web/auth/auth_test.go
See https://github.com/labstack/echo/commit/412823eabb0f1e4c0b93fcf7a26232099469938d
=> Fix build, CSRF error message has changed in echo

web/middlewares/cors.go, web/middlewares/cors_test.go, web/routing/routing.go
This allows us to support credentials from non-determined URLs.
=> Replace echo CORS by custom one

pkg/instance/instance.go
Warning: This make it not retro-compatible with old registered instances.
=> Use snake_case everywhere for json

pkg/utils/utils.go, pkg/utils/utils_test.go
It's a start to improve our coverage ratio!
=> Add tests for the utils package

scripts/build.sh
...otherwise I get " file "../statik/statik.go" already exists"
=> Remove statik.go before executing go generate

docs/files.md
=> Add root directory section to Files API doc

docs/data-system.md, web/data/data.go, web/data/data_test.go
The `POST _all_docs` works, but it's better to also have `GET _all_docs` for when we will have permissions on /data.
=> Add GET _all_docs

pkg/jobs/mem_jobs_test.go, pkg/jobs/worker.go
Recover in case a worker function does panic.
=> Handle workers that may panic

docs/client-app-dev.md
The VFS was not persisted with the suggest command, so I add the relevant folder to sync to it. Thanks @jinroh for the tip!
=> Add VFS data persistence to dev doc

cmd/files.go, pkg/apps/git.go, pkg/apps/installer.go, pkg/couchdb/couchdb.go, pkg/instance/instance.go, pkg/vfs/directory.go, pkg/vfs/file.go, pkg/vfs/rand_suffix.go, pkg/vfs/vfs.go, web/files/files.go, web/middlewares/middlewares.go
See https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters
=> Be explicit with return values

docs/settings.md, pkg/oauth/client.go, web/data/permissions.go, web/permissions/permissions.go, web/settings/clients.go, web/settings/settings.go, web/settings/settings_test.go
=> Revoke OAuth2 client

cmd/root.go, cozy.dist.yaml, docs/client-app-dev.md, pkg/config/config.go, pkg/config/config_test.go, scripts/Dockerfile, scripts/cozy-app-dev.sh
- It binds cozy-stack on 0.0.0.0 inside the docker (it fixes issues in some configurations of docker)
- It uses an URL for configuring CouchDB (it allows to use https and credentials).
=> Improve docker image and couchdb configuration

cmd/cmd_test.go, cmd/files.go, pkg/instance/instance.go, pkg/permissions/claims.go, pkg/permissions/rule.go, pkg/permissions/validation.go, pkg/vfs/archive.go, pkg/vfs/permissions.go, pkg/vfs/permissions_test.go, web/files/files.go, web/files/files_test.go, web/files/permissions_test.go, web/files/referencedby.go, web/files/referencedby_test.go, web/permissions/permissions.go
Still lacking some test but reviewable
=> Add permissions to /files

docs/sharing.md, pkg/sharings/sharings.go
This mainly describes how to make a POST on the /sharings/ route. 
It also fix few things in the documentation, and correct a link in the code.
=> Add sharing documentation

client/apps.go, docs/cli/cozy-stack.md, docs/cli/cozy-stack_apps.md, docs/cli/cozy-stack_apps_install.md, docs/cli/cozy-stack_apps_update.md, docs/cli/cozy-stack_bug.md, docs/cli/cozy-stack_completion.md, docs/cli/cozy-stack_config.md, docs/cli/cozy-stack_config_passwd.md, docs/cli/cozy-stack_config_print.md, docs/cli/cozy-stack_doc.md, docs/cli/cozy-stack_doc_man.md, docs/cli/cozy-stack_files.md, docs/cli/cozy-stack_files_exec.md, docs/cli/cozy-stack_files_import.md, docs/cli/cozy-stack_instances.md, docs/cli/cozy-stack_instances_add.md, docs/cli/cozy-stack_instances_client-oauth.md, docs/cli/cozy-stack_instances_destroy.md, docs/cli/cozy-stack_instances_ls.md, docs/cli/cozy-stack_instances_token-app.md, docs/cli/cozy-stack_instances_token-oauth.md, docs/cli/cozy-stack_serve.md, docs/cli/cozy-stack_status.md, web/data/data_test.go
Oops, I've merged #330 too soon
=> Fixes after #330

docs/konnectors.md
Here is the konnector install and execution description.
=> Konnectors installation description

client/apps.go, cmd/apps.go, pkg/apps/installer.go, pkg/apps/installer_test.go, pkg/vfs/vfs.go, pkg/vfs/vfs_test.go, web/apps/apps.go
This PR adds the possibility to remove/uninstall an application from the HTTP API and CLI.
Tests are on there way.
=> Apps: uninstall

pkg/consts/consts.go, web/auth/auth.go
Cf https://github.com/cozy/cozy-stack/blob/master/docs/onboarding.md#flow-example
=> Redirect / to onboarding when the user has no passphrase yet

cozy.example.yaml, pkg/config/config.go
depends on https://github.com/cozy/gomail/pull/3
=> Add support for SkipCertificateValidation option

README.md, cmd/apps.go, cmd/instances.go, docs/CONTRIBUTING.md, docs/INSTALL.md, docs/README.md, docs/cli/cozy-stack_apps_install.md, docs/cli/cozy-stack_instances_add.md
- Give some more examples of CLI usage
- Update the README
- Add an install guide
=> The usual docs update

client/auth/auth.go
This fixes the `access_token` request in the OAuth client.
=> Fix access_token request

docs/jobs.md, pkg/couchdb/couchdb.go, pkg/couchdb/couchdb_test.go, pkg/jobs/trigger_event.go, pkg/jobs/trigger_event_test.go, pkg/permissions/verbs.go, pkg/realtime/memhub.go, pkg/realtime/realtime.go, pkg/realtime/realtime_test.go, web/data/data.go, web/data/permissions.go
Turns out we dont currently support Couchdb -> Stack replication, so we dont have couchdb.Proxy routes that write data...
=> Add realtime to couchdb package

pkg/config/config_test.go
More test on pkg/config (following issues on #415)
=> Add tests on pkg/config Setup method

pkg/permissions/permissions.go
=> Add a workaround for installing apps with a cluster of couch

docs/apps.md, docs/intents.md, pkg/apps/apps_test.go, pkg/intents/intents.go, pkg/intents/intents_test.go, web/apps/apps_test.go, web/apps/serve.go, web/auth/auth.go, web/middlewares/middlewares.go, web/middlewares/middlewares_test.go, web/middlewares/secure.go, web/middlewares/secure_test.go, web/routing.go
=> Allow to open iframes for intents

client/client.go, cmd/files.go, pkg/apps/installer_test.go, pkg/instance/instance.go, pkg/vfs/couchdb_indexer.go, pkg/vfs/directory.go, pkg/vfs/file.go, pkg/vfs/mem_lock.go, pkg/vfs/permissions.go, pkg/vfs/vfs.go, pkg/vfs/vfs_test.go, pkg/vfs/vfsafero/impl.go, pkg/vfs/vfsswift/impl.go, web/routing.go
This PR introduces a global RW lock on the VFS to make concurrent access to the files deterministic.
=> VFS locking

docs/konnectors.md, docs/konnectors_design.md
This new field will allow the my accounts application to get the list of fields to display for each konnector
=> New "fields" field in manifest.konnector

tests/pouchdb-integration/package.json, tests/pouchdb-integration/tests.js
I hope it will help to fix failures like https://travis-ci.org/cozy/cozy-stack/jobs/218800988#L1601
=> Remove some JS dependencies

pkg/sharings/send_mails.go
When trying to send mail not just after the creation of a sharing,
documents are fetched from the database. Private fields are not
populated so they have to be fetched manually.
This PR fixes a mistake of that kind in the "send_mails.go" file.
=> Fix send mails

docs/konnectors_workflow_example.md
The aims of this doc is to describe the whole (future) API necessary to get started client side with konnectors.
Requiring reviews from the Plateformers : 
@doubleface 
@gregorylegarec 
Let me know if you need more information, if some thing is not clear and so on!
=> Docs konnectors

docs/konnectors_oauth.md
This is stil a work in progress, opinions welcome.
=> Add docs on oauth for konnectors

web/files/paginated.go, web/files/pagination_test.go, web/jsonapi/data.go, web/jsonapi/jsonapi.go
=> Fix meta is missing in relationships when count is 0

pkg/vfs/metadata.go
This is a temporary bandaid so @GoOz can work on PHO-18.
=> Default image metada to now

scripts/docker-entrypoint.sh
=> Docker: fix apps warning when using multi-apps

pkg/scheduler/mem_scheduler.go, pkg/scheduler/redis_scheduler.go, pkg/scheduler/redis_scheduler_test.go, pkg/scheduler/scheduler.go
I'll write documentation and make another PR with it
=> Add cron triggers with multi-stack, via redis

assets/externals
Yes again, sorry for the inconvenience but i didn't saw the bug coming 😕
=> chore: update cozy-bar to 3.0.0-beta21

docs/jobs.md, pkg/couchdb/couchdb.go, pkg/jobs/errors.go, pkg/jobs/jobs.go, pkg/jobs/mem_jobs.go, pkg/jobs/mem_jobs_test.go, pkg/jobs/store.go, pkg/jobs/worker.go, web/jobs/jobs.go, web/jobs/jobs_test.go
Add a `GET /jobs/:job-id` method to be able to poll the result of the job and see if it as succeeded or not.
=> Store jobs in couchdb

pkg/accounts/type.go, web/konnectorsauth/oauth.go, web/konnectorsauth/oauth_test.go
=> Add support for implicit grant flow

assets/externals
=> Update cozy-bar to v3.0.0-beta24

assets/externals
=> chore: update cozy-bar version

pkg/apps/copier.go, pkg/apps/server.go, pkg/config/config.go, pkg/config/swift.go, pkg/instance/instance.go, pkg/stack/main.go, pkg/vfs/vfs_test.go, pkg/vfs/vfsswift/impl.go, web/server.go
This PR actually plug the support for swift as the application storage for webapps and konnectors.
=> Plug swift for apps storage

pkg/consts/consts.go, web/konnectorsauth/oauth.go, web/konnectorsauth/oauth_test.go, web/permissions/allow.go
See https://github.com/cozy/cozy-data-connect/pull/60
=> Rename Cozy Data Connect in Cozy Collect

imexport/oauth.go
Travail en cours avec beaucoup de valeurs en dur pour l'instant. Il y aura des améliorations au fur et à mesure
=> client oauth

docs/workers.md, pkg/workers/mails/mail.go
I'd like to send the logs of cozy-desktop to the support as an attachment, via the sendmail worker
=> Add attachments for email worker

pkg/config/config.go, pkg/config/swift.go, pkg/instance/instance.go, pkg/vfs/vfsswift/impl.go
Also fix the non-namespaced logs for the packages `pkg/vfs/vfsswift` and `pkg/config`.
=> Log when passphrase reset is ignored

.gitignore, pkg/accounts/type.go, web/konnectorsauth/oauth.go, web/konnectorsauth/statestore.go
Add the notion of Nonce, used by some oauth implementations.
This required some moving of code around.
=> Support more oauth types

pkg/workers/sharings/share_data.go
In #675 a "refresh token" check was missing as well as a `parseError`.
=> fix: missing refresh token

pkg/apps/apps.go, pkg/apps/installer.go, pkg/apps/konnector.go, pkg/apps/webapp.go, pkg/couchdb/couchdb.go
Also increase the couchdb timeout.
=> Take the last update time into account to check app state

assets/locales/fr.po, assets/styles/stack.css, assets/templates/authorize.html, assets/templates/authorize_app.html
Permissions are now responsive and mobile compliant
Permissions list are not quite different for now, waiting for a bunch of icons but as it can't really wait, let's merge it like this, everything is just prepared but not used.
=> feat: Add responsiveness + a little better permissions list

assets/locales/en.po, assets/locales/fr.po, assets/styles/stack.css, assets/templates/authorize.html
=> feat: Add style for link and add link to CGU

client/files.go, cmd/fixer.go, cmd/instances.go, pkg/vfs/file.go, pkg/vfs/vfs.go
For instances with the #641 issue.
=> Add command to fix missing md5 in some files

assets/externals
`cozy-bar.min.css` did not change.
=> chore: update cozy-bar :arrow_up:

assets/externals
Update Cozy-bar to 3.0.0-beta29
=> chore: update Cozy-bar

pkg/workers/thumbnail/thumbnail.go
We have some uploaded photos that don't have thumbnails. From the logs, I think it's possible we try too soon, while the image is still uploading (since https://github.com/cozy/cozy-stack/pull/697, the document is created in couch at the beginning of the upload). What do you think?
=> Avoid trying to generate thumbnails for an image still uploading

pkg/imexport/export.go, web/imexport/imexport.go, web/routing.go
I've reworked the PR #732 made by @AylinKocoglu
=> Add the /export route

cozy.example.yaml
Ping @nledez and @jsilvestre for information.
=> doc: adds coming soon example in cozy.example.yaml :books:

web/sharings/files.go
Some permissions check were missing for the sharing
=> Add permissions check

assets/externals
=> chore: upgrade Cozy Bar to v3.0.1 :arrow_up:

pkg/consts/consts.go, pkg/sharings/recipients.go, pkg/sharings/send_mails.go, pkg/sharings/send_mails_test.go, pkg/sharings/sharings.go, pkg/sharings/sharings_test.go, pkg/workers/sharings/sharing_updates.go, web/data/permissions.go
* Migrate the recipient doctype to `io.cozy.contacts`
* Check the recipient mail exist
=> Use contacts as sharing recipients

scripts/konnector-node-run.sh
This script will help developpers which may have problems installing rocket/nsjail in their environment.
Only for development purpose.
=> feat: allow the stack to run a konnector using node directly

cozy.example.yaml
Induced by PR #788 by @doubleface.
=> Update cozy.example.yaml with node script for konnectors

pkg/workers/mails/mail_templates.go
The first two are just improvements. The whole area was not clickable on every email clients.
The last one is a fix, as forms are forbidden in most email clients.
=> fix: emails buttons were not fully clickable

.travis.yml
And it makes the travis web interfaces lag
=> Couchdb logs are way too long to be useful on travis

pkg/scheduler/convert_test.go, pkg/scheduler/redis_scheduler.go
The conversion was breaking : the stack would not stack in integration with it. 
I added tests but cant identify the cause. @nledez 
I might need help for debuging when this goes to int. let's do it on monday.
=> Scheduler convert

web/sharings/sharings.go, web/sharings/sharings_test.go
This enforce a permission check at the sharing creation and revocation.
It makes sure that the defined sharing permissions are a subset of the requester permissions.
=> Enforce sharing permissions

web/konnectorsauth/oauth.go, web/konnectorsauth/oauth_test.go
This PR should allows supporting "normal" oauth provider by registering each stack as a Oauth Client.
=> Oauth redirect from state

assets/locales/en.po, assets/locales/fr.po, assets/templates/sharing_discovery.html, web/sharings/sharings.go
This shows an error mesage below the sharing discovery form, in case the entered URL is incorrect, i.e. the sharer is unable to register.
=> Discovery error message

assets/locales/en.po, assets/locales/fr.po, assets/styles/stack.css
I changed the french and english po files but I am not sur if it works with transifex for the other locales. What should I do?
=> fix: now use one doctype for all types of sinistres

pkg/sharings/sharings.go, pkg/workers/sharings/share_data.go, pkg/workers/sharings/share_data_test.go, pkg/workers/sharings/sharing_updates.go, pkg/workers/sharings/sharing_updates_test.go, web/files/files.go, web/files/files_test.go, web/sharings/files.go, web/sharings/sharings_test.go
This supports the following features:
It doesn't support yet:
- [ ] Change of path for files
=> Handle sharing directory

pkg/sharings/sharings.go, pkg/sharings/sharings_test.go
This fixes the sharing revocation requests
=> Fix revocation requests

pkg/sharings/sharings.go, pkg/workers/sharings/share_data.go, pkg/workers/sharings/sharing_updates.go
This basically consists of moving functions from `workers/sharings` to `pkg/sharings`
=> Deal with refresh token for revocation requests

pkg/consts/consts.go, pkg/couchdb/couchdb.go, pkg/jobs/worker.go, pkg/workers/konnectors/konnector.go
=> [feat] save konnector logs

tests/testutils/test_utils.go, web/auth/auth_test.go, web/permissions/extract.go, web/settings/settings_test.go
This PR allow to extract permissions to the API even if the user is not registered.
=> Allow to generate permissions even when not registered

pkg/workers/sharings/sharing_updates.go
The auto revocation is triggered when a recipient removes the object of the sharing, e.g. a directory or a photo album. This behaviour was badly handled and resulted in unexpected revocations; this PR fixes that.
=> Fix auto revocation

cmd/fixer.go, cmd/instances.go, pkg/couchdb/couchdb.go, pkg/instance/instance.go, pkg/scheduler/mem_scheduler.go, pkg/scheduler/redis_scheduler.go, web/jobs/jobs.go
This PR also adds a `couchdb.ForeachDocs` method to iterate over all the document of a couchdb database.
=> Introduce a jobs fixer command to fix stalled job

web/server.go
see https://github.com/google/gops/blob/b0c5c02b30c5a0eab10869d14a3238be15a7f4a5/agent/agent.go#L127-L136
=> Remove google/gops graceful shutdown as it breaks our

pkg/consts/consts.go, pkg/notifications/errors.go, pkg/notifications/notifications.go, web/data/permissions.go, web/files/files.go, web/notifications/notifications.go, web/permissions/allow.go, web/permissions/extract.go, web/routing.go
This PR lays the foundations for the notifications service by adding a route to create a notification into database.
=> Add notification creation route

web/files/files.go
=> Add rev check to destroy handler

docs/account_types.md, docs/konnectors_oauth.md
We still need to figure out how these will be provisioned in infra
=> Add account_types sample for google

appveyor.yml, cmd/serve.go, pkg/instance/instance.go, pkg/instance/posix.go, pkg/instance/windows.go, pkg/logger/logger.go, pkg/logger/syslog.go, pkg/logger/syslog_stub.go, pkg/vfs/vfsafero/impl.go
This could be a first step to run the cozy-stack on Windows.
Benefits:
- Run all the cozy-desktop tests on AppVeyor
- Develop Cozy Apps on every Windows versions
Next steps could be:
I would prefer to address those points in future PR.
WDYT?
=> Windows build

cmd/serve.go, docs/cli/cozy-stack_serve.md, pkg/config/config.go, web/routing.go
=> Add a --disable-csp flag for development

cmd/apps.go, cmd/files.go, cmd/settings.go, docs/config.md
=> Use COZY_DOMAIN env variable in the CLI

docs/apps.md, pkg/apps/fetcher_file.go, pkg/apps/installer.go
This PR adds the possibility to install/update an application from a local directory. It should be useful in development to install applications with services associated.
=> Add support for file:// scheme to install application locally

pkg/apps/webapp.go, pkg/jobs/redis_jobs.go
This PR fixes the update of services when upgrading the applications multiple times.
cc @kosssi
=> Fix services copy on update

docs/konnectors_workflow_example.md, pkg/workers/exec/konnector.go, pkg/workers/exec/service.go
=> Add env variable COZY_LOCALE to konnectors and services

pkg/apps/webapp.go, pkg/workers/exec/service.go
Also add support to the `debounce` parameter.
=> Fix service execution when launched via @event

pkg/accounts/type.go
Support for new refresh_token mechanism from well known provider.
=> Refresh refresh_token

cozy.example.yaml, docs/registry-publish.md, docs/registry.md, pkg/config/config.go
Documentation and script example to automate the publishing of an application on a registry.
=> Registry publish

assets/externals
Fixes a bug with long app titles
=> Upgrade the cozy bar to v4.2.1

assets/externals
Disables the search bar until further work.
=> Update cozy-bar to v4.2.3

docs/konnectors.md, docs/konnectors_design.md, docs/konnectors_workflow_example.md, docs/registry-publish.md, pkg/apps/konnector.go, pkg/workers/exec/konnector.go, scripts/konnector-nsjail-run.sh, scripts/konnector-rkt-run.sh
This PR adds the possibility to specify a specific parameter in the manifest of a konnector that will be sent to the konnector on its execution in the `COZY_PARAMETERS` environment variable.
=> Konnectors flavor and parameters

pkg/stack/main.go
=> Increase attempts at connecting to couchdb at startup

cmd/serve.go, scripts/build.sh, scripts/cozy-app-dev.sh, web/routing.go, web/server.go
Few cosmetic changes to hide the banner from echo and changing the output of the `cozy-stack serve` command.
=> Hide banners from echo

cmd/apps.go
The handling of accounts is hardcoded into the command since it will change soon enough when adding support for multiple accounts.
=> Checkout the account when using konnectors run command

pkg/accounts/accounts.go, pkg/accounts/type.go, web/konnectorsauth/oauth.go
=> Konnector oauth

pkg/sessions/login_history.go, pkg/workers/exec/konnector.go
This reverts commit f640de30be32ad9c8890d1c0f5d57801c7f65f0d.
=> Revert "Disable alerts by email"

docs/registry-publish.md
=> fix: broken link

pkg/instance/posix.go
Fix needed with the one from #1046
=> Fix building cozy-stack on FreeBSD, again

assets/externals
- Fixes bad UI on bank
https://github.com/cozy/cozy-bar/pull/133
=> chore: update bar version

assets/styles/login.css, assets/styles/stack.css
Added some prefixed CSS so it's not broken on some "not so old" browsers.
=> fix: Add prefixed CSS to support iOS 7

assets/externals
https://github.com/cozy/cozy-client-js/releases/tag/v0.4.3
=> update cozy-client-js to v0.4.3

pkg/consts/consts.go, web/data/permissions.go, web/jobs/jobs.go
Adds a `/jobs/triggers/:trigger-id/state` route with a new doctype: `io.cozy.trigger.state`
=> Route to fetch trigger state

docs/sharing.md, pkg/sharings/sharings.go, web/sharings/sharings.go, web/sharings/sharings_test.go
~~To be merged after #1082~~ it can be merged now!
=> Enable to add a recipient to a sharing

docs/notifications.md, pkg/notifications/notifications.go
=> Add created_at for notifications

pkg/workers/mails/mail.go, pkg/workers/mails/mail_test.go
=> Add cozy domain as X-Cozy in mail headers

assets/locales/en.po, assets/templates/sharing_discovery.html
Tips and tricks for users receiving a sharing email but who don't know what is going on.
=> update sharing discovery page

cmd/settings.go
=> Sort instance settings in CLI

pkg/scheduler/redis_scheduler.go
The debounced trigger worked fine the first time, and then was never removed from `scheduling`. So, it was executed every 10 seconds.
Fix #1120
=> Fix debounced event triggers

pkg/crypto/scrypt.go, pkg/crypto/scrypt_test.go
See https://blog.filippo.io/the-scrypt-parameters/
and https://github.com/golang/go/issues/22082
=> Update scrypt N parameter

pkg/jobs/redis_jobs.go
=> One poll loop per worker to avoid starvation

cmd/apps.go, pkg/consts/consts.go
=> Use the "latest" branch instead of "build" for hardcoded registry

assets/locales/en.po, assets/styles/stack.css, assets/templates/authorize_sharing.html, web/auth/auth.go, web/auth/auth_test.go
⚠️ ⚠️ ⚠️ ⚠️ ⚠️  **I wrote some Go code** ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
I'll explain what I wanted to do below so you can point me to better ways to do things. This is what I'm after:
=> Update accept sharing template

pkg/vfs/fsck.go, pkg/vfs/vfsafero/impl.go, pkg/vfs/vfsswift/impl.go
Some cases weren't fix properly due to a typo in the logbook run-through.
=> Fix fsck for swfit FileMissing case

pkg/workers/mails/mail_templates.go
This PR changes the mail layout to be more Cozy friendly.
=> New mail layout

cmd/serve.go, cozy.example.yaml, pkg/config/config.go, pkg/instance/instance.go
=>  Configurable delay between password reset 

assets/.externals
This version will the logout issue on desktop mode
=> Update cozy-bar to 4.8.2

pkg/scheduler/redis_scheduler.go, pkg/scheduler/redis_scheduler_test.go
The previous fix didn't work (my mistake)
=> Fix debounced triggers

pkg/workers/thumbnail/thumbnail.go
This PR skips the thumbnail update if the content of the file is the same, for instance from a PATCH request modifying the data, or a move of the parent directory.
=> Skip thumbnail generation if content does not change

pkg/vfs/metadata.go
Requires this PR: https://github.com/cozy/goexif2/pull/1
=> Add exif parsing for HEIC images

assets/scripts/passwd-strength-indicator.js, assets/scripts/password-helper.js, assets/scripts/polyfills/fetch.js, assets/scripts/submit.js, assets/templates/login.html, assets/templates/passphrase_renew.html
The goal of this PR is to have the reset form to work on IE11.
=> fix: remove es6 and add fetch polyfill 🚑

pkg/notifications/notifications.go
This PR adds a temporary `with_push` field to notifications to actually send notifications.
This field is temporary as the notification format will soon change with the creation of a real notification center. It is aimed for testing the push worker.
=> Add a temporary `with_push` field to notifications to send push notifications

assets/security.txt, web/routing.go
It will make easier for contributors to send bugs related to security to us via the proper channel
=> Add a security.txt file

cmd/apps.go
* Ability to show a webapp triggers
`cozy-stack triggers show-from-app banks`
* Ability to launch a trigger with its id
`cozy-stack triggers launch 748f42b65aca8c99ec2492eb660d1891`
=> CLI for triggers

assets/.externals
=> Upgrade cozy-bar to v4.9.2

docs/apps.md, docs/client-app-dev.md, pkg/apps/webapp.go, web/apps/serve.go
Related to https://github.com/cozy/cozy-bar/issues/176
Just a code proposal, I probably miss something out.
=> Start serving app name prefix from manifest

assets/.externals
Yeah it's me again. Last time (probably).
=> Update cozy-bar to v4.9.3

pkg/notification/center/notification_center.go, pkg/workers/push/push.go
Opened to fix issue raised in #1288.
=> Add notification id so all notifications can be shown client side

pkg/notification/center/notification_center.go, pkg/workers/push/push.go
The `notId` field for notification push needs to be an integer. This PR changes then encoding of this value.
=> Notifications: field "notId" has to be an integer

pkg/couchdb/couchdb_test.go, pkg/couchdb/local.go, pkg/sharing/replicator.go, pkg/sharing/replicator_test.go
To be reviewed/merged after #1295
=> Use the last sequence number in the replicator

docs/user-action-required.md
For the last part, I am not sure if we should use the notification API instead.
=> User action required errors

pkg/sharing/files.go, pkg/sharing/files_test.go, pkg/sharing/indexer.go, pkg/sharing/replicator.go, pkg/sharing/replicator_test.go, pkg/sharing/rule.go, pkg/sharing/rule_test.go, pkg/vfs/vfs.go, pkg/vfs/vfsafero/impl.go, pkg/vfs/vfsswift/impl_v1.go, pkg/vfs/vfsswift/impl_v2.go
It's a work in progress, but I'd like feedbacks on the sharingIndexer
=> Allow replication of folders for sharings

docs/release.md, scripts/release.rb, scripts/release.sh
Automate binaries generation and release publication
=> Release scripts

client/instances.go, cmd/instances.go, pkg/consts/views.go, pkg/couchdb/couchdb.go, pkg/instance/instance.go, pkg/sessions/session.go, pkg/stack/main.go, pkg/utils/utils.go, pkg/workers/move/export.go, scripts/cozy-app-dev.sh, web/apps/serve.go, web/auth/auth.go, web/errors/errors.go, web/instances/instances.go, web/konnectorsauth/oauth.go, web/middlewares/instance.go, web/routing.go, web/settings/context.go
This PR adds the possibility to have aliases domains for instances.
=> Alias for domains

pkg/instance/manager.go
=> Wrong premium URL

docs/sharing.md, pkg/sharing/member.go, pkg/sharing/sharing.go, tests/sharing/lib/sharing.rb, tests/sharing/tests/read_only.rb, web/sharings/replicator.go, web/sharings/sharings.go
=> Add read-only for a recipient

client/auth/auth.go, docs/auth.md
See https://github.com/cozy/cozy-stack/issues/1488
=> Fix the param for code in OAuth flow

client/apps.go, pkg/apps/apps.go, pkg/apps/installer.go, pkg/apps/konnector.go, pkg/apps/webapp.go, web/apps/apps.go, web/server.go
Blocking update when the permissions change and the user has not acknowledged them.
=> [WIP] Block update when permissions change

.gitignore, docs/release.md, scripts/build.sh, scripts/release.sh
Release cozy-app-dev with the others artifacts
=> Build dev version

cmd/config.go, pkg/accounts/credentials.go, web/data/accounts.go
Add 3 more commands to cozy-stack CLI :
- encrypt-data
- encrypt-credentials
- decrypt-data
=> Add cozy-stack CLI commands 

pkg/vfs/vfsafero/impl.go
Before this commit, a new memfs was created for each HTTP requests, and all changes from previous requests were lost in memfs (but not in CouchDB).
=> Allow to reuse a memfs between HTTP requests

pkg/apps/copier.go, pkg/apps/fetcher_registry.go, pkg/apps/installer.go, pkg/apps/konnector.go, pkg/apps/webapp.go, pkg/instance/instance.go, pkg/registry/registry.go, pkg/workers/exec/konnector.go, pkg/workers/exec/service.go, pkg/workers/updates/updates.go, web/apps/apps.go, web/apps/serve.go, web/registry/registry.go
Perform that application updates lazily, when application is being fetched, or konnector run.
This only works for applications installed from the registry.
=> Apps lazy update: perform update when entering application

pkg/apps/copier.go
In case of a concurrent update of an application, the swift copier (which does allow transactions) may launch a konnector or serve an application, before it was entirely copied.
With this fix, we may have multiple copies in parallel copying the same objects, but without concurrent interactions.
=> Fix concurrent application update

assets/locales/en.po
In English, it is more common to have Remember me in these kind of form.
=> feat: Memorize -> Remember me

pkg/consts/consts.go, pkg/instance/instance.go, tests/sharing/lib/bootstrap.rb, tests/sharing/lib/instance.rb, web/apps/serve.go, web/auth/auth_test.go, web/konnectorsauth/oauth.go, web/konnectorsauth/oauth_test.go, web/middlewares/permissions.go, web/sharings/sharings_test.go
To be merged after Cozy-Home was deployed in production
=> Make Home the true default app to redirect to after login

docs/registry.md
"versionsChannel" works , not "latestVersionChannel"
=> latestVersionChannel -> versionsChannel

docs/docker.md
That is a detail witch took me hours to understand where was my problem ^^U
=> Precision on doc Docker for the app names

pkg/statik/fs/fs.go
* Accept custom assets without shasums
* Set default context for an asset if none is specified
=> Improve external assets insertion

assets/scripts/submit.js, assets/templates/login.html
- 2FA submit was broken on success
- password field's placeholder was redundant with the label
=> fix: 2FA submit button + remove placeholder

client/apps.go, pkg/apps/konnector.go
There is a new proporty `folders` from the manifest. Cf https://github.com/cozy/cozy-apps-registry/pull/18
=> Handle folders from konnector manifest

assets/.externals, assets/scripts/password-visibility.js, assets/scripts/submit.js, assets/templates/login.html
A few design & functional feedback on the login view
~~⚠️ Waiting for the [Cozy-UI PR](https://github.com/cozy/cozy-ui/pull/751) to be merged before merging this one, so we can update the asset.~~
=> fix some margins & missing style

pkg/jobs/worker.go, pkg/metrics/workers.go
- Timeouts counter
- Split konnectors executions with konnectors with `account_deleted` param executions
=> Add some promotheus metrics

pkg/vfs/vfsswift/impl_v2.go
Fix object delete in SwiftVFS2 implementation by removing all previous versions on file deletion
=> Fix swiftVFS2 file version deletes

pkg/apps/konnector.go
Expose aggregator data from manifest, used in https://github.com/cozy/cozy-home/pull/1041
=> Handles agregator accounts

assets/.externals
Fix a realtime issue (only used to get the last installed application in the bar)
=> Update bar to v6.9.7

pkg/config/config.go
Manage the config file "the-debian-way".
Allow config split between system config and user config for easier packaging
=> Override default config file with .local config file

pkg/jobs/worker.go
- Force initialization of timeout counter even without timeouts
- Fix returned slugs
=> Improve prometheus metrics

assets/.externals, assets/styles/stack.css, assets/templates/authorize.html, assets/templates/authorize_app.html, assets/templates/authorize_sharing.html
Fixed buttons on authorize pages by using Cozy-UI.
=> fix: Authorize pages buttons with UI

assets/scripts/check-deeplink.js
See for more details : https://github.com/cozy/cozy-libs/pull/377
=> fix(deeplink): Don't use deeplink on iOS 12 +

assets/templates/error.html, web/auth/auth.go, web/sharings/sharings.go
without any mention of Cozy inside.
This is a temporary update. It may be review by designer later.
=> feat: Update error template layout

assets/locales/en.po
Some locales fixes for mailings.
~~⚠️ I didn't push the locales to transifex yet, so wait before merge.~~
=> fix: Clean up some mail locales

web/auth/auth.go
When a mobile app is linked to a web app, the stack will add a fallback parameter on the redirection after the authorize step of OAuth. This fallback parameter is the URL of the web app on this instance. It will allow to send the user to this URL if the mobile app can't be opened.
=> Add the fallback URI for authorize with linked apps

assets/.externals
We need this for new Drive and Contacts versions
=> Update bar to v6.25.7

web/files/references.go
Instead of updating each reference with a single query, update all of them in one bulk query, to improve performances.
This is related to #1903
=> Use BulkUpdate to update references

model/vfs/couchdb_indexer.go
We had a case where a goroutine was looping while renaming a directory. The root cause was not found, but at least, we should avoid an infinite loop.
=> Fix infinite move directory

model/app/installer.go
This cleaning prevents false update messages in the case of a non-empty
remaining available_version field if the latest version and current
version are the same
=> Clean the available_version field during updates

assets/locales/en.po, assets/mails/two_factor.mjml
Made the 2FA passcode bigger and centered on it's own line.
=> feat: Better 2FA mail

assets/locales/en.po, assets/mails/two_factor_mail_confirmation.mjml
Same as #1966 but with the confirmation mail.
=> feat: Better 2FA mail confirmation

model/job/mem_broker.go, model/job/mem_broker_test.go, model/job/rate_limiting.go, model/job/redis_broker.go, model/job/redis_broker_test.go, pkg/limits/rate_limiting.go, web/auth/auth.go, web/auth/rate_limiting.go, web/auth/register.go, web/files/files.go, web/files/files_test.go, web/sharings/sharings.go
Added limits were set with personal perception, we can discuss/change them if needed.
=> Add a limit for executed jobs

worker/migrations/migrations.go
When an instance is migrated to the swift layout v3, the migration worker won't return an error if some thumbnails can't be copied. It will just log those errors.
=> Log errors on thumbnail migration

model/app/fetcher_git.go
At the beginning, we were using the go-git library to install applications from the git repository. It was not ideal as this library was not capable to handle the tricky cases like the git binary (using something else that master for the default branch for example). So, we moved to use the git binary by default, and with a fallback to go-git when the binary was not available.
Now, most applications are installed from the registry and don't need git at all, and for the developers, we can expect that they have a git binary executable from the stack. So, there is no need to keep to go-git library, and one less library is good thing: less weight, less maintenance.
=> Remove the go-git dependency

model/notification/center/notification_center.go, worker/push/push.go
Add logs when push notifications have an error and at client initialisation.
=> Add logs for push notifications

web/instances/debug.go, web/instances/fixers.go, web/instances/instances.go
=> Improve the API endpoints for CLI

web/apps/apps.go
Do not try to execute the konnector when uninstalling it, if it has accounts but the on_delete_account is not defined: it will fail.
=> Fix konnector uninstall

worker/exec/service.go
This [change](https://github.com/cozy/cozy-stack/commit/e565a3f604b3300e813a61e49c956ea1e34b56a2) had a side-effect, blocking the possibility for a service to be executed by different triggers.
=> Allow several triggers for a service

docs/data-system.md, docs/intents.md, docs/konnectors-workflow.md, docs/mango.md, docs/permissions.md, docs/pouchdb-quirks.md, docs/realtime.md
Enforce english typography in documentation.
See https://everything2.com/title/rules+of+typography
=> Update english typography

model/vfs/couchdb_indexer.go, tests/integration/tests/filepath_operations.rb
When a directory is moved or trashed, if another directory has the same name but not the same case (like /Photos and /PHOTOS), the VFS could be corrupted. The mango selector `$lt` and `$gt` of CouchDB can give suprising results when [filtering documents][1], and the query to find the children of a folder can give bad results because of that. This commit add a check in go to fix this issue.
[1]: http://docs.couchdb.org/en/stable/ddocs/views/collation.html#collation-specification
=> Fix a special case of moving/trashing a directory

docs/jobs.md
Added link to time.ParseDuration.
=> docs: Add information on debounce syntax

worker/migrations/migrations.go
This PR improves migrations worker logging:
- log as error severity for failed migrations
- log if dst container deletion fail
- add swift error il thumbnail copying fail
=> Improve migrations worker logging

cmd/instances.go, model/sharing/indexer.go, model/vfs/couchdb_indexer.go, model/vfs/errors.go, model/vfs/vfs.go, model/vfs/vfsafero/fsck.go, model/vfs/vfsswift/fsck_v1.go, model/vfs/vfsswift/fsck_v2.go, model/vfs/vfsswift/fsck_v3.go, model/vfs/vfsswift/swift.go, web/files/files.go, web/instances/fixers.go, web/instances/instances.go, worker/migrations/migrations.go
- Increase timeout for migration worker
- Add a --fail-fast option to cozy-stack instance fsck
=> Improve migration

worker/migrations/migrations.go
Improve swift layout v3 migration worker logs:
- Log source layout for later reference
- Log an error if deletion of old layout containers fail
=> Improve swift-layout-v3 migration worker logs

model/vfs/vfsswift/swift.go
When deleting a Swift container, we have to first delete all the objects inside it, and then delete the container its-self. Swift behavior on consistency makes possible that the call to delete the container can fail just after we have deleted all the objects. This commit adds a retry loop to work around this limitation.
=> Improve the Swift container deletion

docs/INSTALL.md
Document the default directory hierarchy
=> doc: Default directory for files and apps

scripts/konnector-nsjail-node12-run.sh
To be able to parse some external pages, use node12 legacy http parser
=> Use node12 legacy http parser

assets/locales/en.po, assets/styles/stack.css
- Add i18n string for io.cozy.apps.suggestions
- Icon style
Used in banks.
=> Support for io.cozy.apps.suggestions

web/apps/serve.go
Computing the paths of dynamic assets can be costly, and being lazy by using methods on a struct can help improve a bit the performances.
=> Be lazy when rendering the index.html of apps

web/settings/context.go
Yaml unmarshals nested maps as map[interface{}]interface{}, but json refuses to marshal thme. As we have only strings as keys, we can transform them to map[string]interface{}.
=> Allow to use nested contexts from the config file

docs/README.md, docs/contacts.md, docs/toc.yml, model/contact/contacts.go, model/instance/lifecycle/create.go, pkg/couchdb/index.go, web/contacts/contacts.go, web/contacts/contacts_test.go, web/routing.go
The myself document is an io.cozy.contacts with the me attribute set to true. It has information about the owner of the Cozy instance, like its name and email address, and can be used by konnectors to link imported documents and files to an identity.
=> Add the myself document

web/auth/oauth.go
When an OAuth application is linked to a web app, its permission are taken from the web app manifest. If the web app is updated to add new permissions, the OAuth application may expect that, after some time, it can use the new permissions. For people using only the OAuth application, but not the web app, the manifest can be never updated with the new permissions. This commit tries to avoid this issue by updating the linked web app when the OAuth application refreshes its token. So, if someone uses an OAuth application 7 days after the linked web app has been updated on the registry, their Cozy instance will have the new version of the application, and the OAuth app can use the new permissions.
=> Update linked app on OAuth refresh

cmd/config.go, docs/cli/cozy-stack_config_insert-asset.md, docs/cli/cozy-stack_config_ls-assets.md, docs/cli/cozy-stack_config_rm-asset.md, docs/cli/cozy-stack_serve.md
=> Show in help when CLI commands are deprecated

worker/move/export.go
When a user asks to export its data with the files, it can take a lot of space. For practical reasons, we split the archive in several parts (the buckets). The size of a bucket was limited to 100MB before this commit. It means that for large instance, a user must have to download hundreds or thousands of buckets to export the whole. It has been changed to a dynamic rule. For 100MB or less, it is still a single bucket. For more, the bucket size will increase in the same proportion as the number of buckets. So, if an instance takes 4x more space than another, its export will use 2x more buckets and the buckets will be 2x larger. For an instance with 1TB, it means 100 buckets of 10GB.
=> Compute the bucket size for exports

pkg/limits/rate_limiting.go
The rate limiting works with counters. The redis implementation has a TTL set on the counters to reset the counter after a period has elapsed. But, it worked with 2 calls to redis: the first to increment the counter, and the second to set the TTL if the counter has been created. Network errors may happen between the two calls, and we can have counters with no TTL. In that case, the counter will grow but will never be reset, which is not good. This commit fixes this issue by using a single call to redis with a lua script.
=> Improve rate limiting with redis

assets/.externals
Previous version was only displaying "View offers" only when user had not subscribed to an offer. 
With this version, if the user has an offer, we add a "My offer"  link in the bar
=> feat: Upgrade cozy-bar to display My Offer / View offers

model/job/redis_scheduler.go
When the stack is using redis for jobs and triggers, it needs to remove the triggers from the scheduling key when a rate limit is reached. It avoids that to trying several times to push a job for the rate limited trigger, and should help to keep a healthy state of the global environment.
=> Remove triggers from scheduling when rate limited

docs/client-app-dev.md, web/apps/serve.go
See https://github.com/cozy/cozy-client/issues/586 for the context
=> Add a CozyData helper for apps template

docs/files.md, docs/settings.md, model/sharing/indexer.go, model/vfs/couchdb_indexer.go, model/vfs/trash.go, model/vfs/vfs.go, model/vfs/vfsafero/impl.go, model/vfs/vfsswift/impl_v1.go, model/vfs/vfsswift/impl_v2.go, model/vfs/vfsswift/impl_v3.go, web/files/files.go, web/files/files_test.go, web/settings/disk_usage.go, web/settings/settings_test.go
=> Improve disk usage comprehension

model/bitwarden/oauth.go
This caused a failed attempt to refresh token
=> Fix missing stamp in refresh token

web/bitwarden/bitwarden.go, web/bitwarden/bitwarden_test.go
Settings is used as a bitwarden client, therefore, it could trigger the
account migration worker as it uses the /bitwarden routes. To avoid
this, we check if the OAuth client kind is not "web", used for web apps.
=> Filter accounts migration by ClientKind

docs/konnectors-workflow.md
This makes the diagram source file easier to find and edit :)
=> docs: Add link to mermaid file

worker/exec/common.go, worker/exec/konnector.go, worker/exec/service.go, worker/mails/exec.go
For executing konnectors, services, and mjml, the stack uses nsjail with a temporary directory. This temporary directory was created inside the PrepareWorkDir functions, but cleaned via a defer from the function calling PrepareWorkDir. It means that if a PrepareWorkDir function fails after creating the temporary directory, neither the PrepareWorkDir function or its caller will clean this directory. This is fixed by always creating a function in PrepareWorkDir that is executed by its caller (this function does nothing before the temporary directory is created).
=> Fix cleaning of temporary directories

web/realtime/realtime.go
When a note is inside a shared directory, the stack needs to check recursively that the note is inside a directory for which the JWT token has a permission.
=> Fix realtime for a note in a shared directory

model/account/type.go
The account_types are used when a konnector is using a service with
OAuth 2.0. The OAuth 2.0 danse is started by the stack, with the
parameters from the account_type. Some services have bad implementation
of OAuth 2.0, and a case was reported where the service was not
supporting the redirect_uri parameter. A skip_redirect_uri_on_authorize
parameter was added on the account_types to not send the redirect_uri
for authorize.
=> Add a skip_redirect_uri_on_authorize parameter

model/account/type.go
When a konnector uses an OAuth provider, the stack is responsible to
manage the OAuth dance. Some providers require the state on the access
token endpoint, and some others throw en error if the state is given.
This commit adds an option to the account_types, named
skip_state_on_token to not include the state on this particular request.
=> Add an option to skip OAuth state on token

model/sharing/oauth.go
If several users accept the same sharing at the same time, we can have a
conflict when updating the sharing on the owner's instance. The fix is
quite simple: we should just retry in that case.
=> Fix accept sharing from two users at the same time

model/vfs/vfsswift/impl_v3.go
When more than 10 000 files must be deleted from Swift in trash worker,
we need to make several requests to Swift, as Swift is limited to 10 000
objects per bulk request.
=> Fix empty trash with lot of files

docs/sharing-design.md
This is meant to better introduce the core sharing concepts
=> Reorganize sharing design doc introduction

docs/couchdb-quirks.md, docs/sharing-design.md
This should clarify some points about conflicts
=> Add doc about CouchDB conflicts

model/account/type.go
See https://github.com/cozy/cozy-stack/pull/2575
=> Fix the selection of account type per context

worker/migrations/migrate-accounts-to-organisation.go
This lock is useful to prevent concurrent workers to be run at the same
time if several authentication requests are made at once
=> Add lock on accounts migration

docs/apps.md
Add some precision for getting and using fields
=> fix: Update Available fields to the service

docs/intents.md
Links in bibliography section of intent page was not clickable
=> fix: Add clickable link in intent's bibliography

.github/workflows/assets.yml, .github/workflows/ci.yml, .github/workflows/cli.yml, .github/workflows/integration.yml, docs/docker.md, web/middlewares/permissions.go
See https://blog.golang.org/go1.15
=> Add a build for Go 1.15 on GitHub Actions

model/vfs/couchdb_indexer.go
When the stack tries to delete 10k+ files in the trash, CouchDB can
respond with a 503. We are now splitting the work in several requests,
with a retry, to avoid such failures that can lead to FS
inconsistencies.
=> Fix deletion of many files in the trash

assets/.externals, assets/styles/stack.css, assets/templates/authorize_sharing.html
* https://zpl.io/awRQlJj
* https://zpl.io/29Qk3jl
=> Improve UI of the authorize sharing page

docs/remote.md
remove `will have` since we already have
=> docs: Update remote

assets/locales/en.po, assets/locales/fr.po, assets/styles/stack.css
=> feat: Add doctypes

cmd/serve.go, cozy.example.yaml, docs/archives/konnectors-design.md, docs/move.md, docs/workers.md, model/job/workers_list.go, model/permission/doctype.go, model/permission/permissions_test.go, model/sharing/rule_test.go, pkg/config/config/config.go, web/jobs/jobs.go, web/middlewares/cors.go, web/middlewares/cors_test.go, web/middlewares/secure.go, web/routing.go, worker/updates/updates.go
Cf https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral
=> Replace whitelist/blacklist by allowlist/blocklist

worker/migrations/migrations.go
When there is a copy error on a migration to layout v3 for an instance,
we can abort without waiting to have tried to copy all the other files.
This is done via a combo of:
- a semaphore to limit the number of concurrent calls to Swift
- an errgroup to collect the errors
- a context to coordinate the whole.
When an error occur in a go routine, the errgroup will collect it and
cancel the context. The later calls to aquire the semaphore will then
fail, which will make the VFS walk to abort.
=> Make the migrate to layout v3 worker fail fast

pkg/appfs/copier.go
Swift is eventually consistent, and the stack may be fouled by this
behavior when installing an app.
To install an app to a Swift container, it creates a temporary
"directory", put the files from the tarball in this directory, and if
every thing is fine, copy the files to their final destination before
deleting them (moves don't exist in Swift). To get the list of files in
the temporary directory, the stack was calling the Swift container, with
a list+prefix operation. The response to this call can be not complete
when used without the `X-Newest` header (which was the case).
One way to fix the issue would have been to add this header, but the
Swift documentation recommends to avoid it, as it has some performance
costs. And, we can fix it by just keeping the list of uploaded files in …
=> Fix installing app to a Swift container

assets/locales/en.po, assets/locales/fr.po, assets/templates/passphrase_reset.html
=> Emphasize the data loss when reseting the password

docs/files.md
Use up-to-date example for qualification and add a pointer to the metadata doctype
=> Update doc for qualification metadata

docs/config.md
=> Fix markdown in table in config.md doc

docs/notifications.md
- Title is mandatory https://github.com/cozy/cozy-stack/blob/master/model/notification/center/notification_center.go#L83-L85 
- Added a word on stateful / state
=> docs: Notification. Title is not optional

model/instance/lifecycle/destroy.go
When the instance has not been used recently, its indexes/version can be
out of date. The stack updates them automatically when needed, and the
instance deletion can trigger that when checking the accounts to clean.
So, we may have two concurrent updates of the instance document (the
indexes version and the deleting flag), and it can make the deletion
fails with a CouchDB conflict. We have added a retry for this case.
=> Fix CouchDB conflict on instance deletion

docs/files.md, docs/mango.md, pkg/couchdb/couchdb.go, pkg/jsonapi/data.go, pkg/jsonapi/jsonapi.go, web/auth/passphrase.go, web/data/data.go, web/data/data_test.go, web/files/files.go, web/files/files_test.go, web/files/paginated.go
The execution_stats flag allows to get some information about a mango query execution. See https://docs.couchdb.org/en/stable/api/database/find.html#execution-statistics
This adds support for this flag, both for `/data/:doctype/_find` and `files/_find` routes.
=> Add execution_stats support for _find requests

web/instances/checks.go
The banks manifest has two triggers for two services with the same
arguments, and they were wrongly seen as duplicates. This is fixed by
looking at the message.
=> Fix check triggers for banks

assets/templates/move_in_progress.html, docs/auth.md, docs/sharing.md, docs/user-action-required.md, model/contact/contacts.go, model/instance/instance.go, model/instance/warnings.go, model/move/importer.go, model/move/request.go, model/move/sharing.go, model/note/open.go, model/permission/errors.go, model/sharing/api_sharing.go, model/sharing/files.go, model/sharing/member.go, model/sharing/oauth.go, model/sharing/replicator.go, model/sharing/reupload.go, model/sharing/sharing.go, model/sharing/upload.go, pkg/consts/doctype.go, tests/integration/lib/accept.rb, tests/integration/lib/instance.rb, tests/integration/lib/move.rb, tests/integration/tests/moving_a_cozy.rb, web/auth/oauth.go, web/middlewares/permissions.go, web/settings/settings.go, web/sharings/sharings.go, worker/moves/workers.go
~~It depends of https://github.com/cozy/cozy-stack/pull/2790~~ (merged)
=> Move sharings

web/instances/checks.go
The command will now detect triggers for an application service that
have no name in their message.
=> Improve cozy-stack check triggers

docs/konnectors.md
Add doc example for GET /konnectors/:slug
=> Update /apps - Konnectors

model/move/store.go
There was a typo in redisStore.AllowDeleteAccounts (the prefix was added
2 times). And I have refactored the code to extract the key computation.
=> Fix a typo in move store

cozy.example.yaml, model/sharing/member.go
And change the default limit from 50 to 90.
=> Make the limit of members per sharing configurable

.github/workflows/assets.yml, .github/workflows/ci.yml, .github/workflows/cli.yml, .github/workflows/integration.yml, .github/workflows/release.yml, docs/docker.md, model/move/importer.go
See https://blog.golang.org/go1.16
=> Add a build for Go 1.16 on GitHub Actions

pkg/appfs/server.go
This was broken by adding brotli compression.
https://github.com/cozy/cozy-stack/pull/2898
=> Fix cozy-stack serve --appdir

assets/images/icon-location.svg, assets/locales/en.po, assets/locales/fr.po, assets/styles/stack.css
- Add an icon for location data
- Add locales for `io.cozy.timeseries.geojson` permissions
=> Geojson permission

model/session/login_history.go
Remove forgotten Printf debug statement
=> Remove debug Printf

web/registry/registry.go
When a client makes a request to the stack for an app icon from the apps
regsistry for the latest version, the stack will now send an HTTP header
to inform the client that it can cache it for one day.
=> Add client cache for icons from apps registry

web/auth/auth.go
A Cozy can be onboarded with the need to redirect to a specific app.
The password selection page accepts a redirection parameter for this
use case, but when the OIDC method is used for authentication, the user
doesn't go on this page and it doesn't work. We now accept also this
redirection parameter for / when OIDC is enabled.
=> Allow to redirect to an app for OIDC onboarding

model/vfs/metadata.go
The metadata extractor can be stuck when a truncated file is uploaded.
The Exif parser is waiting for more bytes to read, but there are no more
bytes. A timeout has been added to unblock the worker in this case.
=> Fix metadata extractor

assets/locales/en.po
Small fixes in permissions page.
=> fix: Typo + replace types of data by data types

.github/workflows/assets.yml, .github/workflows/ci.yml, .github/workflows/cli.yml, .github/workflows/integration.yml, .github/workflows/release.yml, docs/docker.md, tests/integration/tests/sharing_read_only.rb
See https://blog.golang.org/go1.17
=> Use Go 1.17 instead of 1.16 on CI

scripts/konnector-nsjail-node12-run.sh, scripts/konnector-nsjail-node16-run.sh, scripts/konnector-nsjail-node8-run.sh
Propagate COZY_TRIGGER_ID variable to konnector when run inside nsjail
=> Propagate COZY_TRIGGER_ID to konnector when run inside nsjail

go.mod, go.sum, model/bitwarden/oauth.go, model/instance/instance.go, model/instance/instance_test.go, model/move/request.go, model/oauth/client.go, model/oauth/client_test.go, model/office/callback.go, model/office/open.go, model/permission/claims.go, model/session/delegated.go, model/session/delegated_test.go, model/sharing/oauth.go, pkg/crypto/jwt.go, pkg/crypto/jwt_test.go, web/auth/auth_test.go, web/middlewares/permissions.go, web/oidc/oidc.go, web/permissions/permissions_test.go, worker/exec/konnector_test.go
The package gopkg.in/dgrijalva/jwt-go.v3 is no longer maintained. Let's
switch to the community maintained fork, github.com/golang-jwt/jwt.
=> Use github.com/golang-jwt/jwt

docs/INSTALL.md
Insert troubleshooting section to solve errors I face while installing project.
=> chore(docs): troubleshooting section in INSTALL

docs/INSTALL.md
Update INSTALL documentation in accordance with https://github.com/cozy/cozy.github.io/pull/223
This should be merged after https://github.com/cozy/cozy.github.io/pull/223
=> Update INSTALL documentation

worker/migrations/migrations.go
- Administrative folder can have been created with the default locale,
and the locale has been changed later
- Photos folder can have been created with some sub-folders.
=> Fix the remove-unwanted-folders migration

model/note/note.go
CouchDB is not strongly consistent, and when saving a note with a
changed title, the stack makes two changes: one for renaming the file,
and the other for changing the content. If the user makes a change to
the content, the stack will fetch the document but CouchDB can return
the intermediate version, which can cause trouble (title can be lost).
To avoid this issue, we are pushing the change to the cache, so the
stack will fetch the document from the cache (previously, the cache was
just cleaned).
=> Fix a race condition on notes

web/auth/oauth.go
When mandatory checking of flagship for the scope * is disabled, the
session_code wasn't checked on /auth/authorize page.
=> Fix session_code for authorize

model/sharing/invitation.go, model/sharing/member.go
When a recipient adds members to a sharing, we can have a race condition
with multiple writes on the sharing document. A retry loop has been
added to workaround this issue.
=> Fix adding delegated members to a sharing

pkg/couchdb/proxy.go
When docs were created in bulk, no event was fired, because we missed to
set the ID and/or the Type.
Therefore, the @event triggers were blind on such updates.
=> Fix bulk save events

model/vfs/couchdb_indexer.go, model/vfs/vfs_test.go
CouchDB has changed the way several documents with the same field in
different encoding are returned in view requests. But, it wasn't what I
was expecting, and with CouchDB 3.2.1+, it wasn't possible to change a
file or directory name to a new name when just the encoding has changed
(eg NFC -> NFD).
Cf https://github.com/apache/couchdb/issues/3773
=> Fix encoding issues of dir/file name in CouchDB

assets/.externals
Includes numerous fixes
- https://github.com/cozy/cozy-bar/commit/3f899413c90bddc9c31e0e561d42836c43780a4b
- https://github.com/cozy/cozy-bar/commit/1547e68a90064f5fd7057a7310e7a68026c31bb9
- https://github.com/cozy/cozy-bar/commit/d5a7a9cc1dc37ee351e9a3cf1b30f27aa5d04504
- https://github.com/cozy/cozy-bar/commit/82027e101cdfe21bf3f118d8ed108840e40b739d
- https://github.com/cozy/cozy-bar/commit/257dfe5cc15a825ff10e495a6e883bb042e56ec6
=> feat: Upgrade cozy-bar to latest

docs/workers.md, worker/exec/service.go
Just like the konnectors, services now have the possiblity to retrieve
custom fields through the COZY_FIELDS env var.
=> Add COZY_FIELDS to service worker

model/account/accounts.go
When several accounts are deleted, it can happen that the database for
soft deleted accounts is tried to be created by 2+ goroutines. In that
case, only one request will succeed, and the other goroutines should
still try to create the documents.
=> Fix a race condition

web/accounts/oauth.go, web/accounts/oauth_test.go
On the OAuth flow for BI konnectors, the stack should avoid creating a
new account when there is already one account with the same
connection_id.
=> Avoid recreating account with same connection_id

model/app/installer.go
When an app is asked to be updated several times at the same time, it may happen that triggers for the services will be messed. This is fixed by adding a lock for updates.
The happy path (when the app is already up-to-date) is kept the same. It is only when an update is attempted that a lock is acquired. As such, the app document must be reloaded from the database as it may have been changed by another goroutine doing the update.
=> Fix race condition on app updates

cmd/fix.go, web/instances/fixers.go, web/instances/instances.go
A new command `cozy-stack fixer service-triggers` will clean the triggers for webapp services.
=> Add a command to fix service triggers

.github/workflows/assets.yml, .github/workflows/ci.yml, .github/workflows/cli.yml, .github/workflows/integration.yml, .github/workflows/release.yml, tests/integration/lib/couch.rb
Cf https://github.com/actions/runner-images/issues/6002
=> Fix CI during the brownouts from GitHub

docs/instance.md
Fix broken list in https://docs.cozy.io/en/cozy-stack/instance/#blocking
=> Fix instance doc

worker/exec/cmd_unix.go, worker/exec/konnector_test.go
It looks like https://github.com/cozy/cozy-stack/pull/3550 doesn't play nicely with the nsjail scripts. Let's try again.
=> Fix cwd for konnectors (bis)

pkg/couchdb/stream/all_docs.go
By making path and fields bytes slices instead of strings, we can make the all_docs endpoint a bit faster (about 5% in my tests).
=> Add a small optimization for all_docs

model/sharing/sharing.go
When a sharing is revoked, it may happen that a conflict (409 from CouchDB) is received when updating the io.cozy.sharings document after deleting its triggers. After that, an error trigger_on_inactive_sharing is reported by cozy-stack check sharings.
And the fix is quite simple: when we receive a 409, we reload the document from CouchDB and try again.
=> Fix a conflict case for io.cozy.sharings doc

README.md
=> Fixed small typo in readme

docs/konnectors.md
=> fix: Fix konnectors doc example

client/auth/storage.go, cmd/cmd_test.go, cmd/fix.go, model/remote/remote.go, pkg/couchdb/couchdb.go, web/oidc/oidc.go
Those replacements have been sugested by the `gocritic` linter.
=> Use `strings.ReplaceAll` instead of `strings.Replace(*, *, -1)`

model/app/fetcher_git.go, model/job/worker.go, model/move/export_test.go, pkg/config/config/config.go, pkg/config/config/funcs_map.go, web/files/files_test.go, web/shortcuts/shortcuts.go, worker/updates/updates.go
Those fix have be done following the suggestions from the `gocritic` linter
=> Fix the assignOp issues emited by gocritic

cmd/apps.go
Those fixes are following the suggestions from the gocritic linter
=> Fix the gocritic `unalambda` suggestions

model/sharing/member.go, model/sharing/reupload.go
Those fix have be done following the suggestions from the gocritic linter
=> Fix the gocritic `elseIf` suggestions

model/app/fetcher_http.go, pkg/appfs/copier.go
When an app is installed or updated, it may happen that several instances are doing this operation at the same time. There was already a lock to avoid several installs/updates of an app on the same instance, but we want to avoid a too large lock, which can create contention.
This commit adds a new lock to avoid FS write operations for installing/updating an app from several instances at the same time (ie just after a new version has been published). The happy path avoids the lock to ensure best performances.
It should help to reduce the pressure on Swift after a new version of an app is published.
=> Add a lock around fs.Copier when updating apps

cmd/check.go, docs/admin.md, docs/cli/cozy-stack_check_sharings.md, model/sharing/rule.go, model/sharing/setup.go, model/sharing/sharing.go, web/instances/checks.go
Each check has its own function.
=> feat: Add sharing trees consistency check

pkg/lock/simple_redis.go
We have many `redisLock` structs, and using one random number generator and logger entry for each `redisLock` takes a lot of RAM. We can use a single global variable to avoid that.
=> Fix memory leaks in redis locks

model/sharing/sharing.go
There are no issues in having an inactive sharing as the ancestor or
the descendant of another, active, sharing.
Besides, if the root of the inactive sharing has been completely
deleted, CouchDB will return an error when we try to fetch the shared
documents.
For these reasons, we skip inactive sharings when looking for sharing
in sharing situations.
=> fix: Sharing in sharing check skips inactive ones

model/bi/webhook.go, web/data/accounts.go
If the client requesting the creation of an Account does not provide
any `cozyMetadata`, we'll generate it.
The idea is to minimize the amount of data partners have to provide to
create Accounts.
=> feat: Add cozyMetadata to new Accounts if missing

model/note/note.go
When a note is created, and another note has the same title, the filename of the new note should be "title (n)", not "new note - date".
=> Fix creation of a note with same title

web/bitwarden/bitwarden_test.go
This migration bring several advantages:
- It allow to handle the body close automatically
- It remove the need to handle a lot of useless bytes/buffer managment
- The body validation is attached to the request and so the error messages are greatly improved
- Later we will be able to setup a more verbose logger if we catch the use of a custom flag.
=> Use `gavv/httpexpect` for the `/web/bitwarden` tests

web/instances/fixers.go
This command wasn't recreating services in some cases where the trigger_id was blank.
=> Fix the cozy-stack fix service-triggers command

web/files/files_test.go, web/files/notsynchronized_test.go, web/files/pagination_test.go, web/files/permissions_test.go, web/files/referencedby_test.go
This was a really big one to migrate. :sweat_smile:
=> Use `gavv/httpexpect` for the `/web/files` tests

client/realtime.go
We may panic on realtime client when the "pump" goroutine receives several messages in a burst, and is waiting to send one of them to its channel, while the main goroutine is closing the channel.
=> Fix a panic in client realtime

go.mod, go.sum, model/app/apps.go, model/app/fetcher_git.go, model/app/installer_konnector_test.go, model/app/installer_webapp_test.go, model/app/webapp.go, model/instance/instance.go, model/move/archiver.go, model/vfs/vfsafero/fsck.go, model/vfs/vfsafero/impl.go, model/vfs/vfsafero/thumbs.go, pkg/appfs/copier.go, pkg/appfs/server.go, pkg/assets/dynamic/impl_os.go, pkg/previewfs/cache.go, worker/exec/common.go, worker/exec/konnector.go, worker/exec/konnector_test.go, worker/exec/service.go, worker/mails/exec.go
After some bugs were found in the main branch a fork have been done and some fix have been pushed into it.
Since then the fix have reached the main branch so there is no more need for a fork and we can return to the main branch
This review have been generated with the following command:
```bash
sed -i 's/cozy\/afero/spf13\/afero/g' **/*.go
go mod tidy
```
Fix #3781
=> Move back to https://github.com/cozy/afero

model/stack/main.go, pkg/assets/dynamic/dynamic_test.go, pkg/assets/dynamic/fs.go, pkg/assets/dynamic/impl_afero.go, web/apps/apps_test.go, web/auth/auth_test.go, web/middlewares/setup_test.go, web/oidc/oidc_test.go, web/routing_test.go, web/sharings/replicator_test.go, web/sharings/sharings_test.go
This PR bring several ameliorations:
- It restrict the OSFS access to only its own folder be setting up the root directory.
- It remove the dependency to the config package
=> Clean up the `/pkg/assets/dynamic.NewOsFS` function

web/instances/instances.go
Fix last-activity endpoint status code according to [documentation](https://docs.cozy.io/en/cozy-stack/admin/#get-instancesdomainlast-activity)
=> Fix last-activity endpoint status code

worker/exec/konnector_test.go
Some tests in worker/exec were not running on the CI, because of -short flag, and we missed that they were failing. Let's fix them!
=> Fix worker/exec tests

model/job/mem_scheduler.go, model/job/mem_scheduler_test.go, model/job/redis_broker_test.go, model/job/redis_scheduler_test.go, pkg/limits/impl_inmemory.go
=> Fix some dataraces inside `/model/job`

model/job/redis_scheduler_test.go
A previous commit has made a refactoring to use a new instance for each test, instead of using the same test instance for all tests. It was made to avoid side effects from one test on another, but it has the opposite effect. The instances were created via setup.GetTestInstance(), which starts the system broker+scheduler. But the configuration is read when the first instance is created, and the other tests were inheriting this configuration. We can avoid those issues by using a custom scheduler in redis scheduler tests, instead of using the system scheduler.
=> Fix tests for redis scheduler

model/instance/instance.go, web/settings/instance.go
In the settings document, the format for default_redirection is expected to be slug+path, but it was filled by a full URL in some cases when the settings are updated. We fix the code and adding some cases to manage instances with the bad format.
=> Fix bad format for default_redirection

.github/workflows/js-lint.yml
We have nothing to install so we can skip the 'install' step
=> Fix the "Lint js" job

.github/workflows/go-tests.yml
This review is based on the following documentation: https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
It also add a check for dataraces
Fix #3798
=> Upload the coverage to codecove after the tests

.github/workflows/go-tests.yml, .github/workflows/integration.yml
See https://blog.couchdb.org/2023/04/25/3-2-3-3-3-2/
=> Update CouchDB used for GitHub Actions

.github/CODEOWNERS
This file allows to setup code ownership and setup automatically the peoples from `@cozy/dev` as a reviewer
=> dev: Add the CODEOWNERS file

pkg/config/config/config.go, pkg/logger/logger.go, pkg/logger/logger_test.go, pkg/logger/syslog.go, pkg/logger/syslog_stub.go, pkg/realtime/log_hook.go
Due to an bug the "syslog" hooks was added twice, leading to log the same line several times.
=> Fix: Remove the log duplicates

docs/apps.md, docs/konnectors.md, model/app/apps.go, model/app/apps_test.go, model/app/installer.go, web/apps/apps.go
This PR is an another proposition for the issues addressed by #3934. it also contains some fixes
=> feat: Update konnectors when fetching their manifest

cozy.example.yaml
Third try to remove this damn letter. This time with a specific PR.
=> doc: Fix typo

tests/testutils/test_utils.go, web/apps/apps_test.go, web/middlewares/cors_test.go, web/middlewares/csrf_test.go, web/middlewares/secure_test.go, web/middlewares/user_agent_test.go
And remove a call to `fmt.Printf`
=> refactor: Remove the error from `SetupSwiftTest`

web/auth/oauth.go
It happens that an OAuth client makes several requests in parallel for refreshing its access token. CouchDB may create a conflict in that case. It would be better if OAuth clients can avoid this behavior, but let's mitigate this issue with a lock on the endpoint to avoid making the requests to CouchDB in parallel.
=> Add a lock around access token endpoint

model/session/session.go
The stack can receives several requests from a webapp in parallel. If the session needs to be updated in CouchDB for the last_seen field, the stack may make several requests to CouchDB in parallel, and CouchDB may create a conflict. We can mitigate this issue by using a lock when updating the session in CouchDB.
=> Add a lock around session updates

web/oidc/oidc.go, web/oidc/statestore.go
- Use larger state and nonce parameters
- Check the nonce (in addition to the state)
=> Make FranceConnect integration more secure

model/sharing/files.go, pkg/couchdb/couchdb.go, web/sharings/replicator.go
=> Improve some errors for sharings

model/account/type.go
Next versions of harvest, banking konnectors will handle powens uuids
which will allow the have the same identifiers for banks in every
environments (int, prod, local, etc)
=> feat: Handle Powens Uuids

pkg/jsonapi/errors.go, web/auth/auth_test.go
=> Fix bad case for error message

model/sharing/sharing.go
add member ID in sharings check reports
=> Show memberID in sharings check reports

debian/cozy-stack.postinst, debian/cozy.yml
Add mail config to deb package
Also fix permission on /var/log/cozy
=> Add mail config to deb package

scripts/docker/production/README.md, scripts/docker/production/docker-entrypoint.sh
=> Fix docker documentation and entrypoint

model/note/delete.go
There was a panic when trying to get the ThumbFS, because the swift layout was missing from the given prefixer.
=> Fix the empty trash handler

worker/exec/konnector.go
When a konnector throws an USER_ACTION_NEEDED.CGU_FORM error, the stack should not retry immediately the konnector. But, if it was started via a @cron trigger, the next time the trigger will be triggered, a job must be created.
=> Fix USER_ACTION_NEEDED.CGU_FORM error handling

model/sharing/upload.go
When the share-upload worker transfers a file from one Cozy to another, it looks at the io.cozy.shared change feeds, and then loads the io.cozy.files. It may happen that the two documents don't match the same revision because of CouchDB eventual consistency, or because of a change between the two requests. We are now aborting the share-upload in that case to retry later.
=> Fix a source of content mismatch FS errors

model/sharing/member.go
1. Alice shares some bitwarden ciphers with Bob
2. Bob forgets the password of their Cozy and resets it
3. Alice adds again Bob to the sharing
Bob should be able to use the shared ciphers, but it wasn't the case as the organization key was encrypted by the wrong public key (the one that was used before the password reset).
=> Fix ciphers sharing after a password reset

pkg/couchdb/bulk.go, pkg/couchdb/couchdb_test.go
The bug was introduced in #4377.
=> Fix ForeachDocs function of pkg/couchdb

web/routing.go
Add endpoint `/connection_check` to admin port to be able to check if stack admin is reachable
=> Add connection_check endpoint to admin port

cmd/fix.go
`cozy-stack fix redis` command is sensible so requiring user confirmation before starting to rebuild redis on all instances seems the way to go
=> Ask for confirmation for fix redis command

model/rag/chat.go
This sources were not properly working after API changes
=> Fix sources for RAG

pkg/rabbitmq/handlers.go, pkg/rabbitmq/rabbitmq_test.go
=> fix: Changed a format of a domain in incoming messages(only top level domain)

docs/apps.md
First proof of concept here
https://github.com/cozy/cozy-home/pull/2306
https://github.com/cozy/cozy-drive/pull/3525
=> Add entrypoints to apps.md
