- README.md
Go source code is downloaded to `$GOPATH/src`.
So, `cd $GOPATH/github.com/cozy/cozy-stack` should be `cd $GOPATH/src/github.com/cozy/cozy-stack`.
> Fix src path of cozy-stack

- cmd/root.go
Not needed because `RootCmd.Execute` is run by `main.go`
> Delete unused `Execute`

- docs/crud.md
RFC @nono
First shot at documenting the API for data manipulation.
Basically just a JSONAPI wrapper to Couchdb
Decision to be discussed : 
- Do we really want JSON-API for these route too or should we consider them lower level.
- The former DS hided `_rev` from the client, I believe this was unwise as we ended up reimplementing it in places for synchronisation with other sources (*dav and imap)
- Should we really allow the creation of a doc with a given `_id` ? The only proper way to use this API is to wrap it in a trycatch and do a `PUT` instead if the doc already exists. It seems we should push devs to always do a `PUT`, or eventually a `PATCH` if only changing some fields.
- keeping the type (formerly `docType`) in the document seems convenient, however, it should be marked as a …
> Add documentation for next sprint CRUD API

- .gitignore
- .travis.yml
- couchdb/couchdb.go
- couchdb/errors.go
- couchdb/errors_test.go
- docs/files.md
- web/data/data.go
- web/data/data_test.go
- web/files/files.go
- web/files/upload_test.go
- web/jsonapi/jsonapi.go
- web/middlewares/instance.go
- web/middlewares/instance_test.go
- web/router.go
- web/status/status_test.go
So this is the first shot at GetDoc API
It is based on 3 commits by @nono which introduce the instance concept.
Some design decisions : 
- a couchdb packages at cozy-stack/couchdb
- Introducing the notion of database prefix in instance, which joined with doctype give use the database name
- using `gin.ErrorLogger` to output json errors
- Changed status test for healthy and added couchdb to travis
Left TODO :
- the database naming should be better analysed, for now it will fail if there is a character outside of `_$()+-/a-zA-Z0-9` in host or doctype, or if the host doesnt start with a `a-z`.
- Need more code comment, will be working on it in parallel with review
@nono, there is a merge conflict with master. I could fix-it by merging master into this branch, or rebasing this branch on …
> First shot at read api.

- cmd/config.go
- cmd/root.go
- cmd/serve.go
- cmd/status.go
- config/config.go
- config/config_test.go
- main.go
Solves #21  "Configuration enhancement", see there for details
> Configuration enhancement

- web/files/files.go
- web/files/files_test.go
- web/files/upload_test.go
- web/middlewares/instance.go
**Still work in progress**
Lots of stuff are missing and would require connections with couchdb. However since the directory creation share some codes with the uploading part, I prefer to make this PR ASAP so that we can work in parallel 🎿 .
This PR introduces:
- better error handling
- some input sanitization
- draft of the directory creation on VFS
> [WIP] Create directory

- web/files/files.go
- web/files/files_test.go
- web/files/upload.go
Adds MD5 checksum on uploaded content.
In 6fbe3ce40d2e57268aeb8463166c1aaa87628ed2 I tested a concurrent approach which is a little faster but with added complexities. I came to a simpler (and a little slower) solution finally...
> Upload with integrity check

- cmd/root.go
- cmd/serve.go
- cmd/status.go
- config/config.go
Little *morning nitpicking* PR on naming and help messages:
- rephrased the outdated `help serve` message
- renamed the `Address` config param to `Host`, which I think is more correct..
- more consistent help messages for flags
> Serve help message

- couchdb/couchdb.go
- couchdb/couchdb_test.go
- web/data/data.go
- web/data/data_test.go
See #36.
The `doctype` on the JSONDoc felt weird and we may fallback on this one... This change will affect the crud api since it adds a explicit `doctype` field to documents.. while the `_id` field also contains it. I'm not really sure about that.
Other than that, I don't see many issue.
> couch.Doc interface

- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- web/errors/errors.go
- web/files/files.go
This PR is only refactorization. The main idea is to export the vfs parts in its own package to give us some space for what is coming next.
The diff may be hard to read so here exact list of what it does:
- create a `package vfs` with all the code specific to vfs, file and directory handling (no gin)
- add error handling in vfs/errors
- renamed `vfs.DocMetadata` struct into `vfs.DocAttributes` and make its fields private
- add `mime`, `class` and `size` fields to `vfs.DocAttributes` to be more consistent
- use `web/errors` in `web/files` to be consistent with `web/data`
> [VFS] Add a vfs package

- .travis.yml
- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
This PR introduce the new route `PUT /files/:files-id` along with a new method `vfs.ModifyFileContent`.
==
*Some notes*:
In order to add this feature, I also removed the intermediary (and awkward) struct `vfs.DirAttributes` that was used to stack all the contents of a creation request for files *and* directories. Now, `web/file` can use `vfs.NewFileDoc` or `vfs.NewDirDoc` directly and appropriately.
I also increased the gometalinter dupl-threshold, because it annoyed me on some trivial code (in test)...
> [VFS] Update file content

- couchdb/couchdb.go
- couchdb/couchdb_test.go
- couchdb/mango/index.go
- couchdb/mango/index_test.go
- couchdb/mango/query.go
- couchdb/mango/query_test.go
This PR introduces mango queries to the couchdb package.
The API is as follow 
```go
index := mango.IndexOnFields('folderID', 'modificationDate')
couchdb.DefineIndex(prefix, doctype, index);
query := couchdb.FindRequest{
Filter: mango.Equal('folderID', myID), 
Sort: mango.SortBy{'modificationDate', mango.Asc}
}
var out []Files
couchdb.FindDocs(prefix, doctype, &query, &out)
```
> Add mango index & queries to couchdb package

- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- web/files/files_test.go
- web/jsonapi/errors.go
Fix concurrent access to file and directory creation and add tests on the matter.
- rely on one call to the FS using `O_CREATE|O_EXCL`
- rely on `MkDir` atomicity *before* adding the document in Couch
- rely on `Rename` atomicity to modify file content using a temporary file
--
This should be merged after #48
> [VFS] Concurrent access

- .travis.yml
- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
- web/jsonapi/errors.go
Adds the `PATCH /files/:file-id` route to modify the metadata of a file, move it and rename it.
I've also added a `vfs.Context` struct to stop passing around fs / dbprefix values...
> [VFS] Patch file meta

- docs/files.md
- vfs/file.go
- vfs/vfs_test.go
- web/files/files.go
- web/files/files_test.go
Use CouchDB indexes to fetch files by path and export the content with `GET /file/metadata`.
Note that the functionality is not working since we are still laking the creation of indexes at startup.
> [VFS] Get file metadata

- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files.go
- web/files/files_test.go
I opted for an intermediary solution for now to handle path and move actions: remove the `Path` field from `FileDoc` and keep it in `DirDoc`.
Files and Directories are still in different databases, but this will be removed soon.
> [VFS] Change directory metadata, move and rename them

- docs/backup.md
- docs/moving.md
- docs/replication.md
This is a big big wip.
Can we figure out an unified sharing/replication/permissions model that we can explain in 5min or less ?
@nono @jinroh @Gara64 @Ljinod 
:heart:
> Replication documentation

- couchdb/couchdb.go
- couchdb/mango/index_test.go
- couchdb/mango/query_test.go
- docs/files.md
- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files.go
- web/files/files_test.go
This PR is quite simple but is has some implications and changes regarding the current doc.
By having files and directories sharing the same doctype `io.cozy.files`, I made these changes:
- `DirDoc` and `FileDoc` now have a `Type string` field (either `"file"` or `"directory"`)
- The ID of the root directory is `io.cozy.files.rootdir`
I did not change **input** side of the API, which still has the notion of `io.cozy.folders`. So clearly, this PR is a work in progress and I would understand if we don't want to merge it as-is.
--
Note: the notion of RootDirectory is handled "manually" in the code. I did not introduce a special object in the database.
> [VFS] Get dir meta

- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
This PR removes the need to pass `?Type=` query param for `GET / PATCH` requests.
> [VFS] Remove the requirement to pass Type query param for modify/read

- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files.go
This PR introduces a `FileCreation` handle that implement `io.WriteCloser`.
It also mutualise the code between the now old `CreateFileAndUpload` and `ModifyFileContent` functions. The `CreateFile(c *Context, newdoc, olddoc *FileDoc) (io.WriteCloser, error)` is now the generic function to create or modify the content of a file.
The `Close()` function of the handle is now (more than ever) important to call as it commits the file document creation or update into CouchDB (see comments).
> [VFS] File handle for creation (io.WriteCloser)

- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
- web/jsonapi/data.go
- web/jsonapi/jsonapi.go
**To merge after #61**
In current version of patching, the tags field was in append mode only. This had two bad side-effect, IMHO:
- stateful API
- impossible to remove or replace
I don't think we want to go to the [jsonpatch](http://jsonpatch.com/) path, so I just rely on a simple replace.
---
This PR also mutualise some code between dirs and files and removes some legacy code used to unmarshal jsonapi document. A `jsonapi.Bind` function has been introduced to do that.
> [VFS] Tags replace on patch

- docs/files.md
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
Changed the GET API to make it look like that:
```
router.GET("/download", ReadFileContentFromIDHandler)
router.GET("/download/:file-id", ReadFileContentFromPathHandler)
router.GET("/metadata", ReadMetadataFromPathHandler)
router.GET("/:file-id", ReadMetadataFromIDHanler)
```
FYI, it was like that before:
```
router.GET("/download", ReadFileContentFromPathHandler)
router.GET("/:file-id", ReadFileContentFromIDHandler)
router.GET("/metadata", ReadMetadataFromPathHandler)
router.GET("/:folder-id", ReadFolderMetadataFromIDHanler)
```
Open to your remarks.
> [VFS] Change metadata endpoints to simplify API

- cmd/instance.go
- couchdb/couchdb.go
- debug.log
- docs/instance.md
- instance/instance.go
- instance/instance_test.go
- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/data/data_test.go
- web/files/files.go
- web/files/files_test.go
- web/middlewares/instance.go
- web/middlewares/instance_test.go
- Instances are created through the CLI
- Instances are stored in a Couchdb DB named global/instances
- When an instances is created, we also create vfs root directory and vfs indexes.
- If there is no instance for the request's Host header, an error is returned (exception for localhost -> dev)
@jinroh I did not change the several places where you commented about the root folder. Let's discuss next week. 
**FUTURE**
- Handle subdomains (someapp.bob.cozycloud.cc)
- Move creation of `global/instances byDomain` request into stack initialization (Not a priority, win a few ms on instance creation ...)
> Add actual instances management

- couchdb/mango/query.go
- vfs/file.go
This PR add the possibility to pass a map of key / values as a mango selector (instead of having to do a `And{Eq, Eq, ...}`)
Note: `$eq` selector is [equivalent](https://docs.mongodb.com/manual/reference/operator/query/eq/) to `{ field: value }` object
> Add mango selector with multiple keys/values

- apps/git.go
- vfs/file.go
- vfs/vfs.go
- web/files/files.go
- web/files/files_test.go
These changes add support to go-git-v4.rc2 that added the `OpenFile(name, flag, perm)` to its `FileSystem` interface.
I took the opportunity to have add `*File` handle that implement `io.Reader`, `io.Seeker`, `io.Closer`, `io.Writer`.
I had to change the way file modification is handled, since go-git needs has a handle to both read and write a same file:
- before: `create tempfile -> write -> safe rename on close or if error remove the tempfile`
- now: `safe rename in backup file -> safe file create -> write -> remove backup on close or if error reuse backup`
This scheme looks better for when we will want to keep multiple file revisions in the vfs.
> Update git filesystem to support go-git-v4.rc2

- build.sh
- cmd/root.go
- config/config.go
- cozy.dist.yaml
- cozy.test.yaml
- instance/instance.go
- instance/instance_test.go
- vfs/directory.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/apps/apps.go
- web/data/data_test.go
- web/files/files_test.go
This is a fix for the root directory creation code and `instances add`. In the current code, the directory creation on the actual file system could not work since we were using a namespaced fs to build its own root directory.
~~I left the `globalFsURL` pointing at `file://localhost/tmp/cozy2` for now. I'm working a way to pass that from the configuration (and have a way to inject configuration from tests).~~
> Fix root directory creation

- cmd/instance.go
- couchdb/couchdb.go
- couchdb/mango/index.go
- instance/instance.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files_test.go
This PR main goal is to have the definition of all VFS indexes directly inside the vfs package. This helps for tests and, IMHO, is clearer.
@aenario I changed a few of the names in `mango/index`, if you ok with that ? :
- `s/IndexDefinition/IndexFields/`
- `s/IndexDefinitionRequest/Index/`
> Move mango indexes definition inside VFS package

- README.md
Moved the CouchDB section first, so newcomers have a database
instance before running the `instances add` command.
Also added instructions to create the `storage/` directory.
Merge `--ff`?
> README: Add instructions to create the dev instance

- .gitignore
- cmd/root.go
- config/config.go
- instance/instance.go
- web/files/files_test.go
Re-implement what was the good behavior: cozy-stack should create *all* the necessary directories to run on `instances add`.
> Create all directories required on instance creation

- vfs/errors.go
- vfs/file.go
- web/files/files.go
This PR should fix a misleading error returned in certain conditions when a file is modified concurrently:
```
in case of a concurrent access to this method, it can happend
that the file has already been renamed. In this case the
safeRenameFile will return an os.ErrNotExist error. But this
error is misleading since it does not reflect the conflict.
```
@aenario waiting for your return on this one.
> [VFS] Fix error returned on a conflictual file modification

- web/router.go
This PR reorder the web router to allow `/version/` and `/status/` routes to respond even if no instance are created.
> Fix /version/ and /status/ when no instance

- cmd/serve.go
- cmd/status.go
- config/config.go
- config/config_test.go
- couchdb/couchdb.go
- couchdb/couchdb_test.go
- instance/instance.go
- instance/instance_test.go
- vfs/vfs_test.go
- web/data/data_test.go
- web/files/files_test.go
- web/jsonapi/jsonapi_test.go
- web/middlewares/instance_test.go
- web/status/status.go
- web/status/status_test.go
This PR removes all the hardcoded addresses to CouchDB url and uses the passed configuration instead.
> Effectively use configuration for CouchDB url

- .gitignore
- .travis.yml
- apps/apps.go
- apps/git.go
- couchdb/couchdb.go
- couchdb/couchdb_test.go
- instance/instance.go
- instance/instance_test.go
- vfs/directory.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/apps/apps.go
- web/data/data.go
- web/data/data_test.go
- web/files/files.go
- web/files/files_test.go
- web/middlewares/instance_test.go
Following #66 here is a first shoot at unifying all the contexts, Basically : 
- replace `dbprefix string` by a `couchdb.Database interface{GetPrefix() string}`
- replace `vfs.Context struct` by an interface extending `couchdb.Database` with `GetFS() afero.Fs`
- make Instance implements both Interfaces
- only pass reference to the instance around
- create appropriate test for each package (in couchdb a custom couchdb.Database, in vfs a custom vfs.Context, in data Instance)
> Unify Contexts

- .gitignore
- README.md
- build.sh
This PR add a deploy command to our build script. This should hopefully help to fully automate our deployment with travis.
> Add build.sh deploy command

- cmd/instance.go
- cmd/root.go
- couchdb/errors.go
- main.go
Tries to uniform a little the stdout/stderr outputs of cozy-stack.
The simple rule I tried to implement:
- use `log` formatting (with logrus) for any error or information (like success of a command etc.)
- use non log `fmt.Print` for command output that could be processed (like the table returned by `instances ls` or `config`)
> More uniform cmd output

- web/router.go
We were returning 500 on what should have been 404 errors.
> Use SetInstance middleware only when needed

- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files_test.go
This PR add a `Walk` function like `filepath.Walk` to the VFS which should come handy to browse a directory.
It also improve the vfs tests.
> Add vfs.Walk and more tests

- couchdb/couchdb.go
- docs/mango.md
Following PO testing of  [DS-13 / E-20] , we identified some issues in docs.
- Using {} selector to get all docs was a hack and broke when we forbid unoptimised queries, remove it from the docs. We should replace it by an HTTP API for couchdb.GetAllDocs (see #100)
- Sort field must be an array and match an existing index,.
And @jinroh saw that it is more efficient to `use_index`,  in [couchdb docs](http://docs.couchdb.org/en/2.0.0/api/database/find.html#index-selection)
For now, the API is just a proxy to couchdb, so we only improve docs to match API behaviour.
Later we might imagine improving API to match user expectation, like autocompleting the beginning of sort field.
> Improve mango docs

- apps/apps.go
- apps/apps_test.go
- apps/errors.go
- apps/git.go
- cmd/root.go
- config/config.go
- couchdb/couchdb.go
- couchdb/mango/query.go
- docs/apps.md
- instance/instance.go
- vfs/directory.go
- web/apps/apps.go
This PR should improve the error handling of `/apps`:
- distinguish error for manifest not reachable
- add documentation of status codes
- add documentation on the async nature of the `POST /apps/:slug` request
- set persisted manifest in `errored` state when an error ocured while installing
> [APPS] Improve error handling

- apps/apps.go
- cmd/serve.go
- instance/instance_test.go
- vfs/file.go
- web/apps/apps.go
- web/apps/apps_test.go
- web/middlewares/app.go
- web/middlewares/instance.go
- web/middlewares/instance_test.go
- web/router.go
It's work in progress. There are some known bugs and I should add some tests. But you can look at it
> Access to an app

- vfs/directory.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files.go
This PR is a little proposal to remove the `typ string` return value of the `GetDirOrFile*` functions.
It is not ideal but I think it makes it clearer that either dir or file is non nil, and avoid to have to "switch" over a string without a default case.
> Remove typ string from GetDirOrFile* return values

- apps/apps_test.go
- couchdb/couchdb_test.go
- instance/instance_test.go
- vfs/vfs_test.go
While preparing today review, I saw my couchdb was a mess, tests were not properly cleaning after themselves.
> Tests should not leave artifacts

- scripts/cozy-app-dev.sh
- web/router.go
- web/router_test.go
Add a simple CORS middleware and fix the `Host` forwarding by the proxy.
> CORS middleware

- cmd/files.go
- cmd/root.go
- couchdb/mango/index_test.go
- couchdb/mango/query_test.go
- docs/files.md
- docs/instance.md
- instance/instance.go
- instance/instance_test.go
- vfs/directory.go
- vfs/errors.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs_test.go
- web/files/files.go
- web/files/files_test.go
This PR propose to unify the usage of the words folder vs directory and uses the word directory only.
The breaking changes of this PR are:
- the remove of the notion of `io.cozy.folders` for the creation API of files and directories. It uses for the query parameter `Type` the values `file` or `directory`
- the renaming (and fixed doc) of the some directory IDs: `io.cozy.files.root-dir` and `io.cozy.files.trash-dir` (instead of `io.cozy.files.rootdir` and `io.cozy.files.trashdir`), to make it clearer for the next custom directories we'll have to introduce.
Also, for all the go code, the work `Dir` is used instead of `Directory` which was still hanging around in some function names, even if `Dir` was already mostly used.
----
If you prefer the word folder, I can change to that direction …
> Unify usage of folder vs directory and use directory

- docs/client-app-dev.md
- scripts/Dockerfile
- scripts/cozy-app-dev.sh
I removed the responsibility to launch CouchDB from the script under certain conditions. It should make it simpler.
Now the script rely on the fact that the user is responsible to launch CouchDB and accept `COUCHDB_HOST` `COUCHDB_PORT` to parameterize its address.
> Dev script should not try to launch couchdb

- scripts/cozy-app-dev.sh
Adds a `-u` flag to update the cozy-stack when launching the dev script.
Also fixes some issues with instance creation and update the usage message.
> Add -u option to update the cozy-stack in dev script

- web/apps/apps.go
- web/auth/auth.go
- web/data/data.go
- web/files/files.go
- web/middlewares/instance.go
- web/server.go
Common errors (`os.Exist` / `os.NotExit` / `couchdb.Errors` / ...) are handled in our common `HTTPErrorHandler`.
This PR mutualizes more of these types of err handling.
> Mutualize common error wrapping

- couchdb/changes.go
- couchdb/changes_test.go
- couchdb/couchdb_test.go
- web/data/data.go
- web/data/data_test.go
This is the first step in allowing couch protocol replication from and to cozy-stack.
There is no documentation for it as the only guarantee we make on this API for now is "It will allow a couchdb or pouchdb to replicate from a cozy" 
What differs from exploration : 
I added style=all_docs support, as couchdb 2 seems to use it in replication
> Add _changes API

- .travis.yml
- couchdb/couchdb.go
- web/data/data.go
- web/data/data_test.go
- web/data/permissions.go
- web/data/replication.go
- web/data/replication_test.go
Simply handles the following routes by proxying to couchdb.
```
GET /:doctype/
GET /:doctype/_changes
POST /:doctype/_changes
POST /:doctype/_ensure_full_commit
GET /:doctype/_bulk_get
GET /:doctype/_local/:docid
PUT /:doctype/_local/:docid
```
> Make cozy-stack a couchdb replication source

- cmd/client.go
- cmd/config.go
- cmd/files.go
- cmd/instances.go
- cmd/root.go
- cmd/serve.go
- config/config.go
- cozy.dist.yaml
- docs/config.md
- instance/instance.go
- scripts/cozy-app-dev.sh
- web/instances/instances.go
- web/middlewares/basic_auth.go
- web/routing/routing.go
- web/server.go
This PR adds an administration endpoint on a separate port (6060 by default).
This administration offers for now the possibility to handle instances through an HTTP API:
- `POST /instances/?Domain=...`
- `GET /instances/`
- `DELETE /instances/:domain`
The `instances` cli command uses has been changed to use this API.
> Add administration api and rely on it for instances cli

- web/auth/auth.go
- web/auth/auth_test.go
If the user is not yet logged in when he starts the OAuth2 authorization code flow, he will be redirectered to the login page with a `redirect` parameter that will be rejected. This PR fixes this and allow the user to complete the OAuth2 flow.
> Fix the OAuth redirectionss for a user not yet logged-in

- docs/auth.md
- web/auth/auth.go
The trust on first use principle is useful when using OAuth as
authentication (OpenID), and when there are many users using the same
OAuth2 server. It's not the case for Cozy, so we can skip this part.
> Remove the TODO about trust on first use

- pkg/apps/git.go
- pkg/vfs/vfs.go
This PR should fix the new go-git package (File struct has changed of package).
It also fixes `OpenFile` func used with `O_CREATE` flag when the file already exists.
> Fix go-git

- scripts/integration.sh
I just saw the integration does not pass, but because the bash script was not properly passing its exit code, travis was green. 
This should both fix error reporting & the bug in travis.
> Fix pouchdb integration tests

- web/data/data.go
- web/data/data_test.go
- web/data/replication.go
- web/data/replication_test.go
Turns out the previous fix did not work with the way echo routes.
This should allow replicating any db, even if it contains _design doc.
Working on adding tests for this.
> Fix replication of _design doc

- pkg/apps/apps.go
- pkg/apps/git.go
- pkg/apps/installer.go
- pkg/apps/installer_test.go
- pkg/vfs/directory.go
- web/apps/apps.go
This PR adds the possibility to upgrade an application. The version comparison between to manifest is done by a simple string comparison (no order).
The modifications of the application files is still clunky since we do not have yet a proper `Remove` method implemented. It only adds and/or override the files, without deleting removed ones.
Testing is done with a local git daemon.
> Allow to update a git application

- cmd/files.go
- pkg/apps/apps.go
- pkg/apps/installer_test.go
- pkg/consts/consts.go
- pkg/couchdb/errors.go
- pkg/instance/instance.go
- pkg/instance/instance_test.go
- pkg/settings/settings.go
- pkg/settings/settings_test.go
- pkg/vfs/directory.go
- pkg/vfs/file.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
- web/auth/access_code.go
- web/auth/auth.go
- web/auth/auth_test.go
- web/auth/client.go
- web/auth/session.go
- web/data/permissions.go
- web/files/files.go
- web/files/files_test.go
This PR adds a `pkg/consts` package containing global identifiers that we use throughout the projet. Mainly the `io.cozy.*` doctypes. Moving them in a separate package has two main advantages:
- prevent circular dependencies just to import a const string
- prevent importing the whole package just to import small consts (for a client for instance)
> Move global consts in their own package

- scripts/cozy-app-dev.sh
Removed the "error:" prefix, added a newline and made the message clearer.
> Make hosts message clearer in dev script

- docs/client-app-dev.md
While it's actually obvious to many, a little mistake like not pointing to the right directory can waste a lot of time!
> Add a tip to run an application in dev mode

- pkg/crypto/scrypt.go
- pkg/crypto/scrypt_test.go
- pkg/instance/instance.go
- web/middlewares/basic_auth.go
Just stumbled across the passphrase update mechanism (in case the scrypt attribute are changed and the hash needs to be updated) and was a bit confused.
The changes in this PR:
- remove the `UpdateHash` method (which is more a `ShouldUpdateHash`)
- make the `CompareHashAndPassphrase` return a `needUpdate` boolean along with an error
This has two advantages:
- do not require double hash checking (one by `Compare` and the other by `UpdateHash`) on each passphrase check (in case of a success)
- "force" the user of the `CompareHashAndPassphrase` method to handle the case where the hash is outdated
> Handle passphrase hash update differently

- cmd/files.go
- cmd/instances.go
- cmd/serve.go
- pkg/instance/instance.go
- pkg/instance/instance_test.go
- pkg/sessions/session.go
- scripts/cozy-app-dev.sh
- scripts/integration.sh
- web/apps/apps.go
- web/apps/apps_test.go
- web/auth/auth.go
- web/auth/auth_test.go
- web/data/data_test.go
- web/files/files_test.go
- web/instances/instances.go
- web/server_test.go
This PR add many tweaks to improve the development on the stack:
- notion of development instances with a dev flag
- the dev script now automatically register a new "cozy.local:8080" instance with a password "cozy"
- the cookies are functional even on instances with a port in the name
- removed the special instance named "dev" for "localhost" and "127.0.0.1" hosts
> Add development instances to help development on the stack

- cmd/client.go
- cmd/config.go
- cmd/files.go
- cmd/instances.go
- cmd/root.go
- pkg/config/config.go
- pkg/couchdb/couchdb.go
- pkg/crypto/scrypt.go
- pkg/instance/instance.go
- pkg/jobs/errors.go
- pkg/jobs/jobs.go
- pkg/jobs/mem_jobs.go
- pkg/jobs/mem_jobs_test.go
- pkg/jobs/worker.go
- pkg/jobs/workers_list.go
- pkg/oauth/client.go
- pkg/permissions/claims.go
- pkg/sessions/session.go
- web/apps/apps.go
- web/errors/errors.go
This PR adds timeout and retry with backoff for jobs workers:
- timeout is handled by giving the worker a timeout chan. we have to trust the worker to timeout properly by reacting to this channel since it is not possible from an outside observer to stop a go-routing
- retry has three parameters:
- `MaxExecCount`: the maximum total number of time the worker is executed
- `MaxExecTime`: the maximum total amount of time it is allowed to spin on a job
- `RetryDelay`: the initial retry delay applied between each retry. the delay is calculated by `RetryDelay * 2^(ExecCount-1) * (1 + RandomNum(-0.2, 0.2))`
> Add jobs timeout and retry with backoff delay

- cmd/config.go
- pkg/config/config.go
- pkg/utils/utils.go
Now that we have a `utils` package, we can move some general methods in it.
This PR moves `UserHomeDir`, `FileExists` and `AbsPath` which are mostly utils functions for the CLI or config.
> Move some methods to the utils package

- .gitignore
- assets/externals
- scripts/build.sh
- web/routing/routing.go
Add a simple step to the build script to download assets described in `assets/externals` file.
This step is called with the before the `release` command or using the new `assets` command.
> Add an asset handling step on build.sh script

- docs/jobs.md
- pkg/consts/consts.go
- pkg/jobs/jobs.go
- pkg/jobs/mem_jobs.go
- pkg/jobs/worker.go
- web/jobs/jobs.go
- web/jobs/jobs_test.go
- web/jsonapi/data.go
Includes commits from #200 
This PR adds the possibility to watch jobs state from `POST /jobs/queue/:worker-type` with and `Accept: text/event-stream` header.
It also adds the endpoint `GET /jobs/queue/:worker-type` returning the number of elements currently in the queue.
> Jobs eventstream and queue size

- pkg/apps/git.go
- pkg/apps/installer_test.go
- pkg/couchdb/couchdb.go
It is safer to have a timeout on HTTP clients, to avoid stuck connections when a service is down.
See https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
> Add a timeout to couchdb and apps http clients

- pkg/apps/apps.go
- pkg/apps/apps_test.go
When installing an application which does not define complex routing,the default route created is 
```
"routes":{"/":{"folder":"/","index":"index.html","public":false}}}
```
The current version of FindRoute does not match this route with /any/other/path.txt
> [Bug] Fix routing of files for default app route

- web/middlewares/bearer_token.go
This PR makes the Bearer "parsing" constant time (using `strings.HasPrefix` instead of `strings.Split`).
The diff is better watchable [without whitespaces](https://github.com/cozy/cozy-stack/commit/13175f79f06fec68d739a6fcc3a8af5fec3a743f?w=0)
> Splitting of Authorization header in constant time

- pkg/jobs/errors.go
- pkg/jobs/mem_jobs_test.go
- pkg/jobs/worker.go
- pkg/jobs/workers_list.go
As suggested by @aenario, this PR uses `context.Context` to handle jobs timeout.
> Jobs: use context instead of timeout channels

- pkg/instance/instance.go
It is better to always create the settings document for instance, even if empty. It makes the /settings/instance endpoint easier for clients with the locale hack (ie the locale is stored in the instance itself, not in the settings document, so it's weird to have a 404 or no revision when asking for /settings/instance when there is a locale but no timezone/email).
> Always create the settings for an instance

- cmd/root.go
- cozy.dist.yaml
- pkg/config/config.go
- pkg/jobs/jobs.go
- pkg/jobs/worker.go
- pkg/jobs/workers/mail.go
- pkg/jobs/workers/mail_test.go
- web/jobs/jobs.go
This PR adds a `sendmail` and a `sendmail-template` workers to send mails.
The sendmail-template accepts a template html string along with values. It may be not really useful as is, but could become interesting with a preset of predefined HTML templates.
> Add sendmail worker

- cmd/instances.go
- main.go
- web/instances/instances.go
Adds a generic endpoint `GET /instances/token` to generate different kinds of tokens together with two commands:
- `cozy-stack instances token-app [domain] [slug]`
- `cozy-stack instances token-oauth [domain] [clientid] [scopes]`
> Commands app-token and oauth-token

- docs/konnectors.md
To much detail, not enough. Remarks are welcome!
> Study about konnectors isolation solutions

- docs/cli/cozy-stack_serve.md
I believe this is a typo in the flag name.
> [fix] Typo

- pkg/consts/consts.go
- pkg/sharings/errors.go
- pkg/sharings/recipients.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/routing.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This adds the possibility to create a new sharing through a `/sharings/` route.
A new sharing structure is defined, as well as a recipient structure and the link between them.
Some tests are added for the `web` and `pkg` part.
Note that no verification is done on the shared documents, I think it should be done in the permission part (check the documents exist, etc).
> Add sharing creation

- pkg/sharings/errors.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
Add a sharing request reception handler. 
It covers the case where a recipient received a mail with an URL containing the sharing informations in the query-string and clicked on this URL (the actual sending mail PR will come soon).
A sharing document is then created in the recipient database, which will be later used to ask the recipient if he accepts the sharing or not.
> Sharing request

- pkg/sharings/sharings.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
When a recipient receive a sharing request throught an URL sent by mail, he is redirected to the OAuth authorize page, based on the information specified in the query string. 
This is done in addition to the sharing document creation.
> Add sharing authorization

- client/apps.go
- web/apps/apps.go
The eventstream parser would crash in case an error string contains newlines. This PR fixes this issue by encoding the error string in JSON.
> Make the apps eventstream a little more robust

- pkg/apps/installer_test.go
- pkg/consts/views.go
- pkg/couchdb/couchdb.go
- pkg/couchdb/couchdb_test.go
- pkg/couchdb/mango/index.go
- pkg/couchdb/mango/index_test.go
- pkg/instance/instance.go
- pkg/permissions/permissions.go
- pkg/vfs/references.go
- pkg/vfs/vfs.go
- pkg/vfs/vfs_test.go
- web/data/replication_test.go
- web/permissions/permissions_test.go
This PR is a little refactoring to store all the views and indexes declarations into the `consts` package. It should offer a clearer view of all the indexes and views that are defined by the stack.
The `ExecuteView` method takes a `View` pointer which make it also less error-prone.
The `instance.Create` function has been inlined to so that it is easier to see all the creation steps it goes though.
> Move indexes and views declarations in const package

- pkg/utils/utils.go
- pkg/utils/utils_test.go
- web/instances/instances.go
Since `strings.Split("", ",")` is the array `[]string{""}`, the CLI `cozy-stack instances add "foo.bar"` would try to install an app and result in the error `Failed to install Unknown app`.
> Fix --apps flag when used as empty string

- pkg/realtime/memhub.go
- pkg/realtime/memsub.go
- pkg/realtime/memtopic.go
- pkg/realtime/realtime.go
- pkg/realtime/realtime_test.go
Fixes on the realtime package:
- goroutine leak in the topic loop (not released)
- asynchrounous send with fixed size buffer for `subscribe`/`unsubscribe` channels (instead of goroutines)
- close/send race on the `send` channel, guarded with an atomic state
> Realtime fix

- pkg/apps/installer_test.go
- pkg/consts/consts.go
- pkg/consts/views.go
- pkg/couchdb/couchdb.go
- pkg/instance/instance.go
- pkg/sharings/errors.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/data/data_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This handles a refused sharing answer on the sharer side to eventually update the recipient sharing status.
For this end, a mango index is used to retrieve the sharing document from the state parameter, and then the recipient from the client_id parameter.
> Handle refused sharing answer

- pkg/sharings/send_mails.go
- pkg/sharings/send_mails_test.go
If the url specified in the recipient's structure is not prefixed by
either "http" or "https" the button generated in the invitation email
cannot be correctly handled.
This PR fixes this problem by prefixing it by the appropriate value,
depending on `instance.Scheme()`. If the url is already prefixed then
nothing is changed.
> Set http prefix to url in sharing mail

- pkg/sharings/errors.go
- pkg/sharings/send_mails.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This PR adds a route POST /sharings/formRefuse that, once called, will
trigger the refusal of the sharing.
This refusal is divided into two steps:
1. Deleting the corresponding sharing document;
2. Informing the sharer of the refusal.
> A recipient can refuse a sharing

- pkg/instance/instance.go
- pkg/sharings/errors.go
- pkg/sharings/recipients.go
- pkg/sharings/send_mails_test.go
- pkg/sharings/sharings_test.go
- tests/testutils/test_utils.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This allows to create a sharing recipient throught a `POST sharings/recipient` route. 
It triggers the creation of the recipient in the sharer database, and the OAuth registration of the sharer to the Cozy's recipient.
Note that the` public_name` option in the instance settings has been added, as it is needed for the OAuth `client_name` parameter.
> Sharing recipient creation 

- pkg/sharings/send_mails.go
- pkg/sharings/send_mails_test.go
The url's link in the mail must have its path equal to
"/sharings/request".
This PR fixes this mistake and adds a test that verify that the produced
link is correct.
> Fix request url in mail invitation

- web/data/data.go
In a third party application with pouchdb, there is `_changes` request sent to know changes.
Sometimes (chromium Version 57.0.2987.110) this request sends an extra query parameter for cache purpose called `_nonce` and containing a request hash.
That is the very reason I suggest this PR.
> fix: new query parameter added in _changes request

- pkg/sharings/recipients.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/auth/auth.go
- web/auth/auth_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This allows to handle a recipient's sharing answer on the sharer side.
From the user point of view, he is redirected to his own Cozy, after being redirected to the sharer Cozy.
Behind the hoods, the answer triggers an `access_token` request to the recipient and an update in database with the new credentials and recipient status.
Note the `auth/authorize` redirection has been completed with a the `client_id`, as it is required by the sharer to identify the recipient.
> Sharing acceptation handler

- pkg/instance/instance.go
- web/files/paginated.go
This PR fixes (like #400) contains a temporary fix for the migration to our new index naming system in couchdb.
It also fixes a null value returned by the data relationship in the jsonapi representation of a directory.
> Create index on get

- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
This allows a sharing recipient to receive the documents in his Cozy after he gave the authorization.
Note that it doesn't use the CouchDB replication protocol as initially planned, because some work is still needed at the stack level.
> Send documents after sharing acceptation

- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
We need to be able to access the sharer's information from the sharing
document: this is what this PR adds.
The `sharer` structure is filled when a sharing request is received by a
recipient. It is composed of the id of the sharer's OAuth Client (at the
recipient's) and of the sharer's URL of her Cozy.
Tests where updated accordingly.
> Add sharer structure

- pkg/sharings/recipients.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
The refused sharing answer handler on the recipient side used to make a POST to the sharer. 
This changes the request to follow the same behaviour than the accepted sharing answer, i.e. an HTTP redirect to the sharer endpoint.
> Fix refused sharing answer

- pkg/jobs/workers/sharing.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
A sharing worker is triggered on documents updates specified by the sharing permissions.
The trigger creation is done just after the sharing accept.
Note that the worker does nothing yet, this will be implemented in a future PR.
> Sharing worker creation

- pkg/apps/installer.go
- pkg/couchdb/couchdb.go
- pkg/couchdb/errors.go
- pkg/instance/instance.go
- web/data/data.go
- web/data/data_test.go
To facilitate retro-compatibility when adding new doctypes, the `couchdb.IsNotFoundError` now also returns true when the database does not exist.
It fixes the konnectors installation with no created `io.cozy.konnectors` database on instance creation.
> Handle no-database error from couch as notfound errors

- scripts/Dockerfile
- scripts/cozy-app-dev.sh
We need to make cozy-stack listens on 0.0.0.0 inside docker to be accessible from outside the docker image
> Fix cozy-app-dev docker image

- client/request/request.go
- cmd/apps.go
- pkg/apps/installer.go
- pkg/apps/installer_test.go
- pkg/instance/instance.go
- web/apps/apps.go
This PR improves the error handling of the installation / update of applications. On the server-side the installer is given on "Operation" type to better check the manifest existence only if necessary (update/delete). On the API/Client side, the error are always returned in a `text/event-stream` format if required by the client.
> Improve error handling of apps install/update

- docs/INSTALL.md
Edited the example in INSTALL.md:
* Replaced `localhost` with `cozy.tools` in example to prevent cookie hell
* Added `--passphrase` to the example
> Replace localhost with cozy.tools and add passphrase to example

- pkg/apps/git.go
- pkg/apps/installer.go
- pkg/apps/installer_test.go
- pkg/instance/instance.go
- web/apps/apps.go
- web/apps/serve.go
- web/server.go
This PR moves the apps and konnectors storage out of the VFS index.
For retro-compatibility reason, the `.cozy-apps` and `.cozy-konnectors` are stilled used and stored in the VFS directory of the user.
The `swift` filesystem is not yet implemented.
> Move apps/konnectors data out of the VFS

- pkg/apps/apps.go
- pkg/apps/konnector.go
- pkg/apps/webapp.go
- pkg/couchdb/reference.go
- pkg/instance/instance.go
- pkg/jobs/errors.go
- pkg/jobs/trigger_at.go
- pkg/jobs/trigger_cron.go
- pkg/oauth/client.go
- pkg/permissions/permissions.go
- pkg/sharings/recipients.go
- pkg/sharings/send_mails_test.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- pkg/vfs/archive.go
- pkg/vfs/file.go
- web/apps/apps.go
- web/data/references.go
- web/data/references_test.go
- web/files/files.go
- web/files/paginated.go
- web/files/referencedby_test.go
- web/instances/instances.go
- web/jsonapi/data.go
- web/jsonapi/jsonapi.go
- web/permissions/permissions.go
- web/settings/clients.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
Remove almost all dependency from "/pkg" to "/web".
Only remaining dependency is in pkg/sharings which needs to setup a fake remote cozy to communicate with.
Use the apiXXX technique to remove dependency to jsonapi & a new couchdb.DocReference which replace jsonapi.ResourceIdentifier.
> [refacto] Clean package graph 

- pkg/jobs/workers/sharings/sharing_updates.go
- pkg/jobs/workers/sharings/sharing_updates_test.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
This adds the possibility to define a dynamic sharing throught the use of `selector`, for JSON documents.
This is done at the trigger creation, once the sharing is accepted.
Note this PR relies on #466.
> Dynamic sharing support

- pkg/consts/consts.go
- pkg/jobs/workers/sharings/share_data.go
- pkg/sharings/sharings_test.go
- pkg/vfs/couchdb_indexer.go
- pkg/vfs/vfs.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl.go
- web/data/data.go
- web/files/files.go
- web/sharings/files.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This PR adds a route `/sharings/doc/:doctype/:id` that will handle the
documents sent by the sharer. Depending on the doctype either the
request is transmitted to `/data` or our custom handler (for the
creation of a file/dir with an id) is called.
This route was added because we need to modify the parent of an incoming
file/dir and set it to "Shared With Me" as we don't want to propagate
the entire hierarchy with a document.
We created a custom handler that heavily resembles that of files because
we need to be able to predefine the id of a file/dir for synchronisation
purposes. To do so we had to add two new functions to the interface of
the indexer and update the vfs implementation.
The list of changes is:
* consts.go: add `SharedWithMe` constant.
* share_data.go: the functions `SendDoc` …
> A recipient can receive a sharing.

- cmd/instances.go
- pkg/consts/views.go
- pkg/couchdb/couchdb.go
- pkg/couchdb/cursor.go
- pkg/couchdb/cursor_test.go
- pkg/instance/cache_test.go
- pkg/instance/instance.go
- pkg/permissions/permissions.go
- pkg/vfs/couchdb_indexer.go
- pkg/vfs/vfs.go
- web/data/references.go
- web/files/files.go
- web/files/files_test.go
- web/files/paginated.go
- web/files/pagination_test.go
- web/jsonapi/data.go
- web/jsonapi/jsonapi.go
- web/jsonapi/jsonapi_test.go
- web/permissions/permissions.go
This adds a meta:count to the contents  relationships of a folder. 
We also introduce a separate route to fetch more of this relationships.
Improved couchdb.Cursor to  support both skip & cursor, this will allows supporting both kind of pagination for all routes using couchdb.Cursor.
Note @nono I added a couple "TODO change me for flag hidden" which will require revision when introducing `hidden` flag.
> Add supports for skip pagination on /files/

- client/apps.go
- docs/apps.md
- docs/client-app-dev.md
- pkg/apps/webapp.go
- web/apps/serve.go
So we can use it to display the name of the app in the Cozy-bar
> feat: Add app.editor reading from manifest

- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
At the dynamic sharing creation, one needs to create and request a mango index based on the selector to retrieve all the docs concerned by this sharing, before being sent to the recipients.
> Docs retrieval at dynamic sharing creation

- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
- web/data/data.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
With a previous PR two regressions were introduced: it was no longer
possible to share a JSON, and its updates were not propagated. This PR
fixes those issues and enhance the propagation of updates as it is now
possible for a sharer to propagate the deletion of a shared document.
> Share and update JSON documents

- cozy.example.yaml
- pkg/apps/copier.go
- pkg/apps/git.go
- pkg/apps/installer.go
- pkg/workers/konnectors/konnector.go
- scripts/konnector-rkt-run.sh
- scripts/konnector-run.sh
This PR add a new konnector executing script designed for RKT.
It also contains two fixes for konnector and webapps installation:
- fix a leak of empty temporary files (copier were not properly closed)
- fix a bad state manifest, preventing a delete/upgrade a konnector that would have failed to install
> Konnector rkt run

- docs/konnectors_workflow_example.md
- pkg/workers/konnectors/konnector.go
- pkg/workers/konnectors/konnector_test.go
- scripts/konnector-rkt-run.sh
Seen with @doubleface, it is preferable that the instance gives the url of the cozy instead of the domain only in the case the instance is a `dev` instance and is served over http.
> Use COZY_URL instead of COZY_DOMAIN

- pkg/sharings/recipients.go
- pkg/sharings/send_mails.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This declares a route in order to add a recipient to an existing sharing.
The sharing process is then triggered, with the recipient registration and a mail sent to the its given address.
> Add route to add a sharing recipient

- web/data/data.go
- web/data/data_test.go
Needed for the front to access data about a konnector or an app.
> Allows manipulating docs with slash in _id from /data

- pkg/sharings/recipients.go
- pkg/sharings/send_mails.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
In a Master-Master sharing context, the recipient must register an OAuth client to the sharer, as it will be necessary for the recipient to have access on the sharer docs.
This PR implements this registration, just after the sharing request is received on the recipient side. It then sends the generated `client_id` to the sharer, for him to save it in his sharing document.
Note this relies on #502
> Register the recipient for master-master sharing

- pkg/sharings/send_mails.go
- web/sharings/sharings.go
This fixes 2 things:
- Add a new sharing recipient doesn't trigger a new mail to the existing recipients for this sharing
- A nil recipient doesn't cause jsonapi to crash for a nil pointer reference
> Fix sharing recipient adding

- docs/konnectors_workflow_example.md
- pkg/apps/installer.go
- pkg/apps/konnector.go
- pkg/workers/konnectors/konnector.go
Pass the `COZY_TYPE` as env var to be able to distinguish different konnector types.
> Pass the COZY_TYPE as env var

- client/client.go
- client/instances.go
- client/request/request.go
- cmd/root.go
- scripts/cozy-app-dev.sh
This PR makes the `cozy-stack` CLI use the `config.ServerAddr()` address to perform its HTTP connection, instead of the domain of the instance.
This address can be overridden with the `--host` and `--port` flags, which default to `localhost:8080`.
> Default to localhost for CLI

- docs/client-app-dev.md
The cozy client is now namespaced inside `cozy`, as mentioned [here](https://github.com/cozy/cozy-client-js/tree/master/docs#cozyclientinitoptions)
> fix: outdated docs

- client/request/request.go
- cmd/root.go
This PR removes the https default scheme used for the CLI. This change takes place after #544, which make use of the local server addressing by default.
> Remove https fallback for CLI since we use server address by default

- docs/permissions.md
- web/apps/apps.go
- web/permissions/permissions.go
This PR adds a route to modify the webapps and konnectors permissions. It also add the `permissions` field to the konnector JSON-API representation, like described in the konnector workflow document.
> Add a route to modify apps/konnectors permissions

- pkg/sharings/errors.go
- pkg/sharings/recipients.go
- pkg/sharings/sharings.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This completes en ends the master-master OAuth support.
After a sharing being accepted and the answer received on the sharer side, an access code is generated and sent to the recipient. He then asks the sharer for an access token, and save it in database.
Note this relies on #516
> Add master-master sharing token exchange

- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- web/sharings/files.go
This adds the possibility to define a `referenced_by` selector, which is useful for album sharing.
It sends the `references_by` attributes to the recipient, for him to check the associated permissions. 
Note that at the sharing creation, the `Title` permission field is used to know which doctype is referenced, needed to query the referenced view. I'm open to suggestions for a better way to get this doctype.
> Add album sharing support

- client/files.go
- pkg/sharings/sharings.go
- pkg/vfs/vfs.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- web/files/files.go
- web/sharings/files.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
With this PR when a file is shared in Master-Slave it will be updated at
the recipients' accordingly to what the sharer does.
A problem exists with the `UpdatedAt` field which is not automatically
updated when a file is, so the test in the `vfs` package was replaced by
an error log.
> Share files updates

- pkg/permissions/errors.go
- pkg/permissions/permissions.go
- pkg/permissions/permissions_test.go
- pkg/permissions/verbs.go
- web/permissions/permissions.go
This PR uses more specific error messages for modifying/revoking permissions.
It also should fix the parsing of the verbs set shortcut `["ALL"]`.
> Clearer errors messages and fix parsing of verbs set

- pkg/vfs/vfs.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- web/sharings/files.go
- web/sharings/sharings_test.go
Before this PR the recipients and the sharer would have different dates
for the shared files: the recipients would set the `createdAt` date to
when they received a file, and `updatedAt` to when they received an
update.
Now both the sharer and the recipients have the same `createdAt` and
`updatedAt` dates.
> Use same `createdAt` and `updatedAt` dates

- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl.go
In some cases (large files), image.DecodeConfig will return sooner, so we closes the reader part of the Pipe. which causes a io.ErrClosedPipe on next Write, which cause loss of metadata. This fixes that.
> Fix meta extraction for large file

- client/auth/auth.go
- pkg/sharings/recipients.go
- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/sharing_updates.go
The sharing was broken in https because the scheme is no longer deduced since #548.
This fixes the issue by adding the scheme for each http(s) request.
> Add request scheme

- pkg/permissions/rule.go
- pkg/sharings/errors.go
- pkg/sharings/sharings.go
- pkg/vfs/permissions.go
This adds the possiblity to define a permission Value embedding the
referenced doctype with the id, separated by a '/'. It is useful for
permissions with a `referenced_by` as a selector.
> Add permission syntax for referenced_by doctype

- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/sharing_updates.go
- web/sharings/sharings.go
This implements an actual master-master sharing, i.e. the changes are synchronized from both the sharer and recipient.
This supports creation, updates, and deletes on JSON documents. Full files support will come later.
> Add master-master sharing support for JSON documents

- assets/externals
We will need `piwik.js` to get analytics from usage as explained in https://trello.com/c/zUe4D0KA/269-2-glob-7-traces-d-usage
We tought we could use `piwik.js` by implementing different solution:
Do you think we choose the best solution?
> chore: add piwik.js as an external lib

- pkg/consts/consts.go
- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
- web/sharings/files.go
- web/sharings/sharings_test.go
This PR introduces the necessary code to propagate what we call the
"folders hierarchy": if Alice shares a folder containing subfolders then
the recipient should retrieve the same structure, and if changes are
made they should also be propagated.
In addition this PR introduces the possibility to create specific
folders other than "Shared With Me". It will be used for photos in
particular.
> feat: folders hierarchy in sharing

- pkg/workers/sharings/share_data.go
- web/sharings/files.go
This deals with PUT/PATCH/DELETE on files, both on the sharer and recipient side.
It is able to detect if a remote file is different after a local change, and mitigate the modification.
Note this is based on #575.
> Support master-master sharing for files

- pkg/couchdb/couchdb.go
- pkg/couchdb/couchdb_test.go
- pkg/realtime/realtime.go
- pkg/scheduler/trigger_event.go
- pkg/sharings/sharings.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
This does several things:
- Change the `UpdateDoc` behaviour to get the old doc and emit through `rtevent`
- Add an `OldDoc` field in the `Event` struct
- Add a check in the `trigger_event` to see if the `OldDoc` is Valid
- Compare the references between the local and remote files, to know if the sharing worker needs to send a DELETE request to the remote.
- Add some tests
> Support photo suppression in shared album

- pkg/workers/konnectors/konnector.go
It looks like 30s it not enough for konnectors (the rkt image is slow to load)
> Increase the timeout for konnectors

- pkg/consts/views.go
- pkg/permissions/permissions.go
- web/permissions/permissions.go
- web/permissions/permissions_test.go
Following /permissions/doctype/:doctype two routes were added to fetch
the list of permissions associated to Cozy-to-Cozy sharings.  The first
one fetches the list of permissions for sharings for which the user is a
recipient ("sharedWithMe").
The second one fetches the list of permissions for sharings for which
the user is the sharer ("sharedWithOthers").
For clarity the route /permissions/doctype/:doctype was renamed to
/permissions/doctype/:doctype/sharedByLink.
> feat: Get permissions for Cozy-to-Cozy sharings

- web/sharings/files.go
Some sharing PATCH were failing because of an `UpdatedAt` inferior of the `CreatedAt`. 
To prevent any problem, this PR takes the current `UpdatedAt` value if the incoming one is inferior to the `CreatedAt`.
> Prevent failed sharing because of incorrect time

- client/instances.go
- cmd/instances.go
- pkg/instance/instance.go
- pkg/instance/instance_test.go
- pkg/sharings/sharings_test.go
- pkg/vfs/vfsswift/impl.go
- pkg/workers/sharings/share_data_test.go
- tests/testutils/test_utils.go
- web/instances/instances.go
- better printings of the `instances ls` command using `tabwriter`
- better resilience of the `instance.Destroy` command should not fail and leave the couchdb state in an intermediate state
- deleting an instance based on swift now also deletes the containers associated with it
> Improvements for instance deletions

- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/sharing_updates.go
It has the side effect to support photo album adding. As this is viewed as an update on the file, with a new `referenced_by`, the sharing worker will try to fetch the file from the remote, fail, and thus POST the file.
> Send file when remote doc is not found

- pkg/vfs/vfsswift/impl.go
When `BulkDelete` is used with an empty list, `Swift` answers with a weird `Length missing` error. This PR should fix it.
> Fix destroying a file in swift

- scripts/Dockerfile
I think that the docker entrypoint will change less often than the cozy-stack binary, so it should be before to avoid re-uploading / re-downloading its docker layer when the image is updated
> Improve docker image

- pkg/apps/copier.go
- pkg/apps/server.go
- pkg/config/swift.go
- pkg/vfs/vfsswift/impl.go
- pkg/vfs/vfsswift/thumbs.go
This PR also switches to a [fork](https://github.com/cozy/swift) of the swift library fixing a bug in the `BulkDelete` method, preventing from deleting objects which names contained a white space.
cf: https://github.com/cozy/swift/commit/3e216a7ab367dd8fc804fb43f484962004f36f49
> Add md5 field when uploading a file to swift

- pkg/consts/consts.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- web/sharings/files.go
- web/sharings/sharings_test.go
If a document is removed from a sharing that document would be deleted
from the Cozy of the sharer if it's a recipient that removed it in the
first place. This is a behavior we do not want so this PR fixes it.
> fix: Do not remove file from sharer's Cozy

- pkg/couchdb/couchdb.go
- pkg/workers/sharings/share_data.go
- web/sharings/files.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
With this PR it is possible to share several times the same document. We
detect that a document is reshared when we try to fetch it: we receive a
403 error — the document already exists but we can't access it.
When we receive such error we send the document as is if it was a
creation and the recipient will interpret it as an update.
> feat: a document can be reshared

- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
When Alice shares a photo with Bob through a Master-Master sharing,
Bob's Cozy starts the sharing_update worker. It sees this event as a
creation and tries to send that very same photo to Alice. This led to
errors in the stack log.
This PR fixes this behavior: when we send a file we first try to get it
and unless we receive a 404 or 403 error we abort.
> fix: prevent consecutive sendings

- assets/templates/login.html
Internet Explorer and Edge do not support HTML5 form.
You can check it on http://html5test.com/
So, either we update html markup to wrap all inputs into the form element (this very PR), either we add some crappy JavaScript code to trigger the form submission on button click.
> fix: IE11 does not handle HTML5 form attribute

- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
We had an unwanted behavior: if a recipient removes a document from a
sharing it would be automatically trashed even if it is still shared
somewhere else.
Now we first check that it is not shared anymore before removing it.
To do so the structures declared in pkg/workers/sharings were moved into
pkg/sharings so that the latter could be imported in the former.
> fix: remove doc from recipient only if not shared

- client/auth/auth.go
- pkg/sharings/recipients.go
- pkg/sharings/send_mails_test.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
- web/sharings/sharings_test.go
When a sharing request fails with an authentication error (400 or 401), a token renewal is performed, before retrying the request.
Note this is based on #673
> Refresh token after auth error during sharing

- pkg/consts/consts.go
- pkg/sharings/send_mails.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This PR introduces the following feature: the sharer can now revoke a
recipient. To do so one needs to call the newly created route:
`DELETE /sharings/:id/recipient/:recipient-client-id`
The "recipient-client-id" is the id of the OAuth client of the recipient
for this sharing.
> feat: Revoke a recipient

- pkg/scheduler/redis_scheduler.go
- pkg/scheduler/trigger_event.go
This PR fixes a missing closing of an event subscription that would cause deadlocks when creating/deleting multiple times the same instance.
/cc @aeris
> Fix missing close of the event subscription

- pkg/workers/konnectors/konnector.go
We have some messages "Could not parse as JSON" in our logs. I think it comes from a debug or error messages that contains a `\n`, but it's hard to tell what/where without the message.
> Add a debug line for konnector

- .travis.yml
I hope it will help to have a stable travis build
> Use node 6 to have a prebuilt version of leveldown

- assets/locales/en.po
- pkg/instance/instance.go
Hi! There was a small english mistake in one of the default folder names.
I'm unsure about the complete process here; I think since the translation id changes, I'll need to update the other languages on transifex after the PR is merged. Is that correct?
> fix: english text

- pkg/consts/consts.go
- pkg/sharings/settings.go
- pkg/sharings/settings_test.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates_test.go
- web/sharings/files.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This PR adds the possibility to choose the sharing directory for a given
app and doctype.
To enable that we made the following modifications:
* the application slug is now included in the sharing document;
* the sharingID is now transmitted in all requests to be able to fetch
the application slug at the recipient;
* a settings document was created for sharing;
* a route was added to set the destination directory given an
application slug and a doctype.
> feat: Choose sharing destination directory

- pkg/vfs/download_store_test.go
- pkg/vfs/vfs_test.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl.go
- pkg/workers/sharings/share_data.go
Also prevent from adding a file with a -1 size in the index.
> Swift: delete backup versions before object and better error handling

- pkg/instance/instance.go
- pkg/sharings/recipients.go
- pkg/sharings/send_mails.go
- pkg/sharings/sharings_test.go
This avoids to block the sharing if the public name is missing. Instead, we use the first part of the domain as a default public name. For instance, zoebellot.mycozy.cloud -> zoebellot
> Use domain as public name if missing

- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
For each update regarding a shared document, don't try to share with the revoked recipients.
> Ignore revoked recipients

- pkg/couchdb/couchdb.go
- pkg/sharings/sharings.go
Defaults the "field" parameter to "_id" if it is empty. We had a problem
in the sharings because of that.
> fix: valid function with empty field/selector

- web/data/data.go
- web/data/replication.go
@aenario do you see why we didn't allow `include_docs` on the changes feed before? Just because nobody asked us? Or is there a good reason?
> Allow to use include_docs on the changes feed

- docs/data-system.md
The route was already present, but the documentation was missing.
> Document POST /data/:type/_all_docs

- pkg/workers/konnectors/konnector.go
This PR makes sure we do not allow an executable file to be installed in the konnector workdir. It also fixes a leak of non-closed file.
> No exec file in konnector workdir

- web/sharings/sharings.go
- web/sharings/sharings_test.go
One can request `GET sharings/sharing-id` if he has at least one doctype in its permissions declared in the sharing document.
Note this is based on #805
> Add route to get sharing document

- pkg/scheduler/trigger_event.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- web/sharings/files.go
This allows the propagation of deletions events in a shared directory to the recipients.
When a delete event ends up with a 404, we propagate a "hard delete", so that the recipient removes the dir or file without the trash. This is done to deal with the client desktop behaviour which fully delete a directory if it's empty.
> Support for deletes in shared directory

- docs/registry.md
- pkg/apps/errors.go
- pkg/apps/fetcher_git.go
- pkg/apps/fetcher_http.go
- pkg/apps/installer.go
- pkg/apps/installer_webapp_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/instance/instance.go
- pkg/utils/iocloser.go
This PR adds the possibility to install application via a simple http URL. It is a first step toward the support for the `registry://` scheme.
It also adds the support for the `registries` section of the configuration.
> Apps HTTP fetcher

- pkg/permissions/set.go
- pkg/sharings/sharings.go
- pkg/sharings/sharings_test.go
- pkg/workers/sharings/sharing_updates.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
When a sharing recipient removes the target of a sharing (e.g. a photo album, a directory), the sharing should be revoked between him and the sharer.
This PR supports this, for master-* scenarios.
> Recipient revocation

- pkg/instance/instance.go
- web/auth/auth.go
- web/auth/auth_test.go
Since token have only 15 minutes of availability, we should redirect when presenting a good token that expired.
> Redirect to passphrase renew page when using outdated token

- docs/registry.md
This PR proposes a redefinition of the version object defined in the registry. The proposal is to remove any fields contained in the manifest of the application and to add a `/apps/:app/:version/manifest` route to directly fetch the original content of the manifest.
This should make it clearer what a version object contains versus a manifest (already defined in the stack). It also should simplify the implementation of the registry and the application installer (which needs to download the manifest content before downloading the application archive).
> Proposition to add a route to get the manifest associated with a version

- pkg/sharings/send_mails.go
The recipient sharing status weren't saved for the discovery mode, as pointed by @enguerran
> Save recipient status for discovery

- pkg/crypto/jwt.go
- web/sharings/sharings.go
The permissions handler for sharings was missing the check to ensure the issuer of the JWT corresponds to the instance's domain.
> Sharings should check the claims issuer and expiration

- pkg/apps/apps.go
- pkg/apps/fetcher_git.go
- pkg/apps/installer.go
- pkg/apps/installer_test.go
- pkg/apps/installer_webapp_test.go
- pkg/apps/konnector.go
- pkg/apps/server.go
- pkg/apps/webapp.go
- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
- web/apps/serve.go
This PR adds the possibility to associate services to an applications.
It also fixes some issues with the installation process and simplifies it:
- no more `Errored` state
- application document is created/updated in CouchDB *after* the code is reached and copied
- fixes the `Clone()` on the `WebappManifest` struct
> Add primary principles for services system

- cmd/instances.go
> Warn when the install of an app failed on creating a new instance

- assets/externals
Fixes a spacing problem between elements in the bar. I'd like to say this is the last fix but at this point I'm not sure anymore.
> Update cozy bar to v4.2.4

- assets/scripts/password-visibility.js
`current-password` works only on password type input, so use `autocomplete="off"`
> Avoid autocomplete on clear password login field

- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
This PR also logs errors and warning messages from konnectors into syslog directly. And also remove the storage of logs inside couchdb.
> Add a "critical" message log to use as returned error

- client/jobs.go
- docs/jobs.md
- pkg/jobs/jobs.go
- pkg/jobs/worker.go
- pkg/scheduler/redis_scheduler.go
- pkg/scheduler/redis_scheduler_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/trigger_at.go
- pkg/scheduler/trigger_cron.go
- pkg/scheduler/trigger_event.go
- pkg/scheduler/trigger_event_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
- pkg/workers/thumbnail/thumbnail.go
- web/jobs/jobs.go
This PR adds a `POST /jobs/triggers/:trigger-id/launch` route to allow launching manually the trigger.
It also removes the specific message transformation made by the the `@event` trigger to include the event (`*realtime.Event`) data inside the message field of the job. (`"message": { "message": ..., "event": {} }`). The event is now forwarded to the worker in the worker execution context in a specific key. This was used in the `sharing_updates` worker.
This way, jobs always have an `"message"` field matching the original message of the trigger, independently of the trigger type.
> Trigger run

- pkg/jobs/jobs.go
- pkg/jobs/mem_jobs_test.go
- pkg/jobs/redis_jobs_test.go
- pkg/jobs/worker.go
- pkg/scheduler/mem_scheduler_test.go
- pkg/scheduler/redis_scheduler_test.go
- pkg/scheduler/trigger_event_test.go
- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/konnector_test.go
- pkg/workers/exec/service.go
- pkg/workers/log/log.go
- pkg/workers/mails/mail.go
- pkg/workers/mails/mail_test.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/sharings/sharing_updates_test.go
- pkg/workers/thumbnail/thumbnail.go
- pkg/workers/unzip/unzip.go
- web/instances/move.go
- web/jobs/jobs_test.go
This PR tries to simplify workers by introducing a new struct `WorkerContext` inheriting a `context.Context`, containing job data and some helpers.
> Refacto: add a WorkerContext

- client/jobs.go
- cmd/apps.go
- docs/jobs.md
- pkg/consts/views.go
- pkg/couchdb/couchdb.go
- pkg/couchdb/mango/query.go
- pkg/couchdb/mango/query_test.go
- pkg/jobs/jobs.go
- pkg/jobs/worker.go
- pkg/permissions/permissions.go
- pkg/scheduler/mem_scheduler.go
- pkg/scheduler/scheduler.go
- pkg/sharings/recipients.go
- pkg/vfs/couchdb_indexer.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/konnector_test.go
- pkg/workers/mails/mail_test.go
- pkg/workers/sharings/share_data_test.go
- pkg/workers/sharings/sharing_updates_test.go
- web/data/permissions.go
- web/files/references.go
- web/instances/move.go
- web/jobs/jobs.go
This PR get rids of `io.cozy.konnectors.results` and only rely on `io.cozy.jobs`. The `io.cozy.jobs` now contain the `trigger_id` field when launched from a trigger, which allows to fetch the jobs associated with a specific trigger.
New routes:
- `/triggers/jobs?Worker=???`: fetch all the last jobs (from a specific worker)
- `/triggers/:trigger-id/jobs`: fetch all completed the jobs launched by a trigger
- ~~`/triggers/:trigger-id/jobs/last`: fetch the last completed job launched by a trigger~~
/cc @CPatchane 
~~⚠️ This is not a retro-compatible change~~
>  Remove konnectors result and add new routes to fetch triggers' jobs 

- assets/locales/en.po
- assets/scripts/submit.js
- assets/styles/login.css
- assets/templates/login.html
- docs/auth.md
- docs/settings.md
- pkg/instance/instance.go
- pkg/instance/two_factor_auth.go
- pkg/workers/mails/mail_templates.go
- web/auth/auth.go
- web/settings/instance.go
This PR adds two factor authentication using the following scheme:
- when user asks for two factor authentication, this parameter is saved on the instance document directly
- on each connection, when the TFA is activated:
* the user is asked for its passphrase first
* when entering correct passphrase, the user is then asked for:
- a TOTP (Timebased One-Time password, RFC 6238) derived from the `SessionSecret` with a period of 30secondes and a skew validity of 4 periods (for ~2 minutes validity) composed of six digits, named `two-factor-passcode`
- a short term timestamped MAC with the same validity time-range and also derived from the `SessionSecret` named `two-factor-token`
* when sending a correct and still-valid pair `(two-factor-passcode, two-factor-token)`, the user is granted with …
> Add two factor authentication

- assets/externals
Since the `dist/` folder is no longer versioned, I used unpkg.com to get the files.
> chore: update bar version

- client/instances.go
- cmd/instances.go
- docs/cli/cozy-stack_instances_update.md
- docs/cli/cozy-stack_konnectors_run.md
- docs/cli/cozy-stack_serve.md
- pkg/instance/updates.go
- web/instances/updates.go
Add translation step to migrate and update applications from a `git://` to a `registry://`.
Examples of command:
```sh
$ cozy-stack instances update --all-domains --force-registry
$ cozy-stack instances update --domain foo.bar --force-registry
$ cozy-stack instances update --all-domains --force-registry drive collect
$ cozy-stack instances update --domain foo.bar --force-registry drive collect
```
> Add options to migrate applications from git:// to registry://

- pkg/instance/instance.go
- pkg/instance/two_factor_auth.go
This PR adds a proposition to derive a new key to generate a new TOTP function (from which we generate TOTP passcodes) on each passphrase step.
It works by generating a salt that we encode and sign in the value part of the `two-factor-token` and that is used to derive a new key (with `HKDF(SessionSecret, salt)`) from which we generate TOTPs. This way, on each new connection we generate a new TOTP function, and our token is linked cryptographically to this TOTP function.
Pros:
+ prevent the reuse of TOTPs on another authentication process
+ bind cryptographically the `two-factor-token` and the TOTPs (`two-factor-passcode`s) generated from its associated function
Cons:
- make the code and the logic more complex
@nono what do you think ?
> 2FA: add salt to derive a new TOTP function for each new passphrase step

- docs/jobs.md
- pkg/consts/views.go
- pkg/jobs/jobs.go
- pkg/scheduler/scheduler.go
- web/jobs/jobs.go
The `current_state` field added on triggers can be used to know what is the current state of the jobs triggers. It calculated from the last executed jobs from the trigger.
> Add a current_state field to triggers

- pkg/couchdb/couchdb.go
- pkg/metrics/metrics.go
- pkg/stack/main.go
- web/routing.go
Export the `/metrics` endpoint on the administration interface, using Prometheus client library.
The default endpoint, exposed by the said library, exports generic metrics on the current process and go runtime properties.
> Bootstrap the `/metrics` endpoint

- assets/externals
https://github.com/cozy/cozy-client-js/releases/tag/v0.4.3
I forgot to manually build cozy-client when releasing v0.4.3.
Here is a new shasum for the real v0.4.3.
cf. https://github.com/cozy/cozy-client-js/pull/236/files
> update cozy-client-js to v0.4.3

- pkg/apps/server.go
- pkg/vfs/file.go
- pkg/vfs/vfsswift/impl.go
- pkg/vfs/vfsswift/thumbs.go
- scripts/build.sh
- web/apps/apps.go
- web/apps/serve.go
- web/files/files_test.go
- web/routing.go
- web/server.go
This PR aims at fixing some issues I found from our asset caching control: mainly the `Etag` headers that weren't set properly.
It also switch to a fork of `statik`: `github.com/cozy/statik`, that handles our `assets/externals` file and download assets only if necessary. The generation of our static file now is entirely done with a `go generate`. No real needs to execute `./scripts/build.sh assets` except for download transifex translations.
> Fix "Etags" and improve our "go generate"

- web/konnectorsauth/oauth.go
This patch fix a go panic, while getting redirected to the cozy, after an OAuth authentication, in the specific case where no token_endpoint is provided in account_type.
Below, the go stack trace
```
echo: http: panic serving 127.0.0.1:44724: runtime error: invalid memory address or nil pointer dereference
goroutine 2824 [running]:
net/http.(*conn).serve.func1(0xc420a465a0)
/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xe296a0, 0x16023d0)
/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/cozy/cozy-stack/web/konnectorsauth.redirect(0x15d5820, 0xc420156230, 0xf625e3, 0x20)
/home/jacquarg/workspace/cozy_dev/local_tests/src/github.com/cozy/cozy-stack/web/konnectorsauth/oauth.go:126 +0x77e
github.com/labstack/echo.(*Echo).Add.func1(0x15d5820, 0xc420156230, 0x20, 0xf41004) …
```
> Fix panic (OAuth redirect with no-token_endpoint)

- web/notifications/notifications.go
- web/permissions/allow.go
As discussed via Zoom, we use OAuth tokens while developing and an app should be able to send notifications. The sourceId for OAuth app is the id of the app.
```
"source": "ff13a635265094f840756fe604037517",
```
> feat: allow oauth applications to post notifications

- cmd/serve.go
- pkg/config/config.go
Other CLI commands (like `cozy-stack instances add`) can now be run without needing to be able to read the admin passphrase file
> Only cozy-stack serve needs to read the admin passphrase file

- pkg/workers/mails/mail_templates.go
- web/dev.go
- web/routing.go
- web/statik/handler.go
This PR adds the following routes in a dev release:
- `GET /dev/mails/:name`
- `GET /dev/templates/:name`
These routes can be used to help the development and directly render a specific mail or template. The query parameters given are used a input data for the template rendered. For the mail route, it possible to specify a `ContentType` query parameter to render `text/plain` or `text/html` mail.
> Add dev routes to directly test rendering of any mail or template

- cmd/serve.go
- cozy.example.yaml
- pkg/config/config.go
- pkg/jobs/mem_jobs.go
- pkg/jobs/mem_jobs_test.go
- pkg/jobs/redis_jobs.go
- pkg/jobs/redis_jobs_test.go
- pkg/jobs/worker.go
- pkg/jobs/workers_list.go
- pkg/scheduler/mem_scheduler_test.go
- pkg/scheduler/redis_scheduler_test.go
- pkg/scheduler/trigger_event_test.go
- pkg/stack/main.go
- pkg/workers/exec/common.go
- pkg/workers/log/log.go
- pkg/workers/mails/mail.go
- pkg/workers/push/push.go
- pkg/workers/sharings/share_data.go
- pkg/workers/sharings/sharing_updates.go
- pkg/workers/thumbnail/thumbnail.go
- pkg/workers/unzip/unzip.go
- web/jobs/jobs_test.go
- web/routing.go
- web/server.go
This PR adds a per-worker type configuration to configure workers individually.
The global hard-limit on the number of the total number of concurrent workers is now removed by default, but kept for retro-compatibility when the `jobs.workers` configuration field is set to an positive integer. Setting such a hard limit now produces a warning log.
The `jobs` configuration is now described as follow:
```yaml
jobs:
#
#
#
#
#
workers:
```
The `max_exec_time` configuration for workers has also been removed since it has not proved being useful, and rather unsuitable (not orthogonal to the `timeout` and `max_exec_count` parameters).
> Add a per-worker type configuration

- pkg/workers/mails/mail_templates.go
This is mainly done in order to fix the `go.uuid` API breaking changes, since hermes rely on sprig which rely on this library.
We should introduce quickly the new `go dep` tool in order to lock our dependencies and avoid these kind of issues in the near future.
> Rely on a hermes fork to pass custom template functions

- cmd/apps.go
- pkg/config/config.go
- pkg/jobs/mem_jobs.go
- pkg/jobs/redis_jobs.go
- pkg/jobs/redis_jobs_test.go
- pkg/jobs/workers_list.go
- pkg/workers/log/log.go
This PR adds a specific high priority queue in redis `j/$workerType$/p0` used to prioritize manual jobs. We avoid a starvation of the low priority queue in case too many manual jobs are launched.
> Prioritize manual jobs

- pkg/jobs/worker.go
Cette précision supplémentaire du message de debug pour éviter la confusion entre positionnement du timeout au lancement et échéance atteinte.
> Refine debug message to avoid confusion

- assets/templates/authorize_sharing.html
- web/auth/auth.go
- web/routing.go
This PR is a proposal to avoid loosening our CSP policy on `img-src` on all our main domain pages and using a specific `img-src nonce-random-value` to mitigate the issue of displaying an external logo for the OAuth clients.
> Avoid a wildcard in the img-src CSP configuration and use nonce instead

- pkg/apps/copier.go
- pkg/apps/installer_konnector_test.go
- pkg/apps/installer_webapp_test.go
- pkg/apps/server.go
- web/statik/handler.go
- web/utils/serve_content.go
Adds compression before storing application assets and serve them as is when the user accepts gzip encoding with `Accept-Encoding: gzip` header.
> Compress application assets

- pkg/accounts/accounts.go
- pkg/apps/konnector.go
- pkg/jobs/errors.go
- pkg/jobs/worker.go
- pkg/utils/limit_writer.go
- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
- scripts/konnector-node-run.sh
- scripts/konnector-nsjail-run.sh
This PR adds a specific field `"on_delete_account"` in the manifest of konnectors which can specify a filename to execute at the deletion of an associated account.
This field is not yet documented as it is designed to support a specific behavior of konnectors which may be handled in the future with a more generic system.
> Execute konnector on account deletion

- pkg/lock/simple_redis.go
- pkg/utils/utils.go
- web/konnectorsauth/statestore.go
This PR adds a `RandomStringFast` method allowing to pass a specific RNG (not thread-safe). It maximises the entropy for each roundtrip with the RNG, wasting now 4bits of entropy per 64bits , instead of 56bits wasted by the `RandomString` method. It encodes 6 bits of entropy per character with a 64 character set `[0-9a-zA-Z_-]` (the same as `base64.URLEncoding`).
In addition, the statestore used to store OAuth credentials now uses a rand/crypto for its security-sensitive work.
> Add RandomStringFast method

- pkg/workers/exec/cmd_unix.go
- pkg/workers/exec/cmd_windows.go
- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
- scripts/konnector-nsjail-run.sh
This PR fixes the process termination on timeout for `konnector` and `service` workers. The killing of these process requires to kill all children of the processes, which is not done by the `cmd.Process.Kill()` command.
A `COZY_TIME_LIMIT` is also added which specify to the script how many time is has to execute. This is useful for instance with nsjail which provide a `--time_limit` option to be extra-careful and avoid leaking processes.
> Fix process termination by killing process and its children 

- pkg/jobs/worker.go
- pkg/workers/exec/konnector.go
This PR adds a flag to avoid a retry for jobs. A konnector can send in its `critical` JSON message log a `no_retry` field as `true`, the job won't be retried, regardless the worker configuration.
> Add a no-retry flag on jobs to avoid a retry when needed

- pkg/apps/copier.go
- pkg/apps/fetcher_file.go
- pkg/apps/fetcher_git.go
- pkg/apps/fetcher_http.go
- pkg/apps/installer_konnector_test.go
- pkg/apps/installer_test.go
- pkg/apps/installer_webapp_test.go
- pkg/apps/server.go
- pkg/instance/instance.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsafero/thumbs.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/konnector_test.go
- pkg/workers/exec/service.go
- scripts/coverage.sh
- scripts/integration.sh
- web/server.go
This PR should make the installation and update more robust to failure by adding the possibility to abort an installation in case of an error during the process: i/o error or checksum mismatch: a temporary folder is used to store file during installation and committed (renamed) only on success.
> Robustness: make app installation and update more robust to failure and concurrency

- pkg/couchdb/couchdb.go
- pkg/couchdb/couchdb_test.go
`JSONDoc` may contain nested maps and slices. We need a more robust `Clone()` method of these objects to prevent a category of error with concurrent usages of `JSONDocs`.
> Deep copy of JSONDoc map

- pkg/workers/exec/common.go
- pkg/workers/exec/konnector_test.go
This PR is a small refactorization of the code in `pkg/workers/exec` to simplify the structure of the `konnector` and `services` workers.
Better watch the diff [without whitespaces](https://github.com/cozy/cozy-stack/pull/1248/commits/1b0564a888efb5b5a892efad739fb836fb67549c?w=1).
> Refacto: rewrite of the common exec

- pkg/crypto/mac.go
- pkg/crypto/mac_test.go
- pkg/crypto/utils.go
- pkg/instance/two_factor_auth.go
- pkg/sessions/session.go
This PR changes the `cypto/mac` API, by having a separate "MAC configuration" containing a `Name`, `MaxAge` and `MaxLen` from the actual key slice used to create a MAC.
The EncodeMessage function signature is now:
```go
func EncodeAuthMessage(c *MACConfig, value, additionalData []byte) ([]byte, error)  {}    // before
func EncodeAuthMessage(c MACConfig, key, value, additionalData []byte) ([]byte, error) {} // after
```
The implementation is also changed to have only one allocation per encode/decode phase.
> Improve Encode/Decode auth message API

- cmd/fixer.go
- docs/cli/cozy-stack_fixer_thumbnails.md
- pkg/workers/thumbnail/thumbnail.go
Add a `--with-metadata` flag on the thumbnail fixer command in order to re-calculate the metadata of images.
> Recalculate images metadata when needed

- .gitignore
- .travis.yml
- scripts/coverage.sh
- tests/codecov.yml
Our coverage with go 1.10 on codecov looks like this:
The big green shape is `web/statik/statik.go`
> Ignore web/statik test coverage on codecov

- pkg/jobs/workers_list.go
We have removed the workers for the sharing recently but we still have config files with those workers. We should not block starting the stack on them, just a warning is enough.
> Allow config for workers that do not exist

- docs/settings.md
- web/settings/instance.go
- web/settings/passphrase.go
- web/settings/settings.go
- web/settings/settings_test.go
This PR changes the API to activate the two-factor authentication.
> Always ask for a new code to activate two-factor authentication

- docs/settings.md
- pkg/instance/instance.go
- pkg/instance/two_factor_auth.go
- web/settings/instance.go
- web/settings/settings.go
- web/settings/settings_test.go
Simplify the authentication mode APIs. Rely on a separate route `PUT /settings/instance/auth_mode` to activate / deactivate the two-factor authentications.
> Simplify and separate the authentication mode APIs

- pkg/couchdb/proxy.go
Deleting via `_bulk_docs` would not send realtime events as
deletions but as updates. Here we check if `_deleted` is set
to true to correctly broadcast the Delete event.
> feat: event delete is correctly broadcasted

- cmd/instances.go
Add `token-konnector` command. Sets the token's "aud" field to "konn".
```
$ jwt decode $(cozy-stack instances token-konnector cozy.tools:8080 collect)
Token header
------------
{
"typ": "JWT",
"alg": "HS512"
}
Token claims
------------
{
"aud": "konn", <-------
"iat": 1520516367,
"iss": "cozy.tools:8080",
"sub": "collect"
}
$ jwt decode $(cozy-stack instances token-app cozy.tools:8080 collect)
Token header
------------
{
"typ": "JWT",
"alg": "HS512"
}
Token claims
------------
{
"aud": "app", <-------
"iat": 1520516373,
"iss": "cozy.tools:8080",
"sub": "collect"
}
```
> feat: add instance token-konnector command

- pkg/couchdb/couchdb.go
- pkg/vfs/couchdb_indexer.go
- pkg/vfs/directory.go
- pkg/vfs/file.go
- pkg/vfs/iter.go
- pkg/vfs/vfs.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl_v2.go
This PR moves the "move to/from trash" logic in the indexer. It allows a more robust implementation of this process.
> Move the "trash" logic in the indexer

- cmd/root.go
- pkg/couchdb/errors.go
- pkg/couchdb/proxy.go
Clean up URL that may be contained in errors form CouchDB to make sure they do not contain sensitive informations.
> Make sure error do not contain sensitive informations

- pkg/workers/push/push.go
While working on push notifications on banks, I encountered some problem when I wanted to open the app on a particular route when the user tap on the notification in the notifications center.
I read the docs of the [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#android-behaviour) which we are using to receive push notifications on the mobile app. It explains that we need to send a truthy `content-available` property and to put title and content under the data key, even if the Google docs says something different.
After some tests, I came with this shape for the push notification message object, which works for what we want to do on the app side.
> feat: update push notification data shape

- pkg/apps/webapp.go
- pkg/jobs/errors.go
- pkg/jobs/worker.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
Add error type to convey from the broker to the scheduler that a trigger can be removed. This is used for trigger executing konnector or service that is not installed anymore, or does not match the one defined in the service manifest document.
> Error case to auto-delete triggers

- pkg/workers/push/push.go
After some investigation with @jinroh, we found that this option is not required for Android. But it is important for iOS. We keep it but we use the "official" option provided by go-fcm
> fix: use ContentAvailable option from go-fcm instead of custom content-available

- pkg/notification/center/notification_center.go
- pkg/workers/push/push.go
With one job, send all the necessary push to the clients. The worker handle finding the necessary clients instead on creating one job per client.
Also, this way we do not need to store the device token into the persisted job message value.
> Notifications one job per push

- pkg/accounts/credentials.go
- pkg/accounts/credentials_test.go
- web/data/accounts.go
With this PR, all fields from the `io.cozy.accounts` field `auth` are encrypted. The `login` still appears in plain as it is used to represent the account name in collect.
> Encrypt all fields from the auth object in io.cozy.accounts

- docs/toc.yml
cozy-docs-v3 now pulls the doc automatically from several repos. Since the
doc is inside the repository, it seemed that having its table of contents
near the docs is better. This toc.yml is used during documentation build
and its result is the menu in References.
See the result on https://ptbrowne.github.io/cozy-docs-v3 (Menu Develop > References).
> feat: add toc.yml for cozy-docs-v3

- cmd/root.go
Previously, only prod release would be able to use COZY_ADMIN_PASSWORD. It is useful
for cozy-stack to be able to use COZY_ADMIN_PASSWORD if we are targeting a remote stack
via ssh tunnel.
> feat: allow dev release to use COZY_ADMIN_PASSWORD

- pkg/couchdb/bulk.go
- pkg/vfs/couchdb_indexer.go
- pkg/vfs/fsck.go
- pkg/vfs/vfs.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl_v1.go
- pkg/vfs/vfsswift/impl_v2.go
- web/instances/instances.go
Checking the index integrity means:
- checking that no cycle exists
- checking that all trees are linked to the root tree (no orphans)
- checking that `path` fields in the directory match the hierarchy
A pass checking this integrity is performed before the second pass, consisting in checking the data coherence between the index and the data layer.
When using the `--prune` option of the `fsck` command, the fsck process tries to fix possible integrity issues encountered. Some issues are not solved automatically: if these non-solved issues are recurrent, we can add more intelligent solvers from these concrete cases.
> Fsck: check and repare index integrity in a first pass of the process

- pkg/sharing/rule.go
- pkg/sharing/setup.go
This prevents a nil exception on the receiver side for `push` sharings
> Do not add share-replicate trigger on receiver side if one-way sharing

- docs/konnectors_workflow_example.md
- pkg/jobs/worker.go
- pkg/workers/exec/konnector.go
Added the `COZY_JOB_MANUAL_EXECUTION` environment variable when executing
a konnector.
This can be useful for the konnector as some actions only need to be done
while executing manually.
> feat: add manual execution env var

- pkg/apps/copier.go
- pkg/apps/installer.go
- pkg/apps/installer_konnector_test.go
- pkg/apps/server.go
- pkg/workers/exec/konnector.go
- web/apps/apps.go
Store konnectors in a flat hierarchy, like applications, to be able to extract independent files, like its icon.
> Konnector icon

- pkg/sessions/session.go
- web/files/files_test.go
The session duration is now 30 days. The session cookies do not need an explicit expiration, they are defined as session cookies with the lifespan of the browser session.
The expiration only relies on our session expiration, and not on the cookie expiration.
> Increase session duration and use session cookies for app cookies

- pkg/apps/fetcher_http.go
- pkg/apps/installer.go
- pkg/instance/updates.go
- pkg/registry/registry.go
This PR adds a check on the source change of our applications for the registry: the application slug must exist in the registry to perform the source swap.
Also improves the error reporting of the update script.
> Prepare for registry publication

- docs/sharing.md
- pkg/consts/views.go
- pkg/couchdb/bulk.go
- pkg/couchdb/encoding.go
- pkg/sharing/api_sharing.go
- pkg/sharing/shared.go
- pkg/sharing/sharing.go
- web/sharings/sharings.go
- web/sharings/sharings_test.go
This PR is based on #1333.
This is a naive implementation to get the the sharing info from a doctype. Actually, this will returns as many sharing info as there are a shared documents, i.e. a sharing involving 5 docs will be returned 5 times. We might use a smarter map function and/or a reduce.
I am not confident on the json-api format either.
> Sharing get doctypes

- .travis.yml
- docs/INSTALL.md
The golang.org/x/crypto/ssh package now depends of math/bits that was
introduced in go 1.9. It seems safer to follow the updates and drop go
1.8 support from a security point of view.
> Drop Go 1.8 support

- cmd/root.go
Choosing the root CA and client certificate as an option.
New env variables are:
- `COZY_ADMIN_HTTPS_CLIENT` (set to `1` or `true` to activate https)
- `COZY_ADMIN_HTTPS_CLIENT_ROOTCA_FILE`
- `COZY_ADMIN_HTTPS_CLIENT_CERT_FILE`
- `COZY_ADMIN_HTTPS_CLIENT_KEY_FILE`
- `COZY_ADMIN_HTTPS_CLIENT_PINNED_KEY`
> Allow usage of HTTPs for admin client

- tests/sharing/lib/cozy_file.rb
- tests/sharing/lib/folder.rb
- tests/sharing/lib/model.rb
- tests/sharing/tests/conflicts.rb
The revisions are not propagated after a conflict, therefore the tests fails on `assert_equal child1.name, child1_recipient.name` (lost conflit) or  `assert_equal child1.rev, child1_recipient.rev` (won conflict). I don't see any error in the logs.
> Conflicts tests

- pkg/workers/mails/mail_templates.go
Gmail was failling its style parsing because of this extra character and therefore disregarding everything else in the `<style>` tag.
> fix: mail rendering on Gmail client

- web/files/files_test.go
Travis is not very stable this week and I have enough to restart travis builds (unit tests for go 1.9 and 1.10) because this test fails (or it makes CouchDB lags and the following tests fail)
> Remove TestUploadConcurrently

- pkg/jobs/redis_broker.go
It fixes a regression introduced by https://github.com/cozy/cozy-stack/pull/1435/commits/b9531f2ef40ca988812cdb3ecb07723e3cb572bd#diff-656325a475171641eede0030442145d6
On web servers, the workers are disabled and when we push a job, we try to find the worker from `b.workers` to execute the PreHook. So, we need to initialize `b.workers` even if the workers are disabled.
> Fix push jobs on a server where workers are disabled

- pkg/workers/mails/mail_templates.go
There are a few `return`s between `Lock` and `Unlock` that can happen if a translation is missing for a mail. We should release the lock if it happens to let the other mails to be sent.
> Fix a possible deadlock

- pkg/vfs/vfsswift/impl_v1.go
- pkg/vfs/vfsswift/impl_v2.go
- pkg/vfs/vfsswift/thumbs_v1.go
Use the same logic as layout v2 by first marking containers as "to-be-deleted" before deleting on the containers' data.
> Improve deletion of VFS relying on Swift layout V1

- assets/locales/en.po
This add missing translations for two permissions:
* `cc.cozycloud.autocategorization`
* `cc.cozycloud.sentry`
I also added the french translations via transifex
> Remote doctypes translations

- assets/locales/en.po
I copy/pasted the translations of the store in https://github.com/cozy/cozy-stack/pull/1465, but we don't prefix the translations with 'The' in the stack.
> fix: Remove 'the' in cc.cozycloud.sentry translation

- assets/scripts/submit.js
- assets/styles/login.css
- assets/templates/login.html
Login errors are now more accessible for screen readers as they are inserted in the DOM at the top of the login form but put back to its end with CSS.
You shouldn't see any difference with before in the UI.
> feat: Login errors more accessible

- assets/templates/login.html
- assets/templates/need_onboarding.html
- assets/templates/passphrase_renew.html
- assets/templates/passphrase_reset.html
- assets/templates/sharing_discovery.html
Quick & easy a11y enhancement.
`<figure>` element should have a `role="group"`attribute for accessibility reasons.
> feat: add extra a11y on figure elements

- assets/.externals
To anticipate the removing of Cozy-Collect, we need to remove the cozy-collect action from the Cozy-Bar. This version contains this removing.
> Update cozy-bar to 5.2.0

- assets/.externals
Should fix intents redirection incompatibilty. Thanks @nono for spotting this one.
> Update cozy-client to v0.12.1

- cmd/instances.go
Add a `--json` flag to output a json map of the instances on each line.
Add a `--fields` flag to specify the fields of interest to output on each line.
> Improve formatting of instances ls command

- pkg/apps/copier.go
- pkg/vfs/vfsswift/impl_v1.go
- pkg/vfs/vfsswift/impl_v2.go
- pkg/vfs/vfsswift/thumbs_v1.go
- pkg/vfs/vfsswift/thumbs_v2.go
- pkg/workers/move/archiver.go
We had a wrong interpretation of the checkHash properties defined by ncw/swift. This checkHash does not mean "check against the given hash" but "check against the calculated hash from streaming the content".
Force this argument to true, so that we always have a checksum checked as we thought.
> Always check the checksum when uploading to swift

- client/instances.go
- cmd/instances.go
- pkg/sharing/indexer.go
- pkg/vfs/couchdb_indexer.go
- pkg/vfs/fsck.go
- pkg/vfs/vfs.go
- pkg/vfs/vfsafero/impl.go
- pkg/vfs/vfsswift/impl_v1.go
- pkg/vfs/vfsswift/impl_v2.go
- pkg/workers/move/export.go
- web/files/files.go
- web/instances/instances.go
Another round of improvements on the FSCK analysis:
- more uniform method between VFS: two-pass check on index and objet storage
- faster analysis
- a route on `/files/fsck` to access to the analysis
The `prune`ing parts have been removed for now. They have not shown to be useful or applicable for now.
> Fsck improvements

- pkg/jobs/redis_broker.go
The redis broker is waiting in the shutdown for all the workers to stop polling redis for new jobs. Before this commit, in the list of workers, there were also workers with concurrency at 0, and for those workers, we didn't start the polling. So, on a server where some workers were disabled, we were forced to wait until the context timeout on shutdown even if there was no more activity.
> Fix shutdown of redis broker

- pkg/workers/exec/konnector.go
linked to #1562: adding support for another nested layout of konnector folder.
> Konnectors: delete empty folders for konnectors that do not require one

- pkg/vfs/archive.go
- pkg/vfs/vfs_test.go
- web/files/files_test.go
We need to quote the quoted string of a Content-Disposition header
for filenames with a separator like , or ;
https://tools.ietf.org/html/rfc2616#section-3.6
> Fix the Content-Disposition header

- cmd/instances.go
```bash
root@gozy-adm-int:~# cozy-stack instances show-swift-prefix sblaisot.cozy.works
Error: json: cannot unmarshal array into Go value of type string
```
> Fix show-swift-prefix cmd

- client/instances.go
- cmd/instances.go
- docs/cli/cozy-stack_instances.md
- docs/cli/cozy-stack_instances_ls.md
- docs/cli/cozy-stack_instances_show-db-prefix.md
- pkg/couchdb/couchdb.go
* Renamed `show-prefix` option to `show-db-prefix`
* Add `db_prefix` field
* Add `--available-fields` option to list available fields returned by `--fields` option for command `cozy-stack konnectors ls`
* Improve JSON output
> Improve show-prefix command

- pkg/sharing/sharing.go
- web/apps/serve.go
Already existing tokens where overwritten when a new token was generated
for a share. This fix should keep the old tokens.
> Fix overwritten sharings on new sharing creation

- assets/scripts/submit.js
- assets/templates/login.html
- right title on 2FA view
- numeric pad on Android
- header missing margin
- replaced remember me checkbox on mobile
> fix: Wizard visible elements

- client/tlsclient/tlsclient.go
- pkg/config/config.go
- pkg/vfs/vfsswift/impl_v1.go
Disable Accept-Encoding for requests to Swift. For files with a gzipped
size inferior to the real size, a reverse-proxy between the stack and
Swift can gzip the response, and when it is the case, the stack may
return a 500 because it can no longer infer the file size from the
Content-Length, as http.ServeContent does.
> Fix Swift encoding

- docs/references-docs-in-vfs.md
After reading the documentation, I was expecting to get the whole `file object` with its own attributes. But in fact, we just get id and type (as described in the example).
> docs: Add clarification about references

- pkg/vfs/fsck.go
With these unexported JSON fields, there were not written to the `files-index.json` metadata file during the export, thus not exported to the archive.
> Fix cozies export

- pkg/apps/apps.go
- pkg/apps/copier.go
- pkg/apps/fetcher_file.go
- pkg/apps/fetcher_git.go
- pkg/apps/fetcher_http.go
- pkg/apps/fetcher_registry.go
- pkg/apps/konnector.go
- pkg/apps/server.go
- pkg/apps/webapp.go
- pkg/workers/exec/konnector.go
- pkg/workers/exec/service.go
- web/apps/apps.go
- web/apps/serve.go
- web/server.go
When an app is available on two registry spaces, at the same version
number, but not with the same code (customized app for example), the
stack was serving the code from the first version installed. With
this fix, we can differentiate these cases and serve the right code
for the webapp/konnector.
> Fix for same app/version but not code from 2 registries

- web/data/accounts.go
The connectors will soon be able to save their cookie in the associated io.cozy.account. This data
is as sensitive as the password and then should also be encrypted.
This PR is naive, I don't know if there are other files to update accordingly
> feat: add session encrypted attribute to accounts

- client/apps.go
- cmd/apps.go
- docs/cli/cozy-stack_apps_update.md
- docs/cli/cozy-stack_fixer.md
- docs/cli/cozy-stack_fixer_link-app.md
- docs/cli/cozy-stack_konnectors_update.md
In case of blocking changes (TOS, new perms), we may want to block a
webapp/konnector update.
> Add a "safe" flag to app update cmd to prevent updates

- docs/docker.md
For replication tests, CouchDB must be able to make HTTP connexions to cozy-stack. It means that it must run with `--net=host` mode when it is executed from Docker.
> Fix docs for running CouchDB in docker

- web/auth/auth.go
- web/auth/auth_test.go
In case of mobile onboarding, we also want to give the instance domain
param in the deeplink
> Add instance to redirectURI params

- client/instances.go
- cmd/instances.go
- cmd/serve.go
- docs/INSTALL.md
- docs/cli/cozy-stack_instances_add.md
- docs/cli/cozy-stack_serve.md
- docs/instance.md
- pkg/config/config.go
- pkg/instance/instance.go
- pkg/sessions/session.go
- scripts/cozy-app-dev.sh
- scripts/integration.sh
- tests/sharing/lib/stack.rb
- web/instances/instances.go
- web/konnectorsauth/oauth_test.go
- web/middlewares/secure.go
A stack can be built in two release modes: dev and prod. We also has a flag per instance, but it was confusing to have both and, in practice, using a prod release with a dev instance didn't work.
Note that a prod release can be used as a dev release by starting the server like this:
$ cozy-stack serve --dev
> Deprecate the dev flag on instances

- tests/sharing/lib/sharing.rb
- tests/sharing/tests/read_only.rb
Using quotes for filenames in the sharing tests can make them break on travis.
> Do not use long filenames in sharing tests

- pkg/instance/instance.go
- pkg/instance/warnings.go
- web/apps/serve.go
- web/auth/rate_limiting.go
- web/middlewares/instance.go
- web/routing.go
- Split the notion of "blocked instance" in really "blocked" state and "ToS not signed and deadline exceeded". It implies that a user can access his login page and connect even if his ToS deadline is in error. He will be redirected to his `ManagerURL` later
- Add a field `blocking_reason` in Instance to store the information about the blocking reason
> Improve instance blocked checking

- pkg/apps/installer.go
- pkg/apps/konnector.go
- pkg/apps/webapp.go
- pkg/instance/instance_test.go
- pkg/intents/intents_test.go
- web/apps/apps_test.go
- web/auth/auth_test.go
- web/intents/intents_test.go
- web/sharings/sharings_test.go
The id field was missing in the websocket message of /realtime for webapps and konnectors when the stack was using redis. It was due to JSON serialization issues, and fixed by adding an explicit DocID for those two structs.
> Fix realtime for apps

- assets/templates/login.html
- Moved the header in the content so the whole area is scrollable on smaller screens.
- Changed classes `wizard-password` to `wizard-input` since those are now deprecated in Cozy-UI@18.15.0
> fix: login layout on mobile

- assets/templates/login.html
- The avatar now has a satefy minimum top margin (validated by designers)
- Better margin for footer while respecting mockups.
> fix: login margins on mobile

- pkg/workers/exec/konnector.go
It a konnector fails on the first, and then succeeds on a next retry, we should reset the error from the previous run to not see it as a whole failure.
> Fix the error handling in the konnector worker

- pkg/instance/instance.go
We were comparing the old and new values for the settings to know if we really need to persist the changed to CouchDB. But the comparison can panic if a value is a slice or a map. Using reflect.DeepEqual fix this.
> Fix a panic when updating the settings

- assets/templates/authorize.html
- web/auth/auth.go
If we don't have a fallback URI, it is useless to try to detect if the device can handle a deeplink or not, as we can't do anything if it does not. So, let's include this script only if needed.
> Include the check deeplink JS only when useful

- pkg/workers/exec/konnector.go
If we had some logs from the konnector after the error message, this message was lost.
> Fix the error message for konnector failures

- cmd/fixer.go
- pkg/contacts/contacts.go
- pkg/move/import.go
- pkg/sharing/member.go
- web/sharings/sharings_test.go
We were using structs for the contacts doctype, but it forces to have exactly the same mapping as the front applications. It can be dangerous and lead to data loss. For example, if a contact was added to a group, and she accepts a sharing, the contact will be removed from the group.
> Use a map for contacts

- pkg/apps/installer_webapp_test.go
This test was not very useful as there is no known Cozy webapp on gitlab, and could make some builds on Travis fail.
> Remove a test

- pkg/consts/consts.go
- web/apps/serve.go
The onboarding webapp has been deprecated a few months ago. We can remove the guard that were left to ease the transition.
> Clean code for handling the onboarding app

- pkg/apps/webapp.go
- pkg/intents/intents.go
- web/apps/serve.go
- web/server.go
The --appdir mechanism is now handled in a lower level. It allows to load intents for the apps loaded from an appdir, and to show those apps in the cozy-bar.
> Improve the way --appdir is handled

- pkg/jobs/worker.go
Most workers are inactive when an instance is blocked for not signed terms of services. But the user may need to receive an email to be able to login and accept the terms of services.
> Do not block emails when the TOS are not signed

- web/middlewares/secure.go
Adding a websocket `wss://` url in the configuration file under csp whitelist result in the url to be converted to `https://` scheme. This PR preserves the `wss://` configured scheme in CSP whitelist.
> Allow wss scheme in CSP whitelist

- pkg/workers/exec/service.go
Emptying the environment variable if there is no CouchDB document in the job event.
> Do not crash if there is no event linked to the job

- pkg/apps/apps.go
- pkg/apps/installer.go
- pkg/apps/installer_webapp_test.go
- pkg/apps/konnector.go
- pkg/apps/webapp.go
- pkg/permissions/permissions.go
- pkg/permissions/rule.go
- pkg/permissions/rule_test.go
- pkg/permissions/set.go
- pkg/permissions/set_test.go
- web/auth/auth.go
This PR allows to keep the extra-permissions added to a webapp or konnector during updates. 
Here is the workflow:
1 - A diff is made between the app/konnector original manifest and the actual permissions doc of the app. This diff contains the added `verbs` or `values` of each `Rule` of the `Set`
2 - The webapp/konnector is updated, this diff is given to the update function
3 - Once the app is updated, the diff is applied to the permissions of the app
> Avoid losing custom permissions during a webapp/konnector update 

- pkg/jobs/scheduler.go
In some cases, when no job has an "Errored" or "Done" state, the job is
skipped, preventing the status to be updated. In that case, the status
was set by default to "Done". This commit updates the status of the
trigger before checking the job state.
> Set the trigger last job informations earlier

- pkg/sharing/revisions.go
- pkg/sharing/shared.go
- tests/sharing/lib/folder.rb
- tests/sharing/tests/remove_folder.rb
When a directory is inside a shared folder and is moved outside of it, the files of the directory must not be put in the trash by retroaction. This commit fixes the removed flag of the io.cozy.shared documents.
> fix: Do not trash files inside a no longer shared dir

- web/auth/auth.go
- web/settings/context.go
* Do not generate a `fallbackURI` if the `redirectURI` is not a deeplink. This allows to handle both the universal links and the deeplinks.
* Use `instance.SubDomain()` instead of `instance.PageURL()` for app url generation
> Small improvements for universal links

- pkg/permissions/permissions_test.go
- pkg/permissions/verbs.go
If an application manifest contains a permission where the verbs contain ALL and other things, we should still allow to install the app and consider the permissions for ALL.
Resolves #1831
> Fix for installing apps with ALL+GET permissions

- pkg/jobs/worker.go
- pkg/workers/exec/common.go
- pkg/workers/exec/konnector.go
This PR adds a function to check the error status between each job retry. 
We have to ensure that a job with a `LOGIN_FAILED` status will not be retried for the future 2FA konnectors.
The already existing `beforeHook` function filters the job before pushing it in the queue, but not between the retries. If the first attempt results in a `LOGIN_FAILED`, there will be no checks and the job will be retried regardless of the `LOGIN_FAILED` status.
> Add a function to filter job from the last error

- pkg/contacts/contacts.go
Since https://github.com/cozy/cozy-stack/commit/952f8d06a538abcc024cfea029ddb1455309580f#diff-684de99eacb2392110a923ff3d31fdcaR79 There was a missing space between `givenName` and `familyName` for contacts without `fullname`. This PR fixes it. 
(I tried to write a test but I struggle to instantiate a simple contact to use `PrimaryName` on)
> Fix space between givenName and familyName

- pkg/apps/appfs/copier.go
When installing or updating an application in Swift, the stack puts its file in a temporary directory, and if everything is fine, copies them to their final destination. To know the list of files to copy, the stack calls ObjectNamesAll of the swift library. Using the X-Newest flag should improve reliability by ensuring a consistent response from Swift.
> Make apps install/update more reliable

- assets/mails/archiver.mjml
- web/statik/statik.go
The `<mj-image>` tag doesn't accept an inner-padding attribute. See https://www.npmjs.com/package/mjml-image
> Fix an email template

- web/middlewares/permissions.go
- web/registry/registry.go
- web/settings/context.go
- web/settings/disk_usage.go
- web/settings/settings.go
Before this change, the stack was checking only if the user was logged in. But, an attacker that knows the URL of the cozy can make a cross site request forgery on this endpoint. Now, the stack also checks that a web app token is also present. It should be compatible with the existant, as the cozy-bar was already sending this token.
> Block disk-quota requests with no token

- model/app/installer.go
- model/app/installer_webapp_test.go
- model/app/webapp.go
When an app update is being performed, a diff is done on `services` declared in the both old and new manifests. This diff result is applied at the end the update.
The comparison is done by setting an `oldServices` field in the `newManifest`, containing the `oldManifest` services.
In the event of a blocking update (new permissions, terms added, ...) or an unneeded update (same version), the manifest `Update` function is still called, but with the current manifest. 
The manifest field `oldServices` is therefore not set, causing a diff with an empty `oldServices` field. This results in the stack believing that a service has been added, and creates a new trigger.
> Set oldServices field to manifest in case of no updates

- web/middlewares/permissions.go
- web/registry/registry.go
For cozy instances in a context where allow_install_via_a_permission is activated, the stack should allow a mobile app with the right permissions to install other apps. To do that, we need to check OAuth permissions documents on the endpoint for listing apps in the registry and installing an application.
> Allow mobile apps to install app

- web/accounts/oauth.go
When account type were not having a `token_endpoint` set up, the client state was not passed in the URL. As Home app use its value to retrieve information from localStorage and check consistency, the whole OAuth workflow was not working.
> Oauth: Set clientState when redirecting to app

- pkg/metadata/metadata.go
We have to export this field to allow the go json package to encode/decode it when metadata are sent and received from CouchDB.
> Persist updatedByApps for metadata

- pkg/limits/rate_limiting.go
- web/auth/auth.go
- web/auth/rate_limiting.go
- web/auth/register.go
- web/files/files.go
- web/sharings/sharings.go
Before this change, any kind of error returned by the CheckRateLimit
function (like access error to cache for example) was interpreted as a
rate exceeded, resulting in the blocking of the instance. This commit
ensures the error is the good one before blocking the instance.
> Improve rate limit exceeded check

- docs/files.md
If a file already exists at the previous path, a suffix will be added to avoid any conflict.
> Update doc about restoring a file

- model/job/broker.go
- model/job/broker_test.go
- web/jobs/jobs.go
Some databases have a high number of jobs (250k+), leading to issues on
couch side. This commit should improve the purge by:
- Compute which jobs to delete on go-side instead of couch
- Use chunks for bulk deletes to prevent timeouts
> Handle high number of jobs purging

- model/job/redis_scheduler.go
- model/job/redis_scheduler_test.go
The github.com/go-redis/redis library has made a breaking change, and as we are not yet using go modules (even if it is planned), we need to fix how we use this library in our code.
> Fix for upstream breaking change in redis lib

- docs/intents.md
- model/intent/intents.go
- model/intent/intents_test.go
- web/intents/intents.go
This PR adds an API field that lists non-installed apps that handles the intent.
The `icon` field has not been added alongside the `slug` and `name` ones as it is easy to retrieve by the stack proxy: `http://<instance>/registry/<slug>/icon`.
> Add available apps for intents

- scripts/cozy-app-dev.sh
When behind a corporate proxy, the start-up script inside the Docker
container used curl to query ":8080", which cannot match any `no_proxy`
item, and thus systematically goes through the corporate proxy when one
is configured, resulting in a start-up failure. This commit fixes this
query so that it succeeds in that kind of environment as long as
"localhost" is defined in `no_proxy`.
> Fix cozy-app-dev container start-up behind proxy (#1925)

- docs/client-app-dev.md
A specific Docker configuration is required for the containers to work
correctly behind a corporate proxy.
This addition to the documentation is valid as long as a Docker image containing the change applied by pull request #1926 is available (otherwise container start-up will fail even with a correct proxy configuration).
> Document cozy-app-dev container usage behind proxy (#1925)

- docs/files.md
- model/sharing/files.go
- model/vfs/file.go
- model/vfs/metadata.go
- model/vfs/store.go
- model/vfs/store_test.go
- pkg/consts/doctype.go
- tests/sharing/lib/cozy_file.rb
- tests/sharing/tests/sync.rb
- web/files/files.go
- web/files/files_test.go
- web/files/paginated.go
When a client uploads a file, it can use the MetadataID query parameter to give the key for a metadata object that was created just before. It works for new files, but also when uploading a new version of an existing file.
> Allow clients to update the metadata on file uploads

- docs/files.md
I think it's relevant to say that an archive is not persisted and can't be used to store something.
> doc: Add a note about archive

- assets/.externals
This version fixes a bug we had because we used the transpiled version of cozy-ui. For more informations about the fix, please see https://github.com/cozy/cozy-bar/pull/582
> feat(assets): Update cozy-bar to v7.1.0

- model/job/redis_broker.go
- model/job/redis_broker_test.go
- model/job/redis_scheduler.go
- model/job/redis_scheduler_test.go
- model/session/code_storage.go
- model/sharing/upload_store.go
- model/vfs/store.go
- model/vfs/store_test.go
- pkg/cache/cache.go
- pkg/config/config/config.go
- pkg/config/dynamic/assets_test.go
- pkg/limits/rate_limiting.go
- pkg/limits/rate_limiting_test.go
- pkg/lock/simple_redis.go
- pkg/logger/logger.go
- pkg/logger/logger_test.go
- pkg/realtime/realtime_test.go
- pkg/realtime/redis_hub.go
- pkg/statik/fs/fs_test.go
- scripts/lint.sh
- web/accounts/statestore.go
- web/oidc/statestore.go
Currently, github.com/go-redis/redis is in the work of a new version (v7), and it introduces some breaking changes. There are no known stable version, so let's fork it to have a stable API, at least until we have go modules or the new version is stable.
> Fork go-redis to have a stable API

- cmd/fixer.go
This allows to find potential multiples of 64k
> Use a modulo instead of a fixed 64k size for content mismatch fixer

- docs/notifications.md
- model/notification/center/notification_center.go
The stack requires that apps declare their notifications before sending them. If a mobile app is linked to a web app, the stack will use the declaration from the web app manifest for it.
> Allow mobile apps to declare notifications

- cmd/swift.go
If an instance has swift_cluster > 2, count it as unknown instead of counting it as layout V3
> Improve instance count by swift layout

- web/sharings/sharings.go
When a sharing is created from an OAuth app that is linked to a web app, the stack should use this app slug to create the link sent in the mail.
> Fix sharing from Drive Mobile

- cozy.example.yaml
- model/vfs/version.go
- model/vfs/version_test.go
- model/vfs/vfsafero/impl.go
- model/vfs/vfsswift/impl_v3.go
- pkg/config/config/config.go
- web/files/files_test.go
When a file is changed, a new version is created, and the stack also checks if old versions should be cleaned.
1. The versions that are tagged are always kept.
2. If two versions are too close in time, the latter is cleaned (15 minutes by default, configurable)
3. When there are too many versions for a file, the old versions are cleaned, except if they were tagged (20 versions by default, configurable).
> Clean the old versions of the files

- cmd/serve.go
- cozy.example.yaml
- docs/cli/cozy-stack_serve.md
- docs/workers.md
- model/vfs/vfs.go
- model/vfs/vfs_test.go
- model/vfs/vfsswift/impl_v1.go
- model/vfs/vfsswift/impl_v2.go
- model/vfs/vfsswift/impl_v3.go
- model/vfs/vfsswift/swift.go
- worker/migrations/migrations.go
The migration worker can now migrate instances in Swift layout v1 and Swift layout v2 to Swift layout v3.
>  Add migrations to swift layout v3 

- model/instance/instance.go
- pkg/couchdb/bulk.go
Listing instances is done by fetching the instance information from CouchDB with pagination. By fetching 100 instances per page, we are making a lot of calls, and each call has a fixed latency that makes the
whole slow. We want to keep to pagination to avoid timeouts, but we can increase the number of items per page to 10000 to make the listing faster.
> Make cozy-stack instances ls faster

- model/job/trigger_cron.go
The cron library is moving target now. We will switch back to the upstream soon, with go modules. But, for now, let's use a fork to avoid confusion.
> Use a temporary fork for cron

- pkg/assets/dynamic/fs.go
The /status endpoint checks the connection to swift, among other things.
Before this commit, it was done via /info, but the Swift Restful API
implemeted by Ceph does not expose this endpoint. We will query the
container used by the stack for the dynamic assets for /status now, to
fix the compatibility with Ceph.
> Use the swift container for assets for /status

- docs/apps.md
- docs/konnectors.md
- model/app/konnector.go
- model/app/webapp.go
- model/app/webapp_test.go
- model/intent/intents.go
- web/apps/apps.go
- web/instances/instances.go
- worker/updates/updates.go
This PR adds a pagination for /apps route. The legacy limit is kept, but a custom limit can now be specified if needed
> Add pagination for /apps route

- docs/CONTRIBUTING.md
Since we use `gomodules`, we should not clone into the $GOPATH anymore.
> docs: Update contributing doc since we use gomodules

- cmd/fixer.go
- docs/cli/cozy-stack_fixer.md
- docs/cli/cozy-stack_fixer_orphan-account.md
- docs/konnectors-workflow.md
- docs/konnectors.md
- model/account/accounts.go
- model/instance/lifecycle/destroy.go
- model/job/broker.go
- web/apps/apps.go
When a konnector is uninstalled, the stack looks at the triggers to see which accounts is tied to this konnector. Those accounts are deleted locally, and the konnector is launched to delete the account remotely. Only after that, the konnector can be removed from the instance.
Notes:
1. An account is expected to be linked to a single konnector, via its account_type property
2. The stack does this for all the konnectors, banking but also bills and others.
Next steps:
> Delete accounts when a konnector is uninstalled

- pkg/couchdb/proxy.go
When using the Pouch->Couch replication to push changes to the Cozy, we have to set the doctype in the stack to make the real-time and the triggers work correctly.
> Fix real-time and triggers on replication

- docs/jobs.md
Add an explicit note about /jobs/triggers accepting only a query param 
and the difference between /data/io.cozy.triggers/_find and /jobs/triggers
> docs: Add a not about GET /jobs/triggers

- model/remote/remote.go
Remote doctypes do filter acceptable doctypes they are getting in
response from remote servers.
JSON was authorized as 'application/json' but not with the mime type
of JSON API ('application/vnd.api+json').
This change allows the JSON API response type in remote doctypes.
> feat: Authorizes JSON API in remote doctypes

- cmd/fixer.go
- web/apps/apps.go
The job for deletion needs the _rev just before the deletion to correctly work.
> fix: Pass the correct _rev to account deletion job

- model/sharing/oauth.go
It looks like a divide by zero panic can be thrown if a member of a sharing tries to accept a sharing about the same time he/she is revoked from the sharing. This commit should avoid it.
> Fix a divide by zero panic on sharing

- web/files/files.go
- web/files/files_test.go
Some files imported by a konnector can have cozyMetadata but no SourceAccount or SourceAccountIdentifier. With this commit, a new version of the konnector can add those fields by uploading a new version of such a file.
> Allow to add SourceAccount on existing files

- model/sharing/replicator.go
- model/sharing/revisions.go
- model/sharing/revisions_test.go
- model/sharing/setup.go
- model/sharing/shared.go
- model/sharing/upload.go
- tests/integration/tests/loop_shared_file.rb
Try to protect the stack and redis from being flooded when the desktop client send renaming in a conflict loop.
> Limit the depth of the io.cozy.shared

- model/vfs/couchdb_indexer.go
- tests/integration/lib/instance.rb
- tests/integration/lib/stack.rb
- tests/integration/tests/filepath_encoding.rb
When a file is renamed, its name is different, but it can be very subtle. For example, it can have the same unicode meaning but just with two different normalizations, like NFC and NFD. CouchDB does a unicode normalization when using strings in mango selector, so we had to make the selector more robust for this case to avoid a loop where the same sub-directories where renamed.
> Fix renaming a file from NFC to NFD

- go.mod
- pkg/assets/asset.go
- pkg/assets/dynamic/dynamic.go
- web/apps/serve.go
- web/files/files.go
- web/public/public.go
- web/server.go
- web/statik/handler.go
- worker/mails/exec.go
- worker/mails/mail_templates.go
Loading the index.html of web apps can be slow because the stack loads the assets from the storage to compute their URLs. This commit adds a cache that should help to have faster response time.
> Use cache for dynamic assets

- cozy.example.yaml
- pkg/config/config/config.go
A standalone full-featured stack has 15 worker types. Consequently, when using redis, it opens least 19 redis connections (15 worker types + 4).
Default redis pool size is `10 * runtime.NumCPU()` which is too short on a single-CPU computer.
The stack starts but can't do anything due to lack of available redis connections.
This PR enforces a minimum redis pool size of 25 slots and keeps the default `10 * runtime.NumCPU()` value if it is larger.
> Enforce minimum redis pool size

- web/instances/instances.go
If there is a type mismatch (file vs dir) in the FSCK for an instance, we need to skip the children fields to stay below the 64 limit imposed by bufio.Scanner.
> Skip children for files in FSCK responses

- web/bitwarden/bitwarden.go
Settings can ask a bitwarden token to reencrypt the ciphers when the user changes their password. If 2FA is activated, we can skip sending a code in an email, as we already have two factors: the hashed password and the session cookie.
> Don't send a mail when settings asks a bitwarden token

- docs/bitwarden.md
- go.mod
- go.sum
- model/bitwarden/settings/settings.go
- tests/integration/lib/bitwarden.rb
- web/bitwarden/bitwarden.go
- web/bitwarden/bitwarden_test.go
- web/bitwarden/ciphers.go
- web/bitwarden/folders.go
- web/bitwarden/hub.go
- web/bitwarden/organization.go
- web/bitwarden/settings.go
- web/bitwarden/sync.go
It allows the client to listen with a websocket, and the server can send them notifications about ciphers and folders.
> Add a hub for bitwarden clients

- cmd/assets.go
The examples are still using the deprecated version of the command. 
Our documentation 5isn't up to date either](https://docs.cozy.io/en/cozy-stack/cli/cozy-stack/), but 5looking at the source](https://github.com/cozy/cozy-stack/blob/master/docs/cli/cozy-stack.md) it should be..?
> Update assets command examples

- web/middlewares/instance.go
When a stack is configured with flat subdomains, and an instance has been deleted, a request on `https://<slug>-<app>.mycozy.cloud/` should return a 404 error page.
> Show 404 error page for app domain

- web/middlewares/instance.go
- web/routing.go
If an instance is blocked because the user hasn't signed the terms of services, the requests to this instance are rejected. They were always redirected to the manager, but now, only the requests for an HTML page are redirected. The requests for a JSON API are rejected with 402 Payment required, and a JSON message.
> Fix behavior when an instance is blocked for TOS

- docs/files.md
- web/files/files.go
- web/files/files_test.go
This new endpoint can be used to create a new version of a file with the same content but with new metadata.
> Add an endpoint to copy a version of a file

- cmd/swift.go
- docs/admin.md
- docs/cli/cozy-stack_swift.md
- docs/cli/cozy-stack_swift_ls-layouts.md
- scripts/completion/cozy-stack.zsh
- web/swift/swift.go
We splitted layout v2 into v2a and v2b depending on the swift container name, wether with the instance FQDN or with a random hexadecimal prefix.
Let's do the same for layout v3 because we can have swift containers with instance FQDN instead of prefix for instances migrated from layout v1 or v2a.
> Split swift layout v3 into v3a and v3b like v2

- worker/migrations/migrations.go
When migrating an instance from swift layout v1 or v2 to swift layout v3, we add a "cozy-migrated-from" metadata.
This PR fixes the metadata which was wrongly added to source container rather than the destination container.
This PR also add storing more specific informations about which v2 layout (v2a or v2b) the instance was migrated from
> Fix migrated container metadata

- model/vfs/vfsswift/impl_v1.go
- worker/migrations/migrations.go
Fix swift layout v1 container names.
In particular, fix 
- https://github.com/cozy/cozy-stack/blob/master/model/vfs/vfsswift/impl_v1.go#L57 according to https://github.com/cozy/cozy-stack/blob/master/model/vfs/vfsswift/thumbs_v1.go#L15
- https://github.com/cozy/cozy-stack/blob/master/worker/migrations/migrations.go#L93 according to https://github.com/cozy/cozy-stack/blob/master/model/vfs/vfsswift/impl_v1.go#L55
This way, we can properly:
- Delete data container for instances in swift-layout v1 (`swift_cluster == 0`) with a not null prefix when removing the instance
- Migrate those instances (otherwise migration worker fails to find the files)
Note: After all v1 layout instances have been migrated to layout v3, we should either fix …
> Fix swift layout v1 container names

- web/instances/instances.go
The stack is streaming the response. If an error occurred, the stack has already sent a 200 OK, and cannot change that to a 500. So, it's better to send a log message in the body with the error.
> Improve FSCK response in case of error

- worker/migrations/migrations.go
#2136 introduced a bug in migration worker while adding log on older container deletion. By using the `err` variable to store error on older container deletion, this triggers the deletion of the new container by the defer func after the migration has finished.
This PR fixes that bug and add a warning comment in the code.
> Fix double-deletion in migration worker

- .github/workflows/ci.yml
- .github/workflows/integration.yml
We had a lot of badmatch/badarg errors on CI with CouchDB in Docker. Let's see if it works better with CouchDB installed as a debian package.
> Install couchdb via apt instead of docker for CI

- scripts/konnector-nsjail-node12-run.sh
Node 12 [disable by default](https://github.com/nodejs/node/pull/23814) connection to TLS 1.0 and 1.1 https servers.
This PR updates the nsjail connector launch script to add an argument to nodejs12 to allow connection to external sites using only TLS 1.0 and/or 1.1
> Allow connection to TLS 1.0 external sites

- worker/migrations/migrations.go
Avoid concurrency on swift v3 layout migration to block a scenario where 2 migrations can be launched at the same time on an instance, leading to data loss:
- first migration create new container, copy data from old to new container, then delete old container
- second migration copy data from old to new container while the first one is deleting old container, so it considers the migration failed and it deletes the new container
This PR block migration if the new container already exist (a previous migration is ongoing or failed without deleting the container).
Downside is if a migration fails and also fails to delete new container, then administrator will have to manually clean the new container before being able to launch the migration again on the considered instance.
> Block migration if another one already began

- model/vfs/vfsswift/fsck_v3.go
It allows to detect when the internalID is not correct in the io.cozy.files for VFS Swift in layout v3.
> Fix FSCK for layout v3 of Swift

- docs/client-app-dev.md
- web/apps/serve.go
Since we don't used anymore the intent system to redirect the user to the right route we need to provide to our front application the information about the domain type. It can be flated or nested. With this info in the HTML, our front app can create the right URL without having to do a network request. 
I'm not familiar enough with Go, I don't know if I really need to create a `var` for that but it seems to work.
> feat: Serve domain type to html

- model/vfs/iter.go
- pkg/couchdb/couchdb.go
- web/data/data.go
- web/files/files.go
The worker for migration to Swift layout v3 can fail for instances with a lot of files/folders in the same directory. With this change, the requests to CouchDB for walking the VFS should be faster. They will use a bookmark instead of a skip parameter.
> Make vfs.Walk faster by using CouchDB bookmark

- model/notification/center/notification_center.go
- model/oauth/client.go
- worker/push/push.go
When there are many OAuth clients registered on an instance, but only a few of them has a notification_device_token, the stack can miss sending some push notifications. This issue comes from the pagination on the _find request to find the notifiable clients. By including a mango
selector to find only the OAuth clients with a notification_device_token, we can avoid this issue.
> Fix sending push notifications

- model/vfs/vfsswift/fsck_v1.go
fsck for swift impl V1 is completely buggy. Trying to at least fix some obvious errors like a bad index to find name (resulting in using dirID instead of name) and using an impl_v2 function to determine docID which should not be defined to be autogenerated by couchdb
> Fix fsck_v1

- docs/konnectors-workflow.md
At first we spotted typos in `account_types` occurences. But I read the whole documentation for my culture and saw other little typos.
> docs: Fix typos in konnectors workflow docs

- docs/doctype.md
Links are working on github but not on our doc's website (https://docs.cozy.io/en/cozy-stack/doctype/) 
Hope that fix the issue
> doc: Create links

- cmd/files.go
- docs/settings.md
- model/sharing/indexer.go
- model/vfs/couchdb_indexer.go
- model/vfs/vfs.go
- web/instances/instances.go
- web/settings/disk_usage.go
- web/settings/settings_test.go
File older versions can take a significant amount of disk size. 
Using the `disk-usage` endpoint, it is not currently possible to know what part of `used` size is taken by current version of the files and what part comes from old versions.
This PR adds information on the disk size taken by only the last version of files and the total size of older versions.
This will be available to frontend applications that will be able to show this information to the end user, allowing the user to take the right decision when dealing with space issues. It will also be available in `cozy-stack files usage` command to allow support to explain users how the disk space is used.
> Add versions total size to disk-usage endpoint

- worker/migrations/migrations.go
When a cozy instance is migrating to Swift layout v3, its CouchDB
documents for io.cozy.files are updated to add the internal_id
attribute. The trigger for thumbnails add a job. But as we were giving
only the new document, and not the old one, the sameImg comparison in
the thumbnail worker would fail, and a new thumbnail may be recreated.
And, as we can have a race condition between getting the Swift container
for the thumbnails and locking the VFS, it could be put in the old data
container.
> Send the old doc to the realtime for swift migrations

- web/auth/auth.go
- web/middlewares/csrf.go
- web/middlewares/csrf_test.go
Using Expires for the cookie in the CSRF middleware can lead to some
issues, that Max-Age doesn't have. With Expires, the server defines the
expiration date, and this date will be interpreted by the client. The
client and the server can be in different timezones, or the client can
be misconfigured (no NTP). If the MaxAge configuration from the
middleware is short (let's say hours, not days), it can happen that some
clients throw the cookie as expired when they received it.
To do that, we have copied the CSRF middleware from echo, and made a
pull request for this change upstream. See
https://github.com/labstack/echo/pull/1450
> Use Max-Age for the cookie in the CSRF middleware

- docs/data-system.md
- docs/mango.md
- pkg/couchdb/couchdb.go
- web/data/data.go
- web/data/data_test.go
#2190 allowed _find queries to use bookmark. This make it possible for normal_docs as well.
> Support bookmark pagination for normal_docs

- docs/workers.md
- model/account/accounts.go
- model/account/credentials.go
- model/bitwarden/settings/settings.go
- pkg/consts/consts.go
- worker/migrations/migrations.go
This migrates all accounts from an instance to an encrypted cipher which belong to the cozy organization, so the password manager retrieve them automatically.
> Add accounts to organization migration

- model/bitwarden/oauth.go
- pkg/consts/doctype.go
We need new permissions for the bitwarden's token to be able to get the konnectors list and create new suggestions from the browser extension.
> Add bitwarden's permissions

- assets/templates/oidc_login.html
- docs/delegated-auth.md
- web/oidc/oidc.go
- web/routing.go
- web/statik/handler.go
When OIDC is configured on a context, we can now have a special domainthat users can remember easily. This domain will only serve an HTML page with a login button to start the OIDC connection process.
> Add a login domain for OIDC

- model/account/credentials.go
- worker/migrations/migrations.go
Some instances have accounts with bad credentials, causing errors on decryption. We log them as a warning as it is not a migration error.
> Log warning for bad credentials on migration

- model/vfs/store.go
- web/files/files.go
- web/files/paginated.go
The transformation of a list of referenced files to JSON-API was slow because it involves requests to CouchDB to compute the path of the files. This commit removes this request by using an id instead of a path for storing the secrets for thumbnails.
See #1902
> Optimize the references request

- web/middlewares/permissions.go
In theory, a short shortcode is exactly 12 characters. But sometimes, when people shares a public link with this token, they can put a "." just after the link to finish their sentence, and this "." can be added to the token. So, it's better to accept a shortcode with a final ".", and clean it.
> Accept . at the end of short sharecode

- cozy.example.yaml
- pkg/config/config/config.go
- worker/push/push.go
When testing push notifications with a end to end test, it is quite
handy to be able to have the stack connect to a fake FCM server (for
example to check the received notifications against expected notifications).
Here, we add a configuration key to configure the FCM server used by the
stack.
> feat: Ability to run FCM against a fake FCM server

- web/data/references_test.go
- web/files/references.go
The docid parameter for creating/listing/removing references was not decoded correctly: if a %2f was present, it should be interpreted as a /. This commit fixes that, but it also adds some fallback mechanisms to avoid that references that were created with the bug cannot be found and deleted.
> Fix / encoding of reference IDs

- worker/migrations/migrations.go
The migration script failed with a panic runtime error if no `vendor_link` exists in the konnector manifest, which is the case for few of them (which is being fixed).
As a workaround, we log a warning and skip this konnector migration if it has no `vendor_link`.
> fix: Skip konnectors with no vendor_link

- web/middlewares/user_agent.go
When developing in local with the Android emulator, it can be convenient to have the JS polyfill for subtle crypto as the inapp browser gives access to them only for secure domains.
> Add JS polyfill for inapp browser in dev

- web/middlewares/user_agent.go
Before Safari 11, the window.crypto API was not available and it causes a JS error when trying to login.
> Block old versions of Safari

- docs/realtime.md
- model/job/trigger_event.go
- pkg/realtime/realtime.go
- web/realtime/realtime.go
- web/realtime/realtime_test.go
The route POST /realtime/:doctype/:id can be used to send a JSON payload that can be received in the realtime, but won't be persisted to CouchDB. For example, it can be used by konnectors to send their progress to the Cozy Home app.
> Add a route to POST documents for the realtime

- model/bitwarden/settings/settings.go
- web/bitwarden/bitwarden.go
- web/bitwarden/bitwarden_test.go
When the extension is installed for the first time, we want the user to get its existing account. Therefore, we run the dedicated worker on the pre-login route, only if the `extension_installed` flag is set to false.
> Migrate accounts when extension is installed

- web/bitwarden/bitwarden.go
- worker/migrations/migrations.go
This fixes 2 errors that happened after a test:
* A konnector trigger without the associated manifest will raise an `Application not found` error: we log a warning instead
* A conflict might occur on the bitwarden settings doc, as we were trying to write it in 2 different places, and the job is run asynchronously: we now only update the doc after the job is pushed
> Migration edge cases

- go.mod
- go.sum
- web/middlewares/user_agent.go
Electron was seen as an old version of Safari, and was blocked as such. It is now correctly detected and not blocked.
See https://github.com/mssola/user_agent/pull/62
> Do not block Electron

- web/bitwarden/bitwarden.go
- web/bitwarden/bitwarden_test.go
- worker/migrations/migrations.go
The `accounts-to-organization` migration creates the organization key if it does not exist. However, the settings were not saved in database in the migration: the organization key was therefore lost and replaced by another one later, making all the migrated ciphers to be impossible to decrypt.
> fix: Save settings in the account migration

- docs/konnectors-workflow.md
- web/data/accounts.go
The account decryption was reserved to konnectors only. We make it possible for the apps services to do it as well if they pass an `include=credentials` parameter.
> Decrypt account if include param is credentials

- model/instance/errors.go
- model/instance/instance.go
- model/instance/lifecycle/destroy.go
- web/middlewares/instance.go
When deleting an instance, the first step is to clean the accounts. This step must not run twice in parallel if the instance deletion is runned twice. And if it fails, it must be manually managed. So, we have added a `deleting` flag on the instance to avoid those issues.
> Add a deleting flag on instance

- web/routing.go
Currently, we need to use a remote doctype to be able to use the Sentry API when using a webapp. Since we don't need on mobile app, let's add this URL to our allowed list of domain. 
This way, it will be easier to use Sentry for our web apps
> feat: Add Sentry to allowed CSP url

- web/bitwarden/bitwarden_test.go
- web/bitwarden/hub.go
When the owner of a cozy instance changes its password, the stack must
send a realtime event (logout) to the bitwarden clients. It allows them
to know that they must ask the new password to the user.
> Add logout event for bitwarden hub

- docs/settings.md
- web/settings/capabilities.go
No specific permissions are required to list the capabilities, only a valid token.
> Do not require a permission for capabilities

- web/middlewares/instance.go
- web/routing.go
When an instance is being deleted, it is marked as "deleting", which blocks access from a user and instance deletion retry from the manager. But it also blocks the API requests from the konnectors to clean the accounts, which is bad. This commit fixes this regression.
> Fix a regression for instance in deleting state

- model/bitwarden/settings/settings.go
- web/bitwarden/ciphers.go
- web/bitwarden/folders.go
- worker/migrations/migrations.go
The setting update might fail at the end of the migration worker if the settings were updated during the process.
> Fix conflict on account migration

- assets/locales/en.po
s/form a typing mistake/from a typing mistake
> fix: Typo on Cozy not found page

- cmd/apps.go
This PR aims at printing a useful message on stdout when installing or uninstalling apps or konnectors : 
```
./cozy-stack apps install --domain "cozy.tools:8080" drive
drive has been installed (1.18.23)
```
```
./cozy-stack apps uninstall --domain "cozy.tools:8080" drive
drive has been uninstalled
```
> Print useful message instead of manifest when (un)-installing apps/konnectors

- web/bitwarden/bitwarden.go
- web/bitwarden/bitwarden_test.go
In a real-case migration test, an instance had no organization key when the add-on was connected.
It was then created in both places: during the asynchronous account migration worker, and in the `/accounts/keys` route, resulting in a conflict on `io.cozy.settings.bitwarden` and ciphers created with the not-saved organization key.
We fix that by starting the migration worker after the keys creations, and log a warning if there is no organization key, as it should normally not happen.
> Start account worker after keys creation

- docs/notes.md
- model/note/open.go
- model/permission/permissions.go
- model/sharing/sharing.go
- pkg/consts/doctype.go
- tests/integration/lib/cozy_file.rb
- tests/integration/lib/note.rb
- tests/integration/tests/sharing_push_folder.rb
- web/notes/notes.go
- web/notes/notes_test.go
- web/permissions/permissions_test.go
This route can be used by clients to get information about a note and build the URL where the note can be opened.
> Add a route /notes/:id/open

- model/sharing/rule.go
- model/sharing/rule_test.go
When the Drive web app shares a single note to a set of recipients in read-write mode, it creates a sharing with a rule:
- add: none
- update: sync
- delete: revoke.
With this rule, the stack didn't create an io.cozy.shared for the note on the recipient instance, and thus, the note wasn't seen as part of the sharing. It means that later updates of this note made on the sharer instance are not accepted by the recipients, and the open route for notes sent parameters as if the note was local, not shared. With this commit, the io.cozy.shared is correctly created, which fixes our issues.
> Fix sharing a single note from Drive web

- model/sharing/replicator.go
- model/sharing/setup.go
- model/sharing/upload.go
- pkg/lock/simple_redis.go
When we have seen in the logs some cases where there a lot of failures
of the sharing workers in a short period of time, related to the lock.
They probably come of an accumulation of retry jobs. This commit tries
to tweak the parameters to avoid this cascading failure:
- decrease the number of retries
- increase the initial backoff period
- increase the debounce for the share-upload trigger
- increase the sequence number if the last try for uploading a file
fails (to allow to skip a corrupted file).
> Tweak the Cozy to Cozy sharing parameters

- model/vfs/vfsafero/impl.go
- model/vfs/vfsswift/impl_v3.go
In VFS Afero and Swift layout v3, if the same file is uploaded twice in parallel, it may corrupt the instance (with a duplicate file). The check to ensure the unicity of the path is made at the start of the upload, but the VFS lock is released during the upload, so we need to make again the check at the end of the upload (with the VFS lock held).
> Fix an issue when a file is uploaded twice

- model/sharing/revisions.go
- model/sharing/revisions_test.go
When a file or folder comes a sharing, is removed of the sharing, and
shared again, the stack can misinterpret the revisions tree of this
document. This commit makes the InsertChain method more robust for those
cases.
> Fix the revisions tracking for some special cases

- docs/mango.md
- web/data/data.go
- web/data/data_test.go
We used to add 1 to the limit in order to ensure there are more docs to
query. However, the returned bookmark was consequently the one for this
additional doc. As a result, the client was missing one doc for each
paginated query.
This PR removes this limit increment ; the downside is an additional query from the client when the result docs length is exactly the limit, as we cannot know there are actually no more docs.
> Fix bookmark paginated queries for _find

- assets/locales/en.po
- web/apps/serve.go
When a user tries to access an app that is not yet installed, we will show them an error page with a link to the store where they can install the app.
> Improve the app not found error page

- web/notes/notes.go
If a directory contains a note, and is shared by link, a user with this link should be able to open the note via the `GET /notes/:id/open route`. It was not the case, as the `sharecode` was not put in the response, but it is fixed in this commit.
> Fix opening notes in a shared directory

- web/apps/serve.go
When using {{.Flags}} or {{.CozyData}}, bytes were outputted in the HTML.
The template engine requires a string to be passed.
> fix: Flags and CozyData were passed as bytes instead of string

- web/bitwarden/bitwarden.go
When the 2 factors authentication is enabled on a Cozy instance, the iOS bitwarden app crashs at the login. It looks like it is an issue with the format of the JSON response. The code of the official bitwarden server and clients didn't inspire me, but I've found those lines in bitwarden_rs:
```rust
// https://github.com/dani-garcia/bitwarden_rs/blob/5cabf4d0400e0db3dffabc2cdafb803d811a01de/src/api/identity.rs#L338-L340
result["TwoFactorProviders2"][provider.to_string()] = json!({
"Email": email::obscure_email(&email_data.email),
})
```
So, let's try this format.
> Fix login from bitwarden iOS app with 2FA

- docs/files.md
- web/files/files.go
This is like this preivous [PR](https://github.com/cozy/cozy-stack/pull/2373) but for files: it allows to support bookmark pagination for `_find`. 
But unlike documents, we return the bookmark in a jsonapi `links: { next }` response, as it is done for the [notes](https://github.com/cozy/cozy-stack/blob/master/web/notes/notes.go#L60-L62).
> Add bookmark support for _find on files

- docs/doctype.md
- docs/permissions.md
- docs/sharing.md
- model/app/installer.go
- model/job/redis_scheduler_test.go
- model/permission/doctype.go
- model/permission/match.go
- model/permission/permissions_test.go
- model/permission/rule.go
- model/sharing/rule.go
- model/vfs/permissions_test.go
- pkg/consts/doctype.go
- tests/integration/tests/sharing_sync.rb
- web/permissions/permissions.go
- web/permissions/permissions_test.go
- web/realtime/realtime.go
Now, we authorize a wildcard on the doctype for a permissions. For example, a permission on io.cozy.bank.* will give access to io.cozy.bank, io.cozy.bank.accounts, io.cozy.bank.settings, etc.
And we enforce new rules for the doctype names. In particular, they must be only be composed of lowercase letters, digits, . and _. It will avoid confusion, particularly between . and - that are mapped to the same CouchDB database.
> Changes on the doctype for permissions

- model/instance/lifecycle/helpers.go
- model/session/session.go
- pkg/utils/utils.go
- web/apps/serve.go
- web/routing.go
RFC 5980 defines Internationalized Domain Names for Applications. It allows to have domain names like zoé.example.net.
> Add support for IDNA

- docs/realtime.md
- pkg/realtime/mem_realtime.go
- pkg/realtime/realtime.go
- web/realtime/realtime.go
- web/realtime/realtime_test.go
When a `SUBSCRIBE` order is sent to the realtime websocket, it can be convenient to cancel it later without having to close the websocket. The new `UNSUBSCRIBE` order can be sent to do that. It takes the same parameters that the `SUBSCRIBE`.
Fix #1921
> Add a way to discard a subscription in realtime

- .github/workflows/assets.yml
- .github/workflows/ci.yml
- .github/workflows/cli.yml
- .github/workflows/integration.yml
- docs/INSTALL.md
- docs/docker.md
- go.mod
- scripts/Dockerfile
The last two versions of Go are supported. This is now the version 1.13 and 1.14
> Add support for go 1.14

- web/settings/context.go
- web/settings/settings_test.go
When the context was not configured in the config file, the response to GET /settings/context was a 404. We will change it to a 200 with an empty object to make it easier for developers to use this endpoint.
Fix #2410
> Always respond with a 200 for /settings/context

- pkg/shortcut/shortcut.go
- pkg/shortcut/shortcut_test.go
Before, only .url files with CR LF where accepted (DOS file format). Now, it also accepts .url files with LF (UNIX file format).
> Make the shortcut parser more tolerant

- web/bitwarden/bitwarden_test.go
- web/bitwarden/ciphers.go
Unfortunately, bitwarden's jslib expects a 200
See https://github.com/bitwarden/jslib/blob/44b86f5dd028271059b70a00d7878fbb1a06023f/src/services/api.service.ts#L1001
> fix: Send 200 when importing ciphers

- model/vfs/errors.go
- model/vfs/store.go
- model/vfs/store_test.go
- web/files/files.go
Using return nil, nil with one nil for the result and one nil for the error is an anti-pattern, and it was the cause of a panic where we try to derefence a nil value. This commit removes this anti-pattern on the
VFS store, and thus fix the panic.
> Fix a panic when uploading with a base MetadataID

- web/bitwarden/ciphers.go
- web/bitwarden/hub.go
When passwords are imported in the bitwarden vault, the stack send a message in the bitwarden realtime hub to tell extensions that they should resynchronize their vault.
> Send a sync message after importing passwords

- docs/files.md
- web/files/files.go
The link was wrong, because it was missing the /_find part. In the stack ignored the cursor in the query-string. This commit fixes both issues.
> Fix the next link for POST /files/_find

- docs/sharing.md
We can only call this route on the cozy of the sharer.
> docs: Sharing add a note for the revocation

- model/note/open.go
- model/permission/permissions.go
- model/sharing/sharing.go
- tests/integration/tests/sharing_sync.rb
- web/middlewares/permissions.go
- web/notes/notes.go
A note can be opened on the same Cozy instance as it has been created by the owner of its instance (easy). Or, the note can be inside a directory shared by link, and the visitor can also open the note with the same sharecode.
And there are the notes inside a Cozy-to-Cozy sharing. The note should be opened on the instance where it has been created. The sharecode must gives read-only permission if the person that tries to open the note is marked as read-only in the sharing, or if the sharing rules forbid writing the note. Else, it must be read-write.
Note that we have to take into account the star model used for sharing. Two recipients instances can't talk directly as they have no common authentication proof, the requests must be proxified by the sharer instance.
> Rework opening shared notes

- model/note/open.go
- web/notes/notes.go
When a directory is shared (Cozy to Cozy) with a note inside it, a user that previews this sharing can open the note. And if the sharing allows edition, the user will be able to edit the note. The preview sharecode will only have read permissions, but the stack will generate a share-interact token so that the user can write on the note.
> Allow to open a note from the sharing preview

- model/sharing/files.go
- model/sharing/files_test.go
- tests/integration/tests/avoid_name_conflict.rb
- web/sharings/sharings.go
When a folder is shared, and several renaming happens in a short lapse of time, the sharing synchronisation can encouter temporary conflicts of name. Those errors were silently ignored, and it is no longer the case. It should improve the sharing resiliency.
> Fix a case of conflicts in a sharing

- assets/locales/en.po
- docs/bitwarden.md
- web/bitwarden/bitwarden.go
- web/bitwarden/bitwarden_test.go
The mobile app for passwords can ask the stack to send by mail the hint for the password via a new route, compatible with the bitwarden implementation.
> Allow the bitwarden mobile app to ask the hint

- assets/locales/en.po
Space after a dot was missing.
> fix: Space missing between two sentences

- assets/templates/sharing_discovery.html
- cozy.example.yaml
- web/sharings/sharings.go
When a member of a sharing is asked for the URL of their cozy instance, the input widget offers a suggestion on the domain. This suggestion can now be customized per context (the default is "mycozy.cloud").
> Add a sharing_domain config entry

- web/apps/apps.go
- web/instances/fixers.go
Fix incoherent source for app install when no source is explicitely given between [cli default](https://github.com/cozy/cozy-stack/blob/a6462057decfa27acebbada072cac263f2bd82ae/cmd/apps.go#L273) and [admin api default](https://github.com/cozy/cozy-stack/blob/master/web/apps/apps.go#L110) by explictely using registry stable channel.
Also explicitely use registry stable channel when re-installing konnectors to remove account inside orphan accounts fixer.
> Explicitely use stable registry channel when installing app without source

- web/apps/apps.go
When requesting the stack as `text/event-stream` to install or update app/konnector, the event-stream response contain an extra linefeed (`\n`) after each event.
This PR removes the extra linefeed.
> Fix event-stream extra linefeed

- cmd/feature.go
- docs/cli/cozy-stack_features.md
- docs/cli/cozy-stack_features_config.md
- scripts/completion/cozy-stack.bash
- scripts/completion/cozy-stack.zsh
- web/instances/feature.go
- web/instances/instances.go
Allow to query stack for feature flags configured in configuration file, inside a specific context
> Add context features from config to admin endpoint and cli

- web/middlewares/user_agent.go
- web/middlewares/user_agent_test.go
Firefox on iOS has a lower version number than Firefox on desktop and android. It also uses the webkit engine, and not the Gecko one. So, it makes sense to have special user-agent rules to detect it, and to not block it.
> Fix support of Firefox on iOS

- docs/references-docs-in-vfs.md
- pkg/jsonapi/data.go
- pkg/jsonapi/jsonapi.go
- web/files/referencedby.go
- web/files/referencedby_test.go
- web/files/references.go
When adding new `referenced_by` objects to an io.cozy.files document,
we expect to get the updated list of references in return.
Since the document is updated to add new references, its revision has
changed and should therefore be returned as well so clients won't have
to make another request to get the updated revision and make new
changes to the document.
> Return updated file rev and added references

- model/job/worker.go
- model/sharing/files.go
- model/sharing/member.go
- model/sharing/rule.go
- model/sharing/upload.go
- tests/integration/tests/sharing_moves_n_delete.rb
- tests/integration/tests/sharing_sync.rb
- web/server.go
Example:
1. a folder foo is shared between Alice and Bob
2. foo contains a directory bar, and inside this directory, there is a file baz (on both cozy instances)
3. Alice moves foo/bar/baz to foo/baz, and just after, deletes foo/bar
4. the sharing process must make the move before the deletion, even if bar has a lower id than baz (and comes first in the revs_diff).
> Fix a sharing issue with moves and delete
